### ISSUE TITLE
Interviewer names: ordering of first and last names.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1065]
Interviewer names associated with interviewer profiles are stored as "First Last" and we'd like to consider switching them to being stored as "Last, First".

See e.g. "Raymond C. Ferguson" under "Interviewer Profiles" at  https://staging-digital.sciencehistory.org/admin/works/hm50ts86r#nav-oral-histories ) 

Note 1: this is distinct from the "Interviewer" `creator` metadata visible at https://staging-digital.sciencehistory.org/works/hm50ts86r , which is correctly stored as e.g. "Ferguson, Raymond C."

Note 2: At the moment, these interviewer names themselves are never shown to the public. Only the associated biographical _profile_ is visible (and we're not talking about changing that.) For an example, see Ferguson's profile at https://staging-digital.sciencehistory.org/works/hm50ts86r .

**Comment by eddierubeiz** [comment]
Jonathan notes:  we may also wish to store names exactly as they are in the microsite, but in that case we should remove the FAST autocomplete on the form used to enter *new* interviewer profiles, *and* the hint telling the user to enter the name as "Last, First".

**Comment by jrochkind** [comment]
OK, the way I understand this issue.

We already have interviewer name metadata in our "creator" field, with sub-type "interviewer". That is not what we're talking about here -- those are already FAST-autocompleted, and are `lastname, first` and there is no reason we are aware of to change that. 

We are talking about the way we are  storing *interviewer profiles* specifically. We have a list of interviewer profiles. They have the name of the person profiled on them to identify them in lists. They are linked to Oral Histories so the profiles can be displayed. Those names attached to profiles -- per previous discussion, they autocomplete from FAST too, and have a hint suggested `lastname, first` entry. 

The problem is in trying to migrate them from the microsite. They are not stored that way in the microsite. So how do we import them as `last, first`?  maybe we don't need to, we just import them as is -- in which case we would remove the FAST autocomplete, and the instructions saying to enter as last/first. 

The main challenge  there is that our UI element for linking profiles to Works lists the names in alphbetical order. Is listeing names as `first last`  in alphabetical order going to be usable?

This problem will also apply to the similar way we are approaching Interviewee Biographical entries.

**Comment by eddierubeiz** [comment]
Spoke to @lsberry16 yesterday and we will be using "Last, First" in the digital collections. See https://staging-digital.sciencehistory.org/admin/interviewer_profiles .
