### ISSUE TITLE
Oral histories not getting emails from by-approval requests

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1066]
When someone requests oral history assets that require staff approval, an email is supposed to go out to oral histories staff. 

@lsberry16 reported that's not happening, the emails are not arriving. 

We need to investigate. What email is the "from" and "to"?  Is it a spam prevention issue?

**Comment by lsberry16** [comment]
I just tested this out by requesting Caroline Kisker. The expected email came through to oralhistory@sciencehistory.org and I was able to click the link, log in and approve the request. However, I've not yet received any email to the personal email account letting me know that my request had been received or that it's been approved and attaching the PDF.

**Comment by jrochkind** [comment]
Huh, so this time you DID get the email to oralhistory@sciencehistory.org alerting you to the pending request... that's the email you DIDN'T get from three requests last week. WEIRD. 

If these are just unreliable and sometimes show up and sometimes don't... not sure what to do about it. 

The end-user emails with links also definitely have shown up at least sometimes. I hope those aren't also unreliable; I'm hoping if you give it a few more minutes you will get the email to personal account. 

Also... if you need us to give you a way to *delete* requests from the table (like for test requests?) let us know.

**Comment by lsberry16** [comment]
I just found the email with the file download links in my Junk folder, so that one's okay, at least. I can keep submitting test requests to try and make sure the emails are now getting through reliably to oralhistory@sciencehistory.org.

I don't know that staff needs a way to delete requests from the table on the regular, but if you guys can do it from the back end every now and then after there's been a particular spurt of testing like this one, that would be excellent.

**Comment by jrochkind** [comment]
We can delete em on the back end, just give me dates/times/names so we have a paper trail and make sure we're doing what's expected.

**Comment by lsberry16** [comment]
OK, cool--I think that's the right way to go for now, at least. 

I've put in three more requests, two from my gmail account and one from my live.com account, which I used the first time. I've not yet gone into the dashboard to approve/deny these requests. I've been waiting to see if I receive any confirmation emails, but so far nothing for either account, and I've checked my spam folders.

**Comment by eddierubeiz** [comment]
I requested from my gmail account this morning and received the email immediately. (And I wasn't testing, either -- I was legitimately a patron who also happened to be an employee.)

**Comment by jrochkind** [comment]
@lsberry16 

OK, you are saying you twice now did not receive the request emails to oralhistory@sciencehistory.org?  But earlier today, you *did* receive the request email? So it appears sometimes it goes through, sometimes it does not?

That is difficult to diagnose. Drats!

To be clear and make sure we're on the same page, my expectation is: If the OH is marked by-request *without* approval needed, the requester should receive an email immediately with links. If the OH is instead marked approval-needed, oralhistory@sciencehistory.org should receive a notification email immediately; the requester will not receive any email until staff responds to it in dashboard.

**Comment by lsberry16** [comment]
OK, let me back up and make sure we're clear on what I'm testing and what's happening when I do it.

Today, I have ONLY tested the process for oral histories that require staff intervention. My understanding of what is supposed to happen when a user requests access to one of these interviews is:

1) An email goes to oralhistory@sciencehistory.org saying the request has been made and providing a direct link to the OH Requests table so that the staff member can approve or deny the request. Simultaneously...
2) An email goes to the requester, letting them know that their request has been received and is pending.
3) Once the staff member approves the request, an email goes to the requester, containing download links.
4) If the staff member rejects the request, an email goes to the requester saying that the request has been denied.

Last week, we noticed that (1) didn't seem to be happening. I've tested that with 4 different requests today, and each time, it did, in fact, happen.

(2) Has definitely not happened with any one of the 4 requests that I submitted today. Perhaps I was mistaken in thinking that this was a thing that was supposed to happen?

I have approved only one of my four test requests so far today, but on that one, (3) did happen as expected.

I have not rejected/denied any of my four test requests yet today, so I don't have any info on this point yet. I'll get back to this later.

**Comment by jrochkind** [comment]
Aha! @lsberry16 no, we never programmed (2) above to happen. There nos email to requester letting them know their request has been received and is pending -- just a confirmation in the web browser after they submit. 

We can do so if it's desired, I didn't realize it was!  So this may just be miscommunication between you and I?

(2) definitely won't happen, because we did not write logic for it!

**Comment by lsberry16** [comment]
I just misremembered, then--no biggie!

Let me go approve and reject some of those requests I put in earlier and make sure everything looks ok.

**Comment by lsberry16** [comment]
Yep, everything worked as expected. I'm thinking we might want to keep a record of the approved/denied response emails we send. Could we cc oralhistory@sciencehistory.org on those?

**Comment by jrochkind** [comment]
@lsberry16 sure, can you make a GH issue on it?

**Comment by lsberry16** [comment]
Will do.

**Comment by jrochkind** [comment]
could also/instead keep a record in the application database, hypothetically. But CC email is easy enough.

**Comment by lsberry16** [comment]
I though you might prefer not junking up the database with it; but whichever you like better works for me.

But GitHub/ZenHub still aren't letting me make new tickets. Here's the wording I was going to use:

Issue--
Carbon copy oralhistory@sciencehistory.org on emails responding to oral history access requests

Details--
When a staff member approves or rejects an oral history access request, send a cc of the response email to oralhistory@sciencehistory.org for our records.

**Comment by jrochkind** [comment]
After talking to Lee, we currently think all is working well here, and both aspects of the problem report were misunderstandings/miscommunication.
