### ISSUE TITLE
Lee can't create issues via zenhub

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#1070]
Can I create this issue?

**Comment by jrochkind** [comment]
You just did, hooray!

**Comment by lsberry16** [comment]
Can we not create the issue in ZenHub?

**Comment by jrochkind** [comment]
Aha, is that what is going on?  I myself can create issues in Zenhubs, but maybe you don't have the right permissions to do it via zenhub or something is wrong on zenhub... that's something we can look into more with zenhub support perhaps!  zenhub is a third-party which is supposed to integrate with Github, but there may be something we don't understand about it. 

What happens when you try via Zenhub, is there an error message, what does it look like?

**Comment by lsberry16** [comment]
OK, so when I try to create a submission via ZenHub, I get an error. It just says, "app.zenhub.com says an error has prevented the creation of the issue."

**Comment by lsberry16** [comment]
So, in the meantime, if we need me to create an issue, I'll go straight to GitHub. Problem temporarily solved. Ish.

**Comment by lsberry16** [comment]
I also can't do things like apply labels to issues, unless I just don't know how to. Which is possible. I assume that I open the issue and on the right hand side where it says "Labels" there should be something clickable, but there isn't for me.

**Comment by MDiMeo** [comment]
@lsberry16 is enjoying retirement and not worried about this anymore.
