### ISSUE TITLE
Microsite interviews with no destination digital collection oral history works.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1082]
I still haven't been able to determine the destination record in the digital collections for the following microsite interviews:

1. Bailar `PUBLISHED`  https://oh.sciencehistory.org/node/5358/
2. Braell `PUBLISHED`  https://oh.sciencehistory.org/node/5470/
3. Brent `PUBLISHED`  https://oh.sciencehistory.org/node/7614/
4. Charron `PUBLISHED`  https://oh.sciencehistory.org/node/5490/
5. Chowdhry `PUBLISHED`  https://oh.sciencehistory.org/node/7666/
6. Craft `PUBLISHED`  https://oh.sciencehistory.org/node/5507/
7. Cyster `PUBLISHED`  https://oh.sciencehistory.org/node/5512/
8. Ducy `PUBLISHED`  https://oh.sciencehistory.org/node/5531/
9. Everhart `PUBLISHED`  https://oh.sciencehistory.org/node/5543/
10. Farber `NOT PUBLISHED`  https://oh.sciencehistory.org/node/7522/
11. Folkers `PUBLISHED`  https://oh.sciencehistory.org/node/5302/
12. Jensen `NOT PUBLISHED`  https://oh.sciencehistory.org/node/5629/
13. Kebarle `PUBLISHED`  https://oh.sciencehistory.org/node/7585/
14. Keene `PUBLISHED`  https://oh.sciencehistory.org/node/7667/
15. Koelle `PUBLISHED`  https://oh.sciencehistory.org/node/5654/
16. McAllister `NOT PUBLISHED`  https://oh.sciencehistory.org/node/7518/
17. Omary `NOT PUBLISHED`  https://oh.sciencehistory.org/node/5929/
18. Oreffice `PUBLISHED`  https://oh.sciencehistory.org/node/5737/
19. Pyott `PUBLISHED`  https://oh.sciencehistory.org/node/7657/
20. Raychaudhuri `PUBLISHED`  https://oh.sciencehistory.org/node/5753/
21. Roberts `PUBLISHED`  https://oh.sciencehistory.org/node/5758/
22. Sarett `PUBLISHED`  https://oh.sciencehistory.org/node/5421/
23. Sondek `PUBLISHED`  https://oh.sciencehistory.org/node/5796/
24. Standing `PUBLISHED`  https://oh.sciencehistory.org/node/7672/
25. Stavropoulos `PUBLISHED`  https://oh.sciencehistory.org/node/5801/
26. Stryer `PUBLISHED`  https://oh.sciencehistory.org/node/5808/
27. Taunton-Rigby `NOT PUBLISHED`  https://oh.sciencehistory.org/node/7655/
28. White `NOT PUBLISHED`  https://oh.sciencehistory.org/node/6436/
29. Woolston `PUBLISHED`  https://oh.sciencehistory.org/node/7668/

**Comment by lsberry16** [comment]
FIXED INCORRECT NUMBER IN PRODUCTION

1.	Braell PUBLISHED https://oh.sciencehistory.org/node/5470/
2.	Cyster PUBLISHED https://oh.sciencehistory.org/node/5512/
3.	Ducy PUBLISHED https://oh.sciencehistory.org/node/5531/
4.	Everhart PUBLISHED https://oh.sciencehistory.org/node/5543/
5.	Craft PUBLISHED https://oh.sciencehistory.org/node/5507/
6.	Pyott PUBLISHED https://oh.sciencehistory.org/node/7657/

The other 23 genuinely do not seem to be in Digital Collections and I don't know why not. I'll have to run the list by Annabel, Nic and Hillary and see if they can figure out what's up. I notice that some of these are unpublished, and the remainder, I think, are Pew folks who may have significant restrictions on them. Perhaps there were no records for them in the OPAC and since that's often the starting point for creating the records in Digital Collections, maybe that's the problem.

**Comment by lsberry16** [comment]
Hillary's team will create records in the Digital Collections for 13 of them; the other 10 are in process for one reason or another either they lack final release forms or they need reformatting). It would be nice for whoever finishes these up eventually not to have to re-enter data for them that’s already been keyed in once. Hillary's team will create skeleton records for them to house the biographical data until that day comes.
 
1.	Bailar PUBLISHED https://oh.sciencehistory.org/node/5358/ : FREE ACCESS with FULL INTERNET RELEASE (interviewee deceased). Apparently never made it into the OPAC or onto the library shelves. 
2.	Brent PUBLISHED https://oh.sciencehistory.org/node/7614/: RESTRICTED – transcript and audio sealed for 75 years from date of interview due to privacy concerns. Let’s keep even the metadata private, since we cannot share this material with researchers under any circs for the foreseeable future.
3.	Charron PUBLISHED https://oh.sciencehistory.org/node/5490/: FREE ACCESS (auto-fulfill internet requests). UCLA agreed to keep portions sealed until 2022. Sealed sections are redacted from the transcript, but the situation with the audio is less clear to me. Can we seal all audio files until next year?
4.	Chowdhry PUBLISHED https://oh.sciencehistory.org/node/7666/: FREE ACCESS (auto-fulfill internet requests)
5.	Kebarle PUBLISHED https://oh.sciencehistory.org/node/7585/: FREE ACCESS with FULL INTERNET RELEASE OF TRANSCRIPT and REDACTED AUDIO. Keep unredacted audio file private.
6.	Keene PUBLISHED https://oh.sciencehistory.org/node/7667/: PERMISSION REQUIRED
7.	Koelle PUBLISHED https://oh.sciencehistory.org/node/5654/: PERMISSION REQUIRED
8.	Omary NOT PUBLISHED https://oh.sciencehistory.org/node/5929/ : METADATA ONLY
9.	Raychaudhuri PUBLISHED https://oh.sciencehistory.org/node/5753/: FREE ACCESS (auto-fulfill internet requests)
10.	Sondek PUBLISHED https://oh.sciencehistory.org/node/5796/: FREE ACCESS (auto-fulfill internet requests) but note: we do not have audio files 2-1 and 2-2 because UCLA sealed them.
11.	Standing PUBLISHED https://oh.sciencehistory.org/node/7672/: FREE ACCESS (auto-fulfill internet requests)
12.	Stryer PUBLISHED https://oh.sciencehistory.org/node/5808/: RESTRICTED – sealed until 2022 or Stryer’s death. Keep even the metadata private until we are able to share with researchers.
13.	Woolston PUBLISHED https://oh.sciencehistory.org/node/7668/: FREE ACCESS with FULL INTERNET RELEASE (interviewee deceased)
THESE INTERVIEWS ARE IN PROCESS
14.	Farber NOT PUBLISHED https://oh.sciencehistory.org/node/7522/: unpublished because we have no signed final release form from Farber. 
15.	Folkers PUBLISHED https://oh.sciencehistory.org/node/5302/
16.	Jensen NOT PUBLISHED https://oh.sciencehistory.org/node/5629/
17.	McAllister NOT PUBLISHED https://oh.sciencehistory.org/node/7518/
18.	Oreffice PUBLISHED https://oh.sciencehistory.org/node/5737/
19.	Roberts PUBLISHED https://oh.sciencehistory.org/node/5758/
20.	Sarett PUBLISHED https://oh.sciencehistory.org/node/5421/
21.	Stavropoulos PUBLISHED https://oh.sciencehistory.org/node/5801/
22.	Taunton-Rigby NOT PUBLISHED https://oh.sciencehistory.org/node/7655/
23.	White NOT PUBLISHED https://oh.sciencehistory.org/node/6436/
