### ISSUE TITLE
Featured topic: Oral Histories

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1135]
This new featured topic will replace the "Science on Stamps" featured topic.

The ingredients for a featured topic are:
- a 700x700 pixel image (provided by Lee)
- a blurb (which we can take from the existing one on the OH collections page)
- a genre or set of subjects. Easy: we'll use the `oral histories` genre. 

Note: this will link to a page like e.g. [water](https://digital.sciencehistory.org/focus/water) and not [the actual oral history collections page](https://digital.sciencehistory.org/collections/gt54kn818), unless we change the behavior of featured topics slightly, which we could do.

@lsberry16 : we will need a square image 700 pixels on a side. Assume the bottom sixth of the image is hidden by the label created in front of the thumbnail. More details [in the wiki](https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/1646428165/Creating+a+thumbnail+for+a+Featured+Topic+landing+page).

**Comment by eddierubeiz** [comment]
Oh, we could also change the behavior for the featured topic object so it can just behave like a link if it's created using a URL.

**Comment by jrochkind** [comment]
> Note: this will link to a page like e.g. water and not the actual oral history collections page. Not a big deal, we assume: they're almost the same thing, except for the special OH facets.

Let's explore that, actually. It does not need to be such. 

I wonder if instead of using our normal technology for the "featured topics", the link to OH on home page in that "featured topics" area -- should just link to our OH Digital Collection home page?

Since we have and are spending so much time making it a good OH landing page -- we plan to do more changes to it taking it even further away from the typical "featured topic" page. 

Will require some adjustments to our code, instead of just adding a "featured topic" config for OH, but it's do-able, and I think is probably the way to go

@eddierubeiz one way to organize our code... might be adding to the "featured topic" configuration and class definition, a, like, "just use this url" line. Where instead of linking to a 'featured topic' page, the logic on home page can see "oh, it is configured 'just use this link'", and well, just use that link.  Yeah, what I just saw you post as you were writing this!  We have an existing Env config for "oral history collection ID" so might try to reference that somehow... this maybe gets more complicated than "just do this", but we can work it out somehow maybe. 

Another option would be not using the existing "featured topic" infrastructure at all, instead just adjust the front-page  logic to be like "8 things from 'featured topic' config, plus this one hard-coded thing".  

Whatever is easy.

**Comment by eddierubeiz** [comment]
Exactly!

**Comment by jrochkind** [comment]
@eddierubeiz on image, we have a high-res copy of the "standard oral history graphic" that Lee gave me, that I put at... https://github.com/sciencehistory/scihist_digicoll/issues/1133#issuecomment-839040134

So unless Lee has another one preferred, just take that and resize it down to 700?

**Comment by eddierubeiz** [comment]
Alternately it might be fun to arrange a collage of e.g. 9 OH headshots. Human faces are so much more engaging than a picture of a book and a TASCAM.

**Comment by lsberry16** [comment]
I've assembled a folder containing images of 7 of our interviewees here: https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Institute%20for%20Research/Oral%20History/Digital%20Collections/Images/Interviewees%20for%20main%20page 
We'll want to use a thumbnail version of the Smyth portrait for the Featured Topic: Oral Histories button on the Digital Collections home page.

**Comment by MDiMeo** [comment]
@apinkney0696 Instead of Smyth, we decided to use the Horiba image, included in Lee's folder above. Please crop following the specs above. Thanks!
