### ISSUE TITLE
Create two new metadata fields: Transcription and Translation

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/scihist_digicoll#1183]
Create two new metadata fields for Transcription and Translation. They should be on the asset level and use Plain Text. 

Once this functionality exists, we agreed to revisit this in one month -- after we've used the feature -- to discuss any issues that have arisen.

**Comment by jrochkind** [comment]
@MDiMeo @apinkney0696 for the 'translation' field I'd like to propose an extension to make it future-proof:

1. Each translation should be labelled with the language the translation is in ("English" for these)
2. The translation/language-label field should be repeatable, to support multiple translations. 

What do you think? Alternately, perhaps I am over-complicating; since right now we plan only a single English translation, maybe we make only a single non-repeatable translation field, without language field, no more complicated than we need at present. We can always do a data migration later if we add translations in other languages and/ore more than one translation.  (In this case, I might call the field "English Translation" to be clear). 

Thoughts?

**Comment by jrochkind** [comment]
I think @MDiMeo doesn't see or doens't have time to give feedback, @eddierubeiz do you have any thoughts on question above, should we make translations repeatable and langauge-labelled for future-proofing, or is that over-complexity for current needs?

**Comment by jrochkind** [comment]
After talking to @apinkney0696 we decided for now keep it simple what we need for our actual use cases:

1. A "transcription" field, it won't have it's own language code, we'll use the existing work-level language assignmetns and not worry about a page-level language code. 
2. A single "English translation" field. That's what we have a need for, that's what we'll create. (It is important to have metadata on what language a translation is in, so we'll name this one "english translation" so if anyone is ever tempted to put eg spanish in there, they'll know we need a data model refactor that tags language on translation. :) )

**Comment by eddierubeiz** [comment]
This is great.

**Comment by eddierubeiz** [comment]
The language of the work itself is already part of the work-level metadata, and if the work is in a particular language, the transcriptions will be, too.

As for the translations, totally fine with hard-coding the word "English" into the name of the field at least for now.

**Comment by jrochkind** [comment]
@apinkney0696  says in slack:

> Hi all, I'm taking some time off through the rest of the week, but I wanted to touch base about the new transcription/translation fields before I sign off. @Jocelyn McDaniel was trying out the new fields in staging this morning, and she'll post any additional feedback here. I think the only concern at the moment is whether there will be support for special text characters, strikethroughs, etc., which sounds like it will be a later project. Generally, where the fields are located in the DC and how they work will be fine with respect to Jocelyn and Jahna's workflow, so I think the function can be pushed to production.

My response:

So it depends on what you mean by “special” characters.

Umaluts and other accounts should be fine — that’s just text.

Strikethrough I do not know how to support. I suspect most of our peers are using TEI for this, which I don’t think we plan to do. There may be other ways to support it, but I don’t know what they are, it would require resources.  Same applies to “superscript” I think.

It is up to… someone who isn’t me (@MDiMeo ?), to decide if it’s good enough to start using this as is, or if you want to schedule time for us to figure out if there’s a way to support strikethrough and other features, and not start using this until we do. Not my call!

So umlauts and acccents, no problems. Strikethrough and superscript, problem. So not everything you may be thinking of as “special” is the same, it just depends. If there are other things you have in mind, you can ask me — or really, you can just try it in the demo and see?

We might want to copy this Q&A to the Github Issue so we preserve it for posterity instead of it just being in text chat? I will do so.

(note Jocelyn does not seem to have a github acct so will not be in the loop here)

**Comment by jrochkind** [comment]
From Michelle:

> es, this is the plan: Jocelyn tests the software with actual transcription and translation to flag what is working or not. I'll be curious (and hope!) that those umlauts show up, for instance. As for things like strike through and superscript, we're going to ignore them for now in the application. BUT I would like you to keep the rich text version in your Word/Omega file AND make a note somewhere in our spreadsheet to say what trouble you ran into when you pasted from your document into the Digital Collections fields.

> This will allow us to have a cost/benefit analysis, and will give us a big picture on the issues so we can research with our peers

**Comment by MDiMeo** [comment]
This is ready to publish. Jocelyn tested and found that plain text worked for everything except strikethrough. However, we will use [strikethrough] and [/strikethrough] instead. @apinkney0696 found good peer examples to help guide this decision.
