### ISSUE TITLE
Small copy edits to the Oral History landing page.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1185]
David Caruso requests the following updates to the [OH landing page](https://digital.sciencehistory.org/collections/gt54kn818):
- In the intro, remove the hyphen in "professionally-edited” and change “invaluable” to “remarkable” and “a unique insight” to “unique insights.”
- In the Nanotechnology paragraph, change "career" to “careers” and “that” to “who” in "documenting the lives and career of key scientists and engineers that shaped…” 
- "Resources for Education and Action for Community Health in Ambler (REACH Ambler)” and the "More oral history projects…" links should open new windows.

**Comment by jrochkind** [comment]
@MDiMeo As ordinary for regular work, we won't work on it until prioritized at a weekly meeting. 

We also should check-in again about the workflow for various people "not on the team" to report change requests/problems to Digital Collections, and advertise it. "Email Eddie" is not ideal! 

On the specifics:

1. We decided that "professionally-edited" was grammatical, but we should just go with David's opinion on that?
2. The text is a copy of the text on https://www.sciencehistory.org/oral-history-projects It should be changed/fixed there first, and then we can copy it again. 
3. I don't think I understand the policy on new windows. I would like to do this consistently in Dig Coll instead of every link is different. I thought going from Dig Coll to parts of the main website would be considered an "internal link" that should not get a new window. But "we" (who? maybe Communications?) should just decide how to treat these in the site as a whole, I think?

**Comment by MDiMeo** [comment]
These requests for changes originated with Dana. I've spoken to her about them and paste her responses, below. Please make the changes to one and two. If point three needs more discussion, we can do so at a Monday meeting. Thanks.

1. The hyphen in "professionally-edited" is not grammatically correct; Chicago style does not hyphenate compound modifiers formed with adverbs ending in -ly.
2. I updated the copy on the projects page where the Nanotechnology copy came from
3. I do not consider going to and from the digital collections site and the main site to be internal links so I would always make them open in a new window. However, on the main site there are places where we can't actually do this because of the way the site was built so he might be seeing inconsistency there, but I always have links to external sites like digital collections open in a new window in page copy and wherever else I can. All that said, I can live with same window links in this case.

**Comment by jrochkind** [comment]
Aha! merging!

**Comment by dcaruso-scihist** [comment]
Yes, I can comment on an issue, @eddierubeiz
