### ISSUE TITLE
Customize heroku maintenance page

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1201]
With SHI branding etc. maybe a way to automatically generate it with a speciifc message of expected lenght of outage etc. 

https://devcenter.heroku.com/articles/maintenance-mode#customizing-your-maintenance-page

**Comment by eddierubeiz** [comment]
This breaks down into two parts:
- Part 1 (difficult): Generate branded, customized HTML to use as a maintenance page. The error message needs to be customizable. The HTML can't refer to any assets served by the digital collections, since it's supposed to function properly when the site is down. We could steal a page from the main site, e.g., and customize that.


- Part 2 (easy): 
```
aws s3 cp maintenance.html s3://some_public_bucket/maintenance.html
heroku config:set MAINTENANCE_PAGE_URL=//s3.amazonaws.com/some_public_bucket/maintenance.html --app scihist-digicoll-staging
heroku maintenance:on --app scihist-digicoll-staging
```

Just as a proof of concept I have something up at `https://s3.amazonaws.com/scihist-digicoll-production-derivatives/maintenance/maintenance.html` but the page could really go anywhere, including, honestly, the main Institute website.

**Comment by jrochkind** [comment]
Here is what current draft of our customized "down for maintenance" page looks like, fyi @MDiMeo and @apinkney0696 . This seems pretty good to me, but let me know if you think it has any issues. 

![Screen Shot 2021-07-12 at 2 57 40 PM](https://user-images.githubusercontent.com/149304/125341526-aebd4e80-e321-11eb-9445-7ddd7970febf.png)
