### ISSUE TITLE
Automatically clear files and folders from S3 upload bucket 24 hours from ingest

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1212]
Hi all, I chatted with Jahna, and we both had the same opinions on the S3 bucket, so here is the official request!

Upon **ingest** into the DC, the file should automatically clear after **24 hours**. 

We both agreed that it's easy for us to re-upload to the S3 bucket if we make a mistake and that having a crowded S3 bucket is more of an annoyance than having to re-upload on occasion.

I realized since our last meeting that the old files in S3 may have actually been automatically clearing as they are supposed to, but it's the folders that contain those files that remain and those are causing the bucket to look full. So I suppose the second to-do item here is to get folders to automatically clear once all of its file contents have cleared.

Please let me know if any of this is unclear, and thanks so much in advance!

**Comment by eddierubeiz** [comment]
Good catch. In other words, remove all files and folders after 24 hours.

**Comment by jrochkind** [comment]
Thanks! 

Intersting, normally there is no such thing as an "empty" folder on S3, so it shouldn't be possible for a folder to still be there if all it's contents have been deleted. And yet you are seeing what you are seeing!

We will have to investigate, ok!

**Comment by apinkney0696** [comment]
Interesting! Perhaps a bug! Here is what I see on my end:
![image](https://user-images.githubusercontent.com/78036563/122278680-2af47b80-ceb5-11eb-9502-4c375025dfb6.png)
those circled folders should be "open" but it doesn't show any contents on my end

**Comment by jrochkind** [comment]
Thanks, that's useful to see!

I have a hunch there's some kind of "hidden" files in there. So the real bug is not the schedule on which things get deleted, but that folders end up staying there forever due to some kind of hidden file that stays there forever. 

That may be a bit annoying to fix, sadly. :(  (And it still probably has nothing to do with the modified date!)

**Comment by jrochkind** [comment]
OK, I took a look because I was curious -- those folders really do appear to be empty in S3 via AWS console, but still showing up! Which violates my understanding of how S3 works. Not sure what's going on, we'll have to debug it further.

**Comment by apinkney0696** [comment]
For debugging purposes, here's a rundown of some example of things going on in the S3 bucket:

1. "Empty folders" as seen above.

2. Files two directory levels down aren't deleted: 
![image](https://user-images.githubusercontent.com/78036563/122819711-c9fbe780-d2a8-11eb-9965-205adf00d02d.png)
 
3. Files that aren't image formats aren't deleted:
![image](https://user-images.githubusercontent.com/78036563/122819852-f6afff00-d2a8-11eb-88df-04c6b6deeb6b.png)
 
4. No reason that I can find why they are still in S3... 80 days and counting :( 
![image](https://user-images.githubusercontent.com/78036563/122820207-5d351d00-d2a9-11eb-97fe-d12a2ecf34a3.png)

I also just wanted to clarify for myself that there is a difference between uploading files into S3 and ingesting from S3 to the DC record, right? So per this request, files _uploaded_ into S3 that have not been _ingested_ into the DC within 24 hours will stay in the bucket? Eddie's comment:
> Good catch. In other words, remove all files and folders after 24 hours.
made me second guess, and I wanted to make sure I was asking for something doable/had my terminology correct.

**Comment by jrochkind** [comment]
Thanks! 

I am not assuming the reason they are not being deleted is because they are two directory levels down, or non-image formats. That may just be coincidental. 

Yes, you are correct about the difference between uploading files into S3 and ingesting from S3 to DC. I understand that you are asking for files to be deleted 24 hours after ingest, not 24 hours after uploading to S3. It's @eddierubeiz who was confused there! 

We changed our implementation to be able to handle deleting X days *after ingest* (instead of after upload) around March 16 2021, at #1019

At the point we did that -- some files may have been "leftover" and trapped in a state where they will never get deleted. If they had already been ingested before March 16, they would never be deleted by our new logic, and then we turned off old logic, which would also never delete them. 

So it might make sense to actually delete the entire bucket contents (or entire contents except for a few specified dirs you still need), and start over from scratch, and see if the problem occurs again. 

I am still a bit suspicious of those empty directories, they may be a different issue. We may have more than one issue going on. I want to investigate a bit more when I have a chance -- but it may make sense to just delete the bucket and start fresh after all, if that can work for y'all @apinkney0696

**Comment by apinkney0696** [comment]
That works for us! If you are able to keep the directories "2005.070.001_01_07", "2019.011 Bredig Box 2 Folder 29", and "2019.011 Bredig Box 2 Folder 30" that would be great, but if not we can re-upload. Thanks so much!

**Comment by eddierubeiz** [comment]
Took a look to double-check, and there are indeed a number of empty folders:
```
2005.070.001_01_01
2005.070.001_01_02
2005.070.001_01_03
2005.070.001_01_04
2005.070.001_01_05a
2005.070.001_01_05b
2019.011.b1f1.002
2019.011.b1f1.003
2019.011.b1f2.001
2019.011.b1f2.002
Brent_Roger
Stryer_Lubert
b1036375 Explanation of Terms/CaptureOne
```

**Comment by jrochkind** [comment]
So there might be a number of different problems going on at once. :) 

One is that our system doesn't seem to be escaping spaces/punctuation the same as AWS API. For a test object annabel created, there's an object with key `2003.020.154 Atoms for Peace/2003.020.154_001.tif`. 

Our system is doing:

    bucket.object("2003.020.154%20Atoms%20for%20Peace/2003.020.154_001.tif").exists?
    # => false

How does amazon actually want it? Let's see....
  
    bucket.object("2003.020.154 Atoms for Peace/2003.020.154_001.tif").exists?
    #=> true

OK, the AWS API doesn't want it escaped at all. Our system is storing it in the DB as a "path to delete" escaped as `"2003.020.154%20Atoms%20for%20Peace/2003.020.154_001.tif"`. 

So that's the first thing to fix. I think there may be multiple problems going on at once!

**Comment by jrochkind** [comment]
OK, after fixing that (will PR shortly), I WAS able to reproduce. 

A folder that Annabel dragged to the S3 ingest location, I deleted both items in it... the "folder" item was still left behind! 

This is a weird thing for S3 to do. Ironically, the docs for actually claim it is *unable* to do this even if you want it to! 

> Empty folders and Amazon S3, Azure, Backblaze B2, OpenStack and Google Storage
> ...
> Some services give the impression, via their web interface, that you can create folders, but what they actually do is create empty objects to make it appear there is a folder.
>
> Because of this some options in SyncBackPro are not available when using these cloud systems. For example, you cannot create empty directories.
https://www.2brightsparks.com/syncback/help/cloud.htm

Yeah, that matches my understanding too! But here we have SyncBackPro appearing to create these empty when we don't want it to, even though their docs say they are unable to even when people do want it to!

I am continuing to investigate to understand the nature of this 'empty directory' on S3.

**Comment by jrochkind** [comment]
Indeed for the "empty directory" `2003.020.154 Atoms for Peace`, there is a zero-byte file on S3 with the name `2003.020.154 Atoms for Peace/` (note trailing slash in the name). Very weird. I can only think that SyncBackPro is creating this, although I want to do another test tomorrow. 

I think perhaps the cleanup script should just delete all "empty directory" files (zero-byte files ending in slashing) -- it doesn't even matter if the "directory" is "empty" or not, we don't need these placeholders, there is no reason we need zero-byte files ending in slash in the repo.

**Comment by jrochkind** [comment]
> The Amazon S3 console treats all objects that have a forward slash ("/") character as the last (trailing) character in the key name as a folder, for example examplekeyname/. You can't upload an object that has a key name with a trailing "/" character using the Amazon S3 console. However, you can upload objects that are named with a trailing "/" with the Amazon S3 API by using the AWS CLI, AWS SDKs, or REST API.

> An object that is named with a trailing "/" appears as a folder in the Amazon S3 console. The Amazon S3 console does not display the content and metadata for such an object. When you use the console to copy an object named with a trailing "/", a new folder is created in the destination location, but the object's data and metadata are not copied.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html

Apparently SyncBackPro is creating such.

**Comment by jrochkind** [comment]
OK, it looks like copying a folder with SyncBackPro DOES create that "placeholder" directory object -- an S3 key whose contents are 0 bytes, and whose name is the folder name, including a trailing `"/"`. 

These placeholder directory objects are what makes the directory stay around when it's empty. But actually they aren't necessary at all, even when teh directory is *not* empty, we can still delete the placeholder object, they aren't needed for anything. 

So I will fix the nightly maintenance task to do a scan of all ingest bucket contents, and just delete any thing whose key ends in `/` and whose contents are 0 bytes. It'll just do that every night, after it deletes ready-to-be-deleted objects. 

Will also change expiration time to 24 hours.

**Comment by jrochkind** [comment]
Deleting ALL current contents of scihist-digicoll-production-ingest-mount as of now, per instructions from annabel.
