### ISSUE TITLE
Convert sets of records into child records

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1303]
Eddie ran a list for me of all the records that use the Source field in the digital collection last week. (#1281)

As I suspected, these were all records created in the early days of the Digital Collections when the parent-child hierarchy capability didn't exist. I would like to convert these into child records under a new parent for each book, then remove any data in the source field. I can do this manually on my end, but it might take me a while and I wanted to see if it could be an easily automated process from the back-end. 

I have already created the new parent works and grouped the records that will become the children in this spreadsheet: 
[Source_Field_Project.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/7105919/Source_Field_Project.xlsx)

I would ultimately like to remove the source field from the metadata form, but I can make another ticket when we're ready for that.

**Comment by jrochkind** [comment]
I just want to note:

I remember when we *added* the "Source" field, and the parent/child hieararchy capability *definitely* already existed. 

Repository managers at that time just chose not to use it for these records for whatever reason -- I remember they specifically asked for the "Source" field *because* they didn't want to put a parent record in, they only wanted to put in isolated page(s) -- maybe they were only going to have one page and wanted to avoid having a parent with a single child?  I'm not sure their motivation. 

It's totally fine for the approach to change of course, I have no problems with it. (Will we actually eliminate the 'source' field afterwards?).  I just wanted to include my memory of the history of it.

**Comment by apinkney0696** [comment]
That's really great to know, Jonathan!! Thank you.

I was told by Hillary when I asked her about it several months ago that the reason why they used source rather than a parent work was because the parent-child thing wasn't in place yet, so that's where I was pulling that statement! I'm glad to know otherwise! There are a lot of partially digitized books in the collection which use the parent-child system and use the description field to describe how much of the work is digitized. There are only 14 books here that don't use that system. My gut tells me that it's okay to go forward with this ticket in order to make how we treat partially digitized works consistent within the collection, but I will chat with Gabriela about it again this afternoon to get a second opinion now that I know the initial use of the source field was intentional.

**Comment by apinkney0696** [comment]
@eddierubeiz, here is the updated spreadsheet [Source_Field_Project.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/7106673/Source_Field_Project.xlsx) with the record IDs. I'm leaving out the "Catalog K" info because there seem to be both [individual records](https://digital.sciencehistory.org/works/37720c74n) and a [full digitization](https://digital.sciencehistory.org/works/vt150k323) in the DC right now, so I think I'll go in and manually deal with that one.

**Comment by eddierubeiz** [comment]
Looks great. Thanks very much!
