### ISSUE TITLE
Brainstorming: Refresh Collections Landing Pages

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1358]
Ideas so far to implement:
- Make the thumbnail/feature image more prominent
- If the collection's digitization was funded, add a location for crediting the digitization funding organization and maybe their logo.
- Add beveling and shadowing effects to make text and graphics pop

Inspiration:
https://curiosity.lib.harvard.edu/contagion?utm_source=library.harvard
https://digital.librarycompany.org/islandora/object/Islandora%3AKOLL1
https://digital.hagley.org/islandora/object/islandora:2460207

Some prototypes:
Option 1)
![Collections_Page_Refresh_Option_1-01](https://user-images.githubusercontent.com/78036563/136569839-1e25fcbc-b99c-4fc0-bd02-37e8eb26e606.jpg)
Option 2)
![Collections_Page_Refresh_Option_3-01](https://user-images.githubusercontent.com/78036563/136569845-f1df49b8-de78-4dfd-8e32-b6fb4b0289f3.jpg)
Option 3)
![Collections_Page_Refresh_Option_2-01](https://user-images.githubusercontent.com/78036563/136569842-14476bb2-5aa1-4827-87db-beedd939083c.jpg)

**Comment by jrochkind** [comment]
If we want bigger images, we might need to re-upload the images again. At present we only have images at a fairly small resolution, that won't look right when blown up. This could be a lot of work for our many collections, that we should be sure to budget. 

I am also curious if we have any numbers on how often people acutally view the collection pages. i think they are *not* very highly viewed.  Which is part of why we spent only a modest amount of time on them, I think.  If we want people to view collection pages more, we might need to redesign our home page and/or link to collection pages from more places on institute web site.  Otherwise... does it make sense to spend a lot of time on redesigning pages that are not viewed very often?

Another thing to keep in mind with redesigns is that we make sure all our pages work well on small-screen such as mobile devices, so some of these two-column layouts need to have one-column alternatives as well. One reason the collection page looks how it does currently is because it's simpler to make a layout on large screens which is the _same_ as on small screens; but we can do the more work to have it slightly different on large screens if we want. 

It might be good to be explicit about what the goals are here. Just kind of aesthetics, making it look "better", more attractive?  (Rather than, say... dealing with a UX problem where people are having trouble getting what they need out of the page? But some of that seems to be involved here too, you seem to be suggesting that people need a way to "explore other collections" that they don't have, etc?).  That's fine it's just make it look "better", but we could maybe list some adjectives/qualities of what "better" means to us. More "professional"? "Fun"? Excite people as to the content? other?  And/or list some things we don't like about the current page -- why does it seem in need of a "refresh"?  Or if there are things we think people are having trouble doing that we want them to be able to do, list those explicitly too. Just be explicit about our design goals here in some way.

**Comment by jrochkind** [comment]
Oh, and in addition to resolution maybe needing to be bigger -- in the mock-ups with a "banner" image it's of course a differnt aspect ratio -- we could have the software just kind of arbitrarily cut up a square image to put it in a banner, but we might not like the results -- so we might need to upload manually edited images that are "banner" sized ratio like that?

That might mean we need *two* images attached to a collection, as we still need a square one for the thumbnail on the search results page, I think?

**Comment by apinkney0696** [comment]
Finished.
