### ISSUE TITLE
Digital Collections Homepage Changes

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1361]
Some ideas are:
- Priority: Removing the link to "the rest of our collections" which goes to the Institute's collections, not the digital collections. This has been reported as confusing by several folks in the Institute.
- Priority: Making the link to the Digital Collections' Collections more prominent and replacing the "Featured Collection" and Beckman Image (finally!)
- Adding bevel and shadow effects to graphic elements
- Make the Homepage photo link to its record

Inspiration:
https://digitalcollections.nypl.org/
https://library.harvard.edu/digital-collections
https://www.si.edu/collections
https://digital.hagley.org/

Prototype:
Recently added images taken from a screenshot of the Smithsonian website. Ours would be our own collection images. 
This prototype includes a lot of aesthetic changes, but we can make it simpler.

![HOMEPAGE-1](https://user-images.githubusercontent.com/78036563/136584220-6fd36d98-7fbf-42ba-a93d-a8580eeeb80b.jpg)

**Comment by jrochkind** [comment]
OK, we decide to do some initial change, as per @apinkney0696's last comment. We can split into three parts, one for each "ribbon".  Different people could be working on different parts. 

Not sure how to organize this in Github at this point...

* Recently added -- only show four of them, but with more normal spacing, centered on a center-line, allow to get bigger than square (but not too big). 

* Featured topics, only show 4, with "View all topics" and a sentence about them (need sentenace from @apinkney0696 )

* Collections -- get rid of featured beckman collection, move to more like 'featured topics'.. but with one each from each department? Still? May need to discuss this one more with @apinkney0696

**Comment by apinkney0696** [comment]
I created four images for the collections ribbon. they are each the same width in pixels as the icons on the collections page so you should be able to fit all four across the screen. I wasn't sure if I should include the title across the bottom, but I used the font and colors according to the branding guidelines. I can redo if needed.

There are .tif versions available on P:\Othmer Library\Digital Collections - Internal Access\Homepage images

![Archives-1](https://user-images.githubusercontent.com/78036563/140556805-6895b3d3-e405-4c97-aed3-8e74beaa5c6f.jpg)
![OralHistory-1](https://user-images.githubusercontent.com/78036563/140556801-fd71e013-8535-422c-846f-d88c9d765cc1.jpg)
![Library-1](https://user-images.githubusercontent.com/78036563/140556802-8c080933-df1d-48b6-809d-d28887c9edbf.jpg)
![Museum-1](https://user-images.githubusercontent.com/78036563/140556803-97f756e6-70e9-4a1e-9754-da048cc2e381.jpg)

I also emailed Michelle to get final approval on the Featured Topics ribbon so I'll give the green light on that part soon.

**Comment by jrochkind** [comment]
Hi @apinkney0696 , yes we need it without the words or green stripe please. We place the words as text, not part of the image, for accessibility and SEO among other things. 

On my size laptop screen, it only fits three images at that size, on the  "collections list" page for instance. 

But we can make it wrap 2x2 instead of 3x1 when it wraps, which I think is a bit cleaner. 

You really want a "library" and "oral history" icon that both just link to the collections list page filtered to have only *one* collection?  In the case of oral histories, I feel like might as well just link to the oral history collection itself. In the case of the one library collection... I'm not sure. 

Note that oral history is also currently up in "featured topics", so would currently have two placements on the page.

**Comment by jrochkind** [comment]
@apinkney0696 Also just to make sure we are on the same page:

* The collection thumbs are 266x266 px squares
* If we style then just like the collection thumbs, while the images are square, the bottom portion will be *covered* by the text ribbon -- but we still need the 266x266 square, that's just how we laid it out. 
* If you have big enough images doing this double-resolution at 532x532 would not hurt -- that way we can provide high-res images for high-res screens. Although our current collection thumb images mostly don't do that, so either way.

**Comment by jrochkind** [comment]
(we could also go ahead and create a new issue for the "collection" ribbon specifically maybe, as we discussed?)

**Comment by apinkney0696** [comment]
Okay, no problem. I'll remove the words from the picture and put those in the folder on P: sometime today.

On your laptop do you also only see 3 across on the [collections](https://digital.sciencehistory.org/collections) page? I like the idea of it being a 2x2 wrap when the window is too small, let's do that.

"Library" will be the only category that does not have more than one collection. Oral history will have all of the projects plus the overall OH collection (I know last time we talked we were on the fence about making projects into collections, but I chatted more with Gabriela about this, and we eventually decided it would be a good idea). The oral history topic will probably move into the 'View all Topics' page and so it won't be on the homepage anymore. I'm working on a descriptive sentence to describe what our collections are. Stay tuned.

Michelle cleared having only four "Featured Topics" on the homepage and the rest available elsewhere. The four that will stay on the homepage are Water, Alchemy, Health & Medicine, and Women & Science. These should also sit four across or 2x2 wrapped - do I need to edit their icon images or are you able to resize them on the back end?

Yes, let's make two new tickets, one for the collections ribbon and one for the featured topics ribbon. It's getting a bit confusing talking about everything at once here.

**Comment by apinkney0696** [comment]
> The collection thumbs are 266x266 px squares
> If we style then just like the collection thumbs, while the images are square, the bottom portion will be covered by the text ribbon -- but we still need the 266x266 square, that's just how we laid it out.

Does it have to be square? I used the 266 px width for the above icons, but obviously their rectangular with a longer height

**Comment by jrochkind** [comment]
Yes, on my laptop the collections list page is only 3 across. 

Oh right, I notice now you actually didn't make these images square, you decided to leave the square format used elsewhere on the site for the collections area? That's fine too. 

For the "featured topics" -- are you saying the current images we are using for featured items are not sufficient, you want different ones? Since you are asking about creating new ones? I thought we'd just be using the same ones, I'm not following, let's talk about it at the meeting. 

Also I'm thinking we should remove "Oral History" from "featured topics", since it'll be below under "collections" too?

**Comment by apinkney0696** [comment]
Updated Collections ribbon images are located here: P: /Othmer Library/ Digital Collections - Internal Access / Homepage images/ Final Images
