### ISSUE TITLE
Add validation on blacklight_range_limit date fields

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1378]
- Start at https://staging-digital.sciencehistory.org/catalog
- Click "Date" under "Limit your search"
- Type `..//etc/passwd` into one of the date fields and run the search.
Leads to a 500 error.
Note that the equivalent fields on the home page do have front-end validation.

**Comment by jrochkind** [comment]
Front-end validation doesn't stop a bot from sending the URL of course. 

Another one of these "bad input causes an error" bugs that seem to keep cropping up forever! Last time I tried going over params with an "allow-list only what's a GOOD param" approach (instead of "specifically deny-list specific known patterns of bad"), hoping it would just get everything, but apparently not everything yet!

Obviously they are trying to find a security vulnerabilty of some kind, which they didn't actually find, not a security issue.

**Comment by jrochkind** [comment]
Wait a second @eddierubeiz , I already am getting the front-end validation even on /catalog!

Which makes sense, cause it's the exact same template on front-end as well as catalog, they have to be the same!

What browser are you using?

![Screen Shot 2021-10-14 at 9 38 26 AM](https://user-images.githubusercontent.com/149304/137328830-82b09bc3-3f6c-4e60-8663-9952455bdf8c.png)

**Comment by jrochkind** [comment]
Oh WAIT, Date under "limit your search"!!!

OK, that's coming from blacklight_range_limit. It's hard for us to fix, we might need to PR to blacklight_range_limit... where it might not be generically appropriate...not sure.
