### ISSUE TITLE
Refine results by availability of transcription and/or translation

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1400]
Putting this here for us to talk through and think more about since there seems to be potential interest from staff.

**Comment by jrochkind** [comment]
On the other hand, Distillations staff who wants it doesn't have access to the staff interface. :(

**Comment by jrochkind** [comment]
we do have the ability to add facet to "main search" that is only seen by staff -- that's what we do with the "Medium" facet. 

But again Distillations doesn't have login to see "staff-only" stuff. And if they had one, they'd be able to edit our metadata and such, which we don't want. 

We may need/want another level of "staff" permissions, but that's a somewhat bigger lift too, to create another kind of "staff" role. hmm.

**Comment by apinkney0696** [comment]
Hmm, you bring up some really good points. How much time would it take for you and Eddie to make this a searchable facet? If it's a really small project, it could be worth it even if we end up changing or taking it down later.

**Comment by jrochkind** [comment]
I'm not certain if I know what you mean by "make this a searchable facet". 

If you want us to add something involving presence of transcription/translation to the general facet list for all searches in Digital Collections, that's very easy, a couple hours of work. 

We'd have to decide what you want it to look like,  what the facet is called, what values it holds, corresponding to what. 

I worry that doing this would make our already-overwhelming facet list even worse for users, with a facet that's not particularly useful for most users in most uses of digital collections.  As you originally said "it will only ultimately apply to a small part of the Digital Collections content as a whole, so we may not want this to be a facet on our main search results page."  

So I personally want to push against doing it this "easy" way, I think it's going to confuse users.  (Although one could also argue that our "facets" area is already so confusing that nobody can use it anyway, so it doesn't matter if we make it more confusing. :( )

**Comment by apinkney0696** [comment]
Ah, shoot. Still just brainstorming as well. Entrusting staff with accounts on Production could be the way to go. 

> Or we can work on creating a new kind of "staff" account that doesn't actually have management permissions... Not totally sure how much work that would be.

^ I wonder if that is something we might use again in the future? Hmm. If it's a lot of work and only a temporary fix for this situation it may not be worth it. If it's fairly simple, then I think it could be a great solution.

**Comment by apinkney0696** [comment]
Okay, a new idea that I think might work for this: make "Translated Work" a genre heading, or add "Translations" as a subject heading to translated works. We'll just need to add whichever we chose to any record that already has a translation. Then I can tell Jocelyn to add it to newly translated records as she finishes them. Thoughts on that option?

**Comment by jrochkind** [comment]
So, as far as metadata, if we want it to show up that way in subject or title facet, we can add that in the indexing with no need for any difference in metadata entry, we can just tell the indexing routing "Add a value 'Translated Works' to "subject" facet if it has any translations attached", using logic, not requiring you to actually go add them all and introduce possibility for mistake (accidentally adding that to works without tranlsations or vice versa). 

But, does that actually make sense as a genre or subject?  (changing genre/subject of course effects end-users not just staff). 

UX issues:

As a genre, it will show up above the title on all screens. Which I don't love adding to that, that design was really intended for just one or two. 

As a subject -- I"m not sure there's an easy way to actually use it as a limit, since there are so many subjects!

If we were actually designing this for the end-user, I'd start with -- what do we actually want the UX to look like? Do we *want* it to be a subject/genre? Or what do we want it to look like? Then we can see about how to implement it, I guess.  this would take some time though, not be a quick fix for staff. 

If we're just trying to do this the quickeset way possible that won't effect end-users, I'd  consider just add it as a staff-only-visible facet, give them staff accounts, and ask them not to change anything? 

The software can only do what the software can do!
