### ISSUE TITLE
Create Collection-level metadata field for identifying collecting department

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1409]
Four choices: Center for Oral History, Museum, Library, and Archives
Required field

**Comment by jrochkind** [comment]
We probably don't want to make it a required field until we have the data entered, so do it a few steps:

1. add field
2. metadata entry has to happen
3. go back and make it required once they all have it filled out

Unless we're going to start with a spreadsheet listing how it should be assigned for each one, instead of assigning them in web UX.
