### ISSUE TITLE
Adding Funder's Logo to Oral History Records

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1427]
Sarah Schneider got in touch with me with some requests for the NHPRC project. This one needs a little consideration, so I am putting it in now for discussion. Here is her request:

> "On each person’s Digital Collections page for those whose oral histories are part of the NHPRC grant, we would like to have the NHPRC logo on their page, to designate that they’re part of the project and that we received funding from the NHPRC. This should be done when our OHMS for each individual goes live."

This is touching on our perennial issue of having too much going on our record pages. I was thinking about how I had been pitching adding funder's logos to collections landing pages, so I wonder if they would be opposed to making this a Collection and putting the logo there, rather than us finding a place for a logo on each record. Would love to hear y'all's reaction to this request and ideas you may have about logos on our pages.

**Comment by jrochkind** [comment]
Cool!

Maybe we want to generalize our "digitization sponsor" field to like a "sponsor field", that has a list of sponsor types ("digitization", I don't know what the others are), a name, and an optional link and even possibly logo if we want. (logo takes us building a bit more infrastructure, possibly). 

Or something simpler. We can do whatever is needed one way or another on the technical side. Glad we have flexibility on the page layout/design side!

**Comment by jrochkind** [comment]
Cool. That "sponsor" field continues to rub me the wrong way -- it to me doesn't seem to match the other creator fields, and seems to be more administrative than intellectual metadata, about the work as it was processed by us, not about the work independent from us as a host like all the other fields.

**Comment by apinkney0696** [comment]
I am inclined to agree. Because Oral History funding is not exactly a Digitization Funder, I don't love using that field either. What if in the Additional Credit field we added another dropdown option that said: "Sponsored by"?  That would move it down the page with more of the admin metadata. Just brainstorming.

**Comment by jrochkind** [comment]
So it's actually pretty easy for us to add additional fields and/or drop-down options. 

So we *could* add that additional option to "additional credits." But if you're just doing that because it's already there and it doesn't really fit best there, we can also do literally whatever makes sense. I think right now "additinoal credit" is all in-house staff involved in the production of the records, photograph, translation, etc. Maybe we want to keep it for that?

We can add another field. We can put this wherever you want. We could take some existing field and change/generalize it (maybe generalize "digitization funder" to like "funder/sponsor", with a drop-down for what type of funder?).  

You don't have to try to shoehorn it into somethign that's there, it's not hard for us to add another field, we can do it however you think it's best modelled!
