### ISSUE TITLE
Install or fix font-awesome icons.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#143]
TODO: `<i class=\"fa fa-external-link\" aria-hidden=\"true\"></i>`, as used in turning bare URLS into links, is not showing up properly on the front end. Might be something I'm doing wrong.

See description_display_formatter.rb for more details.

**Comment by jrochkind** [comment]
Nothing your doing wrong, font-awesome is just not installed yet.

I do think we will keep using font-awesome in new app. 

We need to decide if we want Font-Awesome 4 (which chf_sufia uses), or the newer font-awesome 5. The newer v5 has some icons available only in paid "pro" -- but I _think_ all the v4 icons are still available in the free one. v5 has somewhat changed class-name api, that allows more variants of icons (outlines vs solid etc), although some are only available in "pro". 

v5 also allows you to choose to use a javascript-based implementation that uses svg, instead of the pure-CSS using an icon font. I'm not totally sure which we'd want, we need to decide. Some suggest there are accessibility advantages to the JS/svg implementation. 

And we need to figure out how to actually include it in our Rails app, which may depend on if we use the JS implementation (and then figure out how to fight with webpacker or find a gem packaging it for sprockets etc). 

So there's "choices". Or we could make the choice to just keep using v4 exactly how chf_sufia does, to avoid the additional choices (and additonal features, including possibly accessibility advantages).

**Comment by jrochkind** [comment]
They are installed, not sure when we did it but we neglected to close this ticket then. 

We decided to just keep using font-awesome 4, just the way we were in chf_sufia, rather than font-awesome 5.
