### ISSUE TITLE
ffmpeg not present on Heroku

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1448]
```
Running bash on ⬢ scihist-digicoll-production... up, run.2317 (Standard-1X)
~ $ ffmpeg
bash: ffmpeg: command not found
```

**Comment by jrochkind** [comment]
Once fixed, the list of combined derivatives that someone tried to create but failed can be found from: https://app.honeybadger.io/projects/58989/faults/82479368

(Have to tranlsate from UUID pk found in `params` section to friendlier_id/work.)

**Comment by jrochkind** [comment]
I can't remember where ffmpeg is even supposed to be coming from. It doesn't seem to be an included custom heroku bulkdpack nor is it listed in our `Aptfile`... where did we used to get it from then?

**Comment by jrochkind** [comment]
https://github.com/sciencehistory/scihist_digicoll/commit/b91379d7f63a





Looks like at least in Nov 2020 we meant to have ffmpeg as a buildpack…  but which one and what happened to it?

**Comment by jrochkind** [comment]
Eddie found #919, suggesting we needed another buildpack for ffmpeg... wonder what happened to it.

**Comment by eddierubeiz** [comment]
`heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview` does restore `ffmpeg` in staging.

**Comment by jrochkind** [comment]
Confirmed could create a "combined derivative" on staging after that fix. 

I am going to update docs on our wiki page here, listing buildpacks: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1915748368/Heroku+Operational+Components+Overview

To mention this one.

**Comment by jrochkind** [comment]
@eddierubeiz oh hey interesting!  The heroku docs for the activestorage-preview buildpack imply that it should add poppler too! Poppler being 

https://devcenter.heroku.com/articles/active-storage-on-heroku

Remember when we had to mess with poppler/poppler-utils after deploy, things weren't there that we expected there? I wonder if that problem was also caused by activeestorage-preview getting lost in the wash! 

At d61eb69bd

**Comment by jrochkind** [comment]
OK, as of now there are three errors in honeybadger, actually only mentioning two UUID PKs. 

* 5f537256-a7a3-494a-bf93-c6ee3c36c6c7 => https://digital.sciencehistory.org/admin/works/pg15bf97z
* 2b9c5904-4deb-4b12-a0ea-ecc6e65a7254 => https://digital.sciencehistory.org/admin/works/ptm8797

(we should make the UUID pk visible and searchable in admin interface, since sometimes that's what we get from errors and other logs! I had to login to console and look these up)

**Comment by jrochkind** [comment]
Buildpack added in production, those two derivs re-generated.
