### ISSUE TITLE
Export metadata in .csv format for patron

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1449]
A representative from the Newman Numismatic Portal at Washington University in St. Louis, the funder of the Booth papers digitization, has requested an export of the metadata for [334 items](https://digital.sciencehistory.org/collections/kk91fk97p?q=mint&sort). 

They would like the data compiled in one .csv format document and they have no hard deadline to receive the data.

Please export to P:\Special Collections\External Access\Newman Numismatic Portal so I can share directly with the patron.

Let me know if you need any other information from them, I'm happy to ask!

**Comment by jrochkind** [comment]
I am not sure how to put "the metadata" in a CSV file. 

We have a LOT of metadata, and much of it is structured/complex/nested in format, that doesn't obviously map to a CSV file.  Figuring out how to "flatten" it into CSV is non-trivial. 

It's also not necessarily entirely clear what attributes are part of 'the metadata' or not. Does this include *all* the "adminsitrative" metadata we have, for instance?  Does it include asset-level metadata (administrative or not), or just work-level?  

Someone is going to need to specify what this CSV file format of our metadata looks like. I'm not sure who that is. 

Do we think they actually plan to use this for something, or they just want it to say they have it?  Like how much thought or communication with them should we put into it?

It would be somewhat easier to give them a whole bunch of .json files than it would be to give them one CSV file. 

But if they actually plan to use this data for something, we probably need to hear from them for what and what they want in the CSV file specifically.

**Comment by apinkney0696** [comment]
I figured I might need to get some more info from them. Just wanted to put the request in to figure out what other info I needed from them, thanks for the prompt response!

> Do we think they actually plan to use this for something or do they just want it to say they have it? Like how much thought or communication with them should we put into it?

In their original email, they ask "Is there any possible way to do an export of metadata for these items? Opposed to individually looking at each time." I'm not sure what that means they would like to do with it, something I can ask about.

I'm assuming they only want the work-level descriptive metadata, but again, I will ask to get more details. Is a CSV possible, or is there another format I could recommend that would be more convenient for you? I think they want to be able to see everything at once, so I doubt they would like a whole bunch of .json files.

**Comment by jrochkind** [comment]
I don't really know how to answer if a CSV is possible. 

If they tell me exactly what columns they want in a CSV and what the data in those CSV files is, I can create a CSV to those specs. 

Our data for a Work doesn't always "obviously" map to a flat list of individual values though.  For one obvious example, let's say if they wanted  individual asset filenames or sizes. A given work might have 1 asset, or 2, or 10. How do you map the filenames and sizes of multiple children to a single line for a "Work" in a CSV?  You can come up with various schemes if you want, whether they'll be workable or not I don't know. 

Or, just staying within Work metadata, for instance, we model "inscriptions" as a "location" and "text". There can be 0 to multiple inscriptions, each of which has a "location" and a "text".  How do you map this to CSV? Again, i could come up with some hacky way, but there isn't just one true way.  I don't know if any of their 334 items contains an inscription or not. This is just another example -- much of our metadata is structured like this, rather than one single flat list of labels and values. 

Or even subjects -- a work can have many subjects, do you just put them all in a single CSV value, seperated by... maybe not a comma, that gets confusing, because CSV already uses commas to separate values!  By semi-colons? And you count on no subject ever containing a semi-colon itself?  I think that's a safe assumption in the case of FAST/LCSH. 

This is just a list of examples. In general, determining "how do I represent this all in a CSV" is a non-trivial task, that could take, oh a week or two, to try to go through and get "all" the metadata, and if we just try to come up with something we think is "reasonable" it might not be workable for them, and they might come back asking for something else -- this could become a very large and never-ending project. 

If instead they can tell us "We just want title, creators, subjects, and a URL to the work and here is how you represent multiple creators and subjects in a CSV", that's much easier. 

I am not aware of any other format to suggest that would let them see "everything at once" though. 

In general, in the future, if we get grants where they are going to want things like this, it would be good to know that up front and get specifications on exactly what they want, so we can estimate how much it will "cost" us to produce the reporting they want too, if it's something complex.  "Turn ALL of your metadata into a usable CSV" is in fact something complex!

**Comment by jrochkind** [comment]
Thinking about any formats we already have... we have OAI-PMH "oai-dc" format already available for the OAI-PMH export used by PA Digital/DPLA. 

We could give them a single XML file with "the metadata" for those identified works, in OAI-DC format. That would be fairly easy since we already have the metadata available. 

It does "lose" some metadata, when we "translate" to OAI-DC, it doesn't really have "everything". 

Can they look at "everythign at once" from a giant XML file of OAI-DC records? I don't really know!  I guess it depends on what tools they have? There isn't really any way for a human to literally look at dozens of metadata values for 400 records "at once" of course!

**Comment by jrochkind** [comment]
Or if there's some other "standard" format they might wnat, it might still take us a few weeks to create it, but at least it would be re-usable if someone else needs metadata in the same standard format! 

But there's no "standard" I can think of that can fit structured metadata like this into a CSV, the "standards" end up being more like the "bunch of different JSON" files (say with Dublin Core in them), or a crazy RDF file that is not easy for anyone to use at all!

**Comment by apinkney0696** [comment]
I see the complications. Thanks for this. I'm a little sad they want to access the data outside of the Digital Collections when I spent so long putting it in. I wonder if they know about the finding aid.

Regardless, it sounds like I need a little more info from them.

I'll try to find out what their goals are for using the data. Perhaps they would be happy with something rough and ready like a bunch of json files and they can do the data manipulation themselves. And I'll see what metadata fields they are hoping for. Is there anything else I should ask?

**Comment by jrochkind** [comment]
I guess that's it?

Let me get an example of what the already existing (and standardized in library communities) OAI-DC export looks like, so you can show that to them....

Basically XML blocks like this, that could all be in one file or whatever.  You can see it is definitely only a limited subset of our metadata. it is what we share with DPLA. 

```
<record>
	<header>
		<identifier>oai:sciencehistory.org:000000018</identifier>
		<datestamp>2019-06-25T13:17:14Z</datestamp>
	</header>
	<metadata>
		<oai_dc:dc
			xmlns:dpla="http://dp.la/about/map/"
			xmlns:cnt="http://www.w3.org/2011/content#"
			xmlns:dc="http://purl.org/dc/elements/1.1/"
			xmlns:dcterms="http://purl.org/dc/terms/"
			xmlns:dcmitype="http://purl.org/dc/dcmitype/"
			xmlns:edm="http://www.europeana.eu/schemas/edm/"
			xmlns:gn="http://www.geonames.org/ontology#"
			xmlns:oa="http://www.w3.org/ns/oa#"
			xmlns:ore="http://www.openarchives.org/ore/terms/"
			xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
			xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
			xmlns:skos="http://www.w3.org/2004/02/skos/core#"
			xmlns:svcs="http://rdfs.org/sioc/services"
			xmlns:wgs84="http://www.w3.org/2003/01/geo/wgs84_pos#"
			xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/">
			<dc:identifier>https://digital.sciencehistory.org/works/000000018</dc:identifier>
			<dc:title>Adding molten glass to neck of carboy to make rim</dc:title>
			<dc:rights>http://creativecommons.org/publicdomain/mark/1.0/</dc:rights>
			<dc:date>After 1895</dc:date>
			<dc:description>View of a worker adding molten glass to the neck of a carboy, a type of vessel used for the transportation and fermentation of liquids, at a Glass Works factory in New Jersey. This photograph is one of a set of six stereographs detailing the production of 12-gallon glass carboys.</dc:description>
			<dc:publisher>Underwood & Underwood</dc:publisher>
			<dcterms:rightsholder>http://creativecommons.org/publicdomain/mark/1.0/</dcterms:rightsholder>
			<dc:subject>Employees</dc:subject>
			<dc:subject>Glass blowing and working</dc:subject>
			<dc:subject>Manufacturing industries</dc:subject>
			<dc:subject>Glass manufacture</dc:subject>
			<dc:type>image</dc:type>
			<dc:type>photographs</dc:type>
			<dc:type>stereographs</dc:type>
			<edm:preview>https://digital.sciencehistory.org/downloads/41687h66b/thumb_large_2X?disposition=inline</edm:preview>
			<dpla:originalRecord>https://digital.sciencehistory.org/works/000000018</dpla:originalRecord>
			<edm:rights>http://creativecommons.org/publicdomain/mark/1.0/</edm:rights>
			<edm:hasType>photographs</edm:hasType>
			<edm:hasType>stereographs</edm:hasType>
			<edm:object>https://digital.sciencehistory.org/downloads/41687h66b/download_full?disposition=inline</edm:object>
		</oai_dc:dc>
	</metadata>
</record>
```

**Comment by apinkney0696** [comment]
Okay, so I sent them a long email talking through everything, and I received this reply:

> Would it be possible to get the following fields in a .csv?
> 
> dc:identifier
> dc:title
> dc:date
> dc:description
> 
> Our site metadata follows a proprietary format (long story), but copy/paste should be straightforward, if we can get the above fields.

Is this something we can do? I know our Date field has some complicated attributes like 'circa' that might make a .csv complicated.  

Could you export the OAI-PMH (which includes these fields) for the records they want, then use [OpenRefine to change XML into an excel doc or CSV](https://onlinejournalismblog.com/2015/10/21/how-to-convert-xml-or-json-into-spreadsheets-using-open-refine/)? and finally just delete the data fields they don't want? I could do the OpenRefine bit if you export the XML.

Let me know what your thoughts are.

P.S. I'm also not sure if his last sentence means they are taking our metadata to put on their own site? I might mention that they credit us in some way.

**Comment by jrochkind** [comment]
@apinkney0696 that's a great answer, that's totally easy. (I don't think I'dd bother with that openrefine workflow, although that could be a way to do it; we can just create this for them, not a problem). 

What do they want in `dc:identifier`, the URL on our site? 

Yes, the dates are the one more thing I'd ask them about. Our dates can have:

Only one date OR a range of [date1] to [date2] OR "unknown".  Dates are usually just years, but sometimes can have month and/or date too. One or each date can be qualified by: `before`, `after` or `circa`.  Additonally each date can have a `decade` or `century` modifier to mean eg `1930s` or `1900s (century)`. 

So how do they want us to serialize that?  We already have an easy way to output it in a somewhat "human readable" way (eg `before 1945 to 1950`), which is what the OAI export uses. But that might not be great if they're trying to import this into a system. Or we can do something dirt simple like "ignore all that, just output ONE date without any qualifiers". Or probably something else, if they tell us what they want.

**Comment by jrochkind** [comment]
It does sound like they're going to put all our records on their site. Not my role to be concerned about that, I'll stay out of it! Our FAQ has however always said:

> Can I freely download or extract your metadata?

> We strive to make our open data freely available,

It doesn't mention anything about attribution required or requested.

**Comment by apinkney0696** [comment]
@jrochkind I got a response from the Newman folks re: the date and identifier. They would just like the "human-readable" date, i.e. how it appears in the OAI export, and yes, they would like the record URL for the identifier field.

Is that all the info you need to get the four fields: dc:identifier, dc:title, dc:date, dc:description into a spreadsheet format? Let me know! Thanks!

**Comment by jrochkind** [comment]
I think that does it, unless we run into anything else while doing it!

**Comment by jrochkind** [comment]
@apinkney0696 the set of items you need exported is really just the set of all results for a keyword search for "mint"?

OK, the first hard part is figuring out how to get this out of Solr programmatically, Blacklight doesn't make it easy!  We can figure out a way though. Actually might just write code to talk to Solr directly.

**Comment by eddierubeiz** [comment]
We can just use works that have subject heading `Mint of the United States` plus these 10, which probably should have that subject heading but don't:
- 	https://digital.sciencehistory.org/works/gfdq0pd
- 	https://digital.sciencehistory.org/works/es6o6w0
- 	https://digital.sciencehistory.org/works/o7ipnz2
- 	https://digital.sciencehistory.org/works/g7dx9a5
- 	https://digital.sciencehistory.org/works/n78s1gp
- 	https://digital.sciencehistory.org/works/g3zks4g
- 	https://digital.sciencehistory.org/works/atvlzv4
- 	https://digital.sciencehistory.org/works/bsuxl7b
- 	https://digital.sciencehistory.org/works/o4nuf9m
- 	https://digital.sciencehistory.org/works/1gyh1nl
- 	https://digital.sciencehistory.org/works/swydm1a
