### ISSUE TITLE
Possibly remove poppler-utils from the Aptfile. Not urgent.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1455]
Our Aptfile contains the following:

```
# `poppler-utils` is not installed as a dependency of libpoppler-glib8,
# and we need it for  `pdfunite`, which we use for on-demand PDF derivatives:
poppler-utils
```
Now that we have installed the `activestorage-preview` buildpack, is it possible to remove that line?

References:
- https://github.com/sciencehistory/scihist_digicoll/issues/1448#issuecomment-963609495
for Jonathan's reasoning about why we may be installing poppler twice.
- https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/2088271873/Derivative+generation+on+Heroku
for a list of tests that can be run on a heroku bash shell to ensure that we have all the tools we need to generate derivatives
- https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1915748368/Heroku+Operational+Components+Overview
for a more general list of add-ons.

**Comment by jrochkind** [comment]
No idea, easy to find out -- do it on staging, `heroku bash` in, see if you still have `pdfunite` command line. 

Since we have an explicit dependency on pdfunite, it kind of makes me want to list it separately... unless it adds significantly to "slug build" time.

**Comment by jrochkind** [comment]
If removing it works for our app, let's also see if removing it noticeably speeds up our heroku deploys or not.

**Comment by jrochkind** [comment]
OK, I've confirmed that `pdfunite` and all other tools are still present if we remove `poppler-utils` from Aptfile. 

Same version of pdfunite either way (0.86.1), and same list of pdf* related functionality installed in `vips` either way. And even confirmed on-demand PDF generation actually working without `poppler-utils` in Aptfile. 

However, I'm not sure it makes any difference in our Heroku build/deploy time or slug size. I'm not sure it saves us anything. (maybe slightly smalller slug size 238.2M vs 238.0M? not significant) It's a bit hard to compare, because there are heroku build caches involved that get invalidated when you try to compare two different Aptfiles, and time to deploy varies anyway. But nothing obvious is apparent to me. 

So I'm not sure which choice is more future-proof/less error-prone. We were including poppler-utils in the Aptfile in order to get `pdfunite` installed. It turns out `pdfunite` is already installed by the `activestorage-preview` buildpack. 

Should we:

* remove `poppler-utils` for simplicity and because it's not needed
* leave it in as an explicit dependency, because we do need `pdfunite`, and will get confused if we stop using `activestorage-preview` buildpack for some reason and don't have it that way, or if `activestorage-preview` buildpack changes it's definition to not have it, or whatever.
