### ISSUE TITLE
Investigate "memory vastly exceeded" messages from Heroku.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1470]
We suspect these are connected to combined audio derivatives. Let's try deleting and recreating one or two of these in staging and seeing if we can reproduce this problem.

**Comment by jrochkind** [comment]
OK I did a bit more investigation in logs, these may not be connected to combined derivatives after all. 

Searching for "Vastly exceeded" (or `Error R15`) in production logs, there are two instances still available in our online logs. They are both logged as `heroku/worker.1`. 

I wanted to identify the jobs that were happening when these occured. The actual jobs on the same dyno are logged as `app/worker.1` instead of `heroku/worker.1`. I had papertrail limit to `app/worker.1`, then looked at the timestamps of the errors. 

I looked for jobs that began before the out of memory error and did not seem to finish -- had `Performing` log lines, but not `Performed` log lines.  I found there were multiple simultaneous jobs that appeared to be interupted when the dyno was shut down for exceeding memory quota -- none of which were actually combined derivatives, that may have been a red herring. 

The first one at `Nov 18 16:07:16 heroku/worker.1 Error R15 (Memory quota vastly exceeded)`, there were two jobs that appeared to have been in-progress and interupted by the kill; a `CreateDziJob` and a `CreateDerivativesJob` both for the same asset:

```
Nov 18 16:06:58 app/worker.1 INFO: [ActiveJob] [CreateDziJob] [3090d322-2937-42d9-96ec-15bacd856cfd] Performing CreateDziJob (Job ID: 3090d322-2937-42d9-96ec-15bacd856cfd) from Resque(default) enqueued at 2021-11-18T21:06:50Z with arguments: #<GlobalID:0x000055b900ec2fe8 @uri=#<URI::GID gid://scihist-digicoll/Asset/414461bf-ed89-4a69-bf95-ccbc7ce24c0b>>

Nov 18 16:06:51 app/worker.1 INFO: [ActiveJob] [Kithe::CreateDerivativesJob] [039ae987-d1ef-4023-a7fc-9f961f949b3b] Performing Kithe::CreateDerivativesJob (Job ID: 039ae987-d1ef-4023-a7fc-9f961f949b3b) from Resque(default) enqueued at 2021-11-18T21:06:50Z with arguments: #<GlobalID:0x000055b900ec7728 @uri=#<URI::GID gid://scihist-digicoll/Asset/414461bf-ed89-4a69-bf95-ccbc7ce24c0b>>
```

Asset `414461bf-ed89-4a69-bf95-ccbc7ce24c0b` no longer exists in production, so can't see what it is, or check if it has DZI/derivatives now. 

The second error at `Nov 19 08:10:01 heroku/worker.1 Error R15 (Memory quota vastly exceeded)` also has two jobs that seemed to be in-progress and interupted:

```
Nov 19 08:09:21 app/worker.1 INFO: [ActiveJob] [CreateDziJob] [a05c2f3e-c960-44fa-a798-0b1a34f03fcc] Performing CreateDziJob (Job ID: a05c2f3e-c960-44fa-a798-0b1a34f03fcc) from Resque(default) enqueued at 2021-11-19T13:09:19Z with arguments: #<GlobalID:0x00005647ef3ae048 @uri=#<URI::GID gid://scihist-digicoll/Asset/03f187dd-143f-4f11-a7cd-ebc85f3568dd>>


Nov 19 08:09:17 app/worker.1 INFO: [ActiveJob] [Kithe::CreateDerivativesJob] [df46472d-729c-4040-8a37-6073b6e78096] Performing Kithe::CreateDerivativesJob (Job ID: df46472d-729c-4040-8a37-6073b6e78096) from Resque(default) enqueued at 2021-11-19T13:09:16Z with arguments: #<GlobalID:0x00005647eceacdd0 @uri=#<URI::GID gid://scihist-digicoll/Asset/8d65c2b8-4a9b-4a4b-b82e-b8f2cf05f3d8>>
```

Again it's one `CreateDziJob` and one `CreateDerivativesJob`, but this time for two different assets. However, both of them -- `03f187dd-143f-4f11-a7cd-ebc85f3568dd` and `8d65c2b8-4a9b-4a4b-b82e-b8f2cf05f3d8` are also no longer in production. 

It looks to me like it may not have been a combined derivatives job. It's possible it also wasn't just _one_ job, but that the two simultaneous jobs were necessary to use all that RAM. 

I guess we could configure the dynos to have fewer simultaneous workers -- They are currently configured for 3 simultaneous workers, we could move it down to 2. But if the right two simultaneous can still trigger it...  that would be unfortunate. 

Our workers are already `standard-2x`. Moving up to more RAM would be prohibitively expensive, if we are going to leave even one worker running to avoid startup time latency with hirefire scaling. 

I wish we had those assets involved to try to duplicate!

I'm going to do some "combined derivative" creation on staging just to be sure, but it's not looking like those were involved. 

Not sure what else to do with this except hope it doesn't happen again and try to investigate again if it does? 

Or longer-term, change our architecture to not make image derivatives/DZIs on worker dynos at all, we could look into using the IIIF server that runs on AWS lambda instead. https://github.com/samvera-labs/serverless-iiif/

**Comment by jrochkind** [comment]
The errors I found were from Nov 18-19... but this ticket was filed Nov 22.  I guess it just took us a few days to file the ticket, and these are the relevant incidents?  In future, we should put a timestamp of logfile in issue when we create it, if we have a chance!

**Comment by jrochkind** [comment]
Annabel says she was working with this record: https://digital.sciencehistory.org/admin/works/cx63jro

On Nov 18th/19th, and may have had ingest problems that resulted in her deleting and re-ingesting some assets.  She said it may have made a difference whether she ingested as a folder or individual files (I don't think that can possibly make a difference, I think it should hit the ingest pipeline either way, the folder gets expanded to files before it really hits the processing... but I could be wrong!). 

It's only three images, I may try to ingest them to staging in various ways and see if I can reproduce.... staging doesn't have hirefire autoscaling, but since the problem involves out of memory within one dyno, that shoudn't matter too much? The problem does potentially depend on timing/race condition of exactly what jobs get executed when though, so might be hard to reproduce. 

If it's hard to reproduce, at least that might tell us this should be rare? We'll see!

**Comment by jrochkind** [comment]
Just to keep the record... these are fairly large files. 200-300MB. annabel says it's possible they are larger than usual and/or needed because:

> I had a hunch that might be a factor... I think it's because I did some work in photoshop on these and I saved the files with their "layers" which makes them much larger files. I think next time I do that I'll save an extra copy with compressed layers, and ingest that version

**Comment by jrochkind** [comment]
Annabel thinks those image are larger than they needed to be. 

What we may have learned is that on our present infrastructure, images around 200MB are pushing our capacity and may result in out of memory errors?  (Depending on exact timing/race conditions of processing). But that we may usually not need images that big?

**Comment by jrochkind** [comment]
I think I successfully reproduced the crash on staging, trying to simultaneously ingest the three files from https://digital.sciencehistory.org/admin/works/cx63jro

Staging only has one Standard-2x worker dyno, without auto-scaling, so all jobs were executed on there. 

It actually resulted in TWO R15 errors on heroku, oddly. 

```
Nov 30 12:42:32 heroku/worker.1 Error R15 (Memory quota vastly exceeded)
Nov 30 12:42:32 heroku/worker.1 Error R15 (Memory quota vastly exceeded)
```

Both at same second timestamp on same worker, so that's just an idiosyncracy. 

In this case it looks like it was two `CreateDerivativesJob` that were happening when memory crash happened. So it can be that rather than a Dzi and a Derivatives. 

It's possible something about the "layers" makes these images more expensive for vips to process... or just the file size. 

## Resque in inconsistent state

**NOTE ALSO** The crash left the resque dashboard making it appear that there are three jobs in progress (all `CreateDerivativesJobs`) that in fact were killed, the dashboard is an inconsistent state....  I remember I had a way to restore  resque to consistent state in some cases, let's see if I can find it... aha, I encapsulated it in a rake task, good for me. 

    heroku run rake scihist:resque:prune_expired_workers

Doh, results in an error! I think it's not looking in the right place for resque, I'll look into it more. 

### Solution

Once I solve that, I am intersted to see if we limit the dyno to 2 or 1 simultaneous worker instead of 3, if it can handle without an out of memory.

**Comment by jrochkind** [comment]
Interstingly, after I restarted the worker dyno.... the ghost jobs disappeared from the dashboard. AND, the jobs that had been killed by the R15 _did_ show up in the failed jobs queue!

As `Resque::PruneDeadWorkerDirtyExit`. 

So that's good that in some cases they at least show up as failed! 

Not sure why restarting the worker dyno again was necessary for this -- heroku should have already killed it/restarted workers. Odd. 

And hey, there are indeed 6 failed jobs from Nov 19 on production in failed queue, all with Resque::PruneDeadWorkerDirtyExit.  Derivatives AND Dzi. 

I guess this kind of failure does NOT get automatically re-tried!  Which makes sense because it happens purely in resque without going through ActiveJob.  If we had see those, we could have re-tried them again individually... not sure if we should at this point, they may all be for no-longer-existing Assets. Let me check actually:

* 8d65c2b8-4a9b-4a4b-b82e-b8f2cf05f3d8 : gone
* 03f187dd-143f-4f11-a7cd-ebc85f3568dd : gone
* 414461bf-ed89-4a69-bf95-ccbc7ce24c0b : gone
* c59ea222-9e9c-427b-82e9-4d89ff9dd4e5 : gone

Yep, all gone, no reason to re-run at this point, will remove from production failed queue.

**Comment by jrochkind** [comment]
## Lowering to 2 workers DOES provide enough headroom for these particular files

On staging, I:

   heroku config:set ON_DEMAND_JOB_WORKER_COUNT=0

Without the previously one on demand worker,  we now have 2 workers total on the single standard-2x dyno. confirmed in resque dashboard, only two workers. 

Tried an ingest again... We got Heroku R14 Memory Exceeded (which means you are swapping and will have degraded performance), but *not* any R15 Memory Vastly Exceeded (2x RAM limits, at which point heroku kills processes). 

Repeated 3 times total, same result each time. 

So if we keep having this problem, adjusting our total number of workers per dyno will increase our capacity for large/expensive files. With hirefire autoscaling is working so well, that solution looks avaialble. We'd want to increase the maximum autoscale in hirefire -- now that it's proven to work well and not add significant cost, and because reducing workers would mean we'd need more dynos for same amount of work.
