### ISSUE TITLE
Searchability of OHMSed Interviews in DC 

### ISSUE THREAD

**Issue by sunicolita** [sciencehistory/scihist_digicoll#1511]
I noticed a spelling issue in the Molina interview OHMS segment titles and descriptions; "Berkeley" is misspelled as "Berkley" and shows up 6 times in a search of the [actual record](https://digital.sciencehistory.org/works/8pmnk1q#tab=ohToc). However, when searching for the word "Berkley" over the whole DC, the Molina record does not appear. While we are planning on fixing the spelling, this brought up questions about how OHMSed interviews appear in DC searches. Can we investigate if there is a bug that is impacting these search capabilities, and if there isn't, can we look into ways of making all OHMS fields included in DC-wide searches? 

Thank you!!

**Comment by eddierubeiz** [comment]
As I understand it, the "Berkley" string is only in the descriptions of OHMS "segments" in the table of contents, not in the searchable transcript proper.

Now that I think about it, I feel like we may have consciously decided not to index those descriptions, but my memory is foggy. Jonathan will remember better than me. To be continued!

**Comment by sunicolita** [comment]
The segment detail is correct, Eddie, thanks for pointing that out (and for your help today in general). Looking forward to hearing what Jonathan has to say!

**Comment by jrochkind** [comment]
Yep, it looks like from the Table of Contents/Index/"Segment" section, we are not adding the title and description to the searchable index. 

The only thing we are adding to the searchable index from the OHMS "Index" are the "keywords". 

I don't recall if this was intentional or why. 

It sounds like we should add title and description of the "Index Segments" as well, @sunicolita ? We can do that. 

I guess I'd add them in the same way that the "transcript" text is added -- relativevly low level of "boosting" (matches on other metadata fields like title or subject are considered a "better match" resulting in higher position in search results), as well as with matches showing up in the "snippets" area in search results, as the transcript text does. 

Does this make sense @sunicolita  and @apinkney0696 ?

**Comment by sunicolita** [comment]
That sounds perfect to me, @jrochkind - very helpful. Thank you!

**Comment by apinkney0696** [comment]
Sounds good to me too.

**Comment by jrochkind** [comment]
OK, I'll move this ticket to "Ready" column, so we get to it when we next have time!
