### ISSUE TITLE
"More" buttons broken in facets menus

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1547]
None of the "more" buttons which bring up pop-up boxes containing all of the facets seem to be working.

**Comment by eddierubeiz** [comment]
Start at https://digital.sciencehistory.org/catalog
Click the "Subject" dropdown
Click more» (which links to`/catalog/facet/subject_facet` )
This triggers a JS error -- heavily redacted stack trace:
```
Uncaught ReferenceError: bootstrap is not defined
    at Object.Blacklight.modal.show
    at Object.Blacklight.modal.receiveAjax
    at Object.fireWith [as resolveWith] 
```

**Comment by jrochkind** [comment]
My guess is that the recent Blacklight upgrade broke it. So we would want to downgrade Blacklight to whatever version we had before we last upgraded, as an immediate fix. 

We would then want to investigate to understand what was going on, to: 1.  see if we can manage to fix it while still upgrading Blacklight, and 2. report as an issue to blacklight, since a minor version upgrade ought not to break things. 

I also think we want to add a capybara test for the "more" behavior, even though it feels like we're testing Blacklight's beahvior that should just work... now that it's broken once, it would have been nice to have CI catch that, and I just don't really trust Blacklight. 

The first priority is undoing the breakage in production. 

Let me know if you want to turn any of htis over to me @eddierubeiz , otherwise without hearing from you I'll go work on other stuff so as not to be duplicating your labor.

**Comment by jrochkind** [comment]
Reported to Blacklight at https://github.com/projectblacklight/blacklight/issues/2612

**Comment by jrochkind** [comment]
@apinkney0696 this is fixed in production now. 

I'm going to leave this ticket open while I do some more cleanup and investigation though.
