### ISSUE TITLE
ffprobe characterization of a TIFF containing video stream returns "Invalid data found when processing input" 

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1586]
This does not look like a bug: but `ffprobe` is (properly) failing  on attempting to characterize https://digital.sciencehistory.org/admin/asset_files/hke2ry9 , which is a `tiff` with a `video` stream.

**Comment by eddierubeiz** [comment]
See also https://app.honeybadger.io/projects/58989/faults/84199668

**Comment by eddierubeiz** [comment]
Downloading the file and running ffprobe locally confirms there is something wrong with the file, viz., it contains a video stream:
`[tiff @ 0x15082b600] Invalid TIFF header
[image2 @ 0x15180ac00] decoding for stream 0 failed
[image2 @ 0x15180ac00] Could not find codec parameters for stream 0 (Video: tiff, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, image2, from 'b1020635_059.tif':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 10300 kb/s
  Stream #0:0: Video: tiff, none, 25 fps, 25 tbr, 25 tbn, 25 tbc`

**Comment by eddierubeiz** [comment]
@apinkney0696 will re-export the file from Capture One and reingest it. For now, I'm closing this ticket.

**Comment by jrochkind** [comment]
ffprobe characterization is a new feature we added recently -- it *should* only run on files that are analyzed as video in the first place...  The asset is no longer there for me to look at. 

Was it's content-type determined to be a video type? Do you recall what it's content type was in our internal metadata?

What was it *intended*/believed to be, an ordinary TIFF? 

@apinkney0696 if you still have the file sitting around somewhere, I'd be interested to take a look at it.

**Comment by apinkney0696** [comment]
Yeah just a normal .TIF @jrochkind ! I'm so confused why it came out differently because I batch exported it with all of the other files that didn't have any issues. I took the file out of the record, but it is in S3 still. I can re-ingest it if that would be helpful

**Comment by jrochkind** [comment]
> File should still be up there.

https://digital.sciencehistory.org/admin/asset_files/hke2ry9, which is mentioned here, gives me a 404?

In other news... looking at the code.... I intended ffprobe characterization to only run on video files, is that what it's doing?

At first i was worried maybe not:

https://github.com/sciencehistory/scihist_digicoll/blob/master/app/uploaders/asset_uploader.rb#L23-L25

But looking at that method in Kithe... it ought to be only running on A/V:

https://github.com/sciencehistory/kithe/blob/master/app/characterization/kithe/ffprobe_characterization.rb#L65

I'm curious to look at the TIF and confirm that our content-type detection indeed decides if it's audio or video....

> I took the file out of the record, but it is in S3 still. I can re-ingest it if that would be helpful

No need to re-ingest it, certainly not in production, but can you help me get a copy of it on my laptop, @apinkney0696, to investigate?

**Comment by jrochkind** [comment]
The file in question: 

https://s3.console.aws.amazon.com/s3/object/scihist-digicoll-production-ingest-mount?region=us-east-1&prefix=b1020635+Ostwald/b1020635_059.tif

**Comment by jrochkind** [comment]
OK, yeah, that's just a bad file. 

While it ends in `.tif`, if i try to open it up in MacOS Preview it says it's corrupt or damaged and Preview can't open it. 

The command line `file` utility says it's `data`, meaning it could not identify a file type for it, that's just the generic unidentified type. 

Our in-app content-type characterization uses this logic in kithe to characterize: 

https://github.com/sciencehistory/kithe/blob/master/lib/shrine/plugins/kithe_determine_mime_type.rb#L30-L42

Debugging...

* it first uses the `marcel` library, which decides it can not figure out the type (`"application/octet-stream"`)
*  So then it falls back to use the `mediainfo` command line...  which decides it's `MPEG Audio`!

Which is why it tries to run `ffprobe` on it... but ffprobe is like, nah, this is corrupt, I error. 

So yeah, indeed appears is exactly how @eddierubeiz diagnosed it! I just wanted to confirm for sure. 

It looks like a corrupt file. 

We could hypothetically have better error handling/reporting here, although it's a bit of a pain to do since it's all in the background.
