### ISSUE TITLE
Remove "Original File Type"

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1614]
Remove the "original file type" field from the metadata interface. This information is viewable in the download drop-down menu for public-facing users, and on the back-end.

**Comment by jrochkind** [comment]
For reference, the original motivation to add it seems to be at: https://github.com/sciencehistory/chf-sufia/issues/994

Note that the current display summarizes all members in one line, while the download drop-down is available individually for each asset -- and depends on the particular show page being used for the particular type of work. 

So that actually for instance for video files right now... we aren't including any download dropdowns at all, or individual file download access at all, so the "original" (ingested) file type technical metadata actually won't be available at all in the public UI. 

This is still ok @apinkney0696?
