### ISSUE TITLE
placement of "play" arrow in video player

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/scihist_digicoll#1617]
Can the "play" arrow/button that displays on in the video player when the page loads be moved from the upper left to the middle of the player?

**Comment by jrochkind** [comment]
Probably. It's displaying now as the video.js default. The video.js developer has a long argument about why they think it should be in the top left rather than the center, involving how it obscures the central part of the thumbnail when it's in the center, often showing up over someone's face!

But we can look into how we customize that!

What is the motivation for this, do you worry people will miss the fact that it is a video they can click on to play? Is this in response to any user feedback/testing?
