### ISSUE TITLE
Look into updating OAI-PMH for PA Digital updated guidelines?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1672]
Perhaps we can improve our compliance for improved visibility in PA Digital/DPLA/et al. 

> Hi, everyone.
> 
> I am very excited to announce that the updated PA Digital Metadata Guidelines (v.2.1) are now available. 
>  
> http://bit.ly/metadataguidelines2022
>  
> This revision was relatively minor. Here are a few notes on the changes:
>  
> Added a link to PA 
> 
> - Digital’s GitHub repository in Introduction
> - Standardized and updated language and punctuation throughout
> - Updated field mappings and recommendations, for example:
>   - Added recommended header value for delimited text files
>   - Updated recommendations for the following fields to reflect updated Hub preference for derived values: Identifier, Collection Name, and Contribution Institution
>   - Updated mapping guidelines for IIIF and Media Master fields to explain requirements for Wikimedia Commons Partnership
> - Added section “Wikimedia Commons Partnership” to Introduction
> 
>  
> A huge thanks to members of the PA Digital Metadata Team for their hard work on this!
> 
> Comments and/or questions are welcome and may be directed to info@padigital.org.
> 
>

**Comment by apinkney0696** [comment]
Thanks for putting this in, Jonathan. I also received the email about these changes. I need to read over the revisions more carefully, but at first glance, it seems like the section that pertains most to us is the updated field mapping recommendations.

I'll review the document and let you know if there is anything I see that might require some updates on our end. Did you have any specific improvements in mind to pursue after reading this?

**Comment by apinkney0696** [comment]
I emailed PA digital to ask about whether or not we are already enrolled in the Wikimedia Commons Partnership. If we are not already, I expressed that we would like to opt into the program.

**Comment by apinkney0696** [comment]
Assuming that putting .xml at the end of our record URLs will display the metadata being harvested by PA Digital, we might not be providing them with all of the data we possibly could:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




PA Digital   Label | SHI Digital   Collections Label | Simple DC   element | Qualified   DC element | Present in export?
-- | -- | -- | -- | --
Collection Name | Collection | n/a | dcterms:isPartof | **NO**
Contributor | Contributor | dc:contributor | dcterms:contributor | Simple
Creator | Creator | dc:creator | dcterms:creator | Simple
Date | Date | dc:date | dcterms:date | Simple
Description | Description | dc:description | dcterms:description | Simple
Extent | Extent | n/a | dcterms:extent | **NO**
Format | Genre | dc:type | dcterms:type | Simple
Identifier | Bib no./Object ID/Accession no. | dc:identifier | dcterms:identifier | **NO**
Language | Language | dc:language | dcterms:language | Simple
Place | Place | dc:coverage | dcterms:spatial | **NO**
Publisher | Publisher | dc:publisher | dcterms:publisher | Simple
Rights | Rights | dc:rights | dcterms: | Simple
Rights Holder | Rights Holder | n/a | dcterms:rightsholder | **Qualified (WRONG VALUE)**
Subject | Subject | dc: | dcterms: | Simple
Title | Title | dc:title | dcterms:title | Simple
Type | Type | dc:type | dcterms:type | Simple
URL | n/a | dc:identifier | dcterms:identifier | Simple




</body>

</html>

Here's what appears to be wrong/missing:

- **Collection Name:** We are not currently crosswalking our "Collection" field to the Qualified DC element dcterms:isPartof
- **Extent:** We are not currently crosswalking our "Extent" field to the Qualified DC element dcterms:extent
- **Identifier:** "An unambiguous reference to the described resource within a given context" We could crosswalk the physical item identifier (bib no., accession no., object ID) to dc:identifier
- **Place:** We are not currently crosswalking our "Place" metadata into either a Simple or Qualified DC element. I feel like this might be because of our local attributes (Place of Interview/Manufacture/Creation/Publication), but I think it would be okay to lose those in the crosswalk.
- **Rights Holder:** A Qualified dc field, dcterms:rightsholder, does appear to be harvested for works that have our "Rights Holder" field filled out (for example [see dcterms:rightsholder](https://digital.sciencehistory.org/works/676nk88.xml )), but the value should be text, not the rights statement URL.
- We also have Europeana Data Model elements included in the XML which do not appear to be used at all by DPLA. Are we providing data to Europeana too?

**Comment by jrochkind** [comment]
We are not providing data to Europeana. Anything we included it’s because at one point we were under the impression, rightly or wrongly, PA Digital/DPLA would use it. 

I think it's possible there were things PA Digital uses that aren't actually documented. Or were in the past. :( 

Which makes me think we should be careful making any changes without clearing them with PA Digital... although PA Digital's current "barely keeping the lights on" status may make this hard. 

> Extent: We are not currently crosswalking our "Extent" field to the Qualified DC element dcterms:extent

When you say "cross-walking", are you implying that there is a valid list of controlled vocabulary for dcterms:extent, and we'd have to translate? I don't believe that's the case? Or do you just mean outputting whatever we have in our extent field as `dcterms:extent` in the OAI-DC output? If we are not, it's probably becuase we had no indication PA Digital would/could use it, but perhaps that's changed. 

> Identifier

We do have a dc:identifier in there, that is the URI of the object in Digital Collections. I believe this is what PA Digital instructed us to do. You are suggesting adding additional `dc:identifier` tags with things like bib numbers. I'd want to check with PA Digital to ensure this wouldn't disrupt anything; do we think PA Digital/DPLA would use these for anything, or make them available to anyone? If not, might not be worth messing with. 

>  Place... I feel like this might be because of our local attributes (Place of Interview/Manufacture/Creation/Publication),

I bet we just had no guidance that PA Digital/DPLA had any "place" items that they used! Easy enough to add. 

> Rights Holder… but the value should be text, not the rights statement URL.

I am thinking pretty strongly that we are doing it as PA Digital/DPLA instructed us to, and we should definitely check with them before changing it. I believe they want this as a controlled vocabulary from RightsStatement.org and CC, as URIs, so they could combine it with other providers and let people filter through different rights statuses. Free text would not allow that.

**Comment by apinkney0696** [comment]
Thanks, Jonathan!! I reached out to Emily Toner at PA Digital on 5/18 to ask about the pros/cons, and details about the process of updating our metadata. I was sure to ask whether making these changes to our OAI-DC would have any negative ramifications on our output to DPLA. I will add more information to the ticket as I receive it!

**Comment by apinkney0696** [comment]
Feedback from PA Digital:

> Collection Name: We would certainly appreciate it if you were to map your local collection field to a metadata element that we can harvest. Currently, we assign a generic "Science History Institute Digital Collections" to dcterms:isPartOf for all of your items, since this is a required field, but we didn't have any values for it. Having your actual collection names included would be a great improvement.
> 
> Place: This field is recommended, as it is a high-value field for researchers, so if this can be included in your metadata, that would be excellent.
> 
> Extent: You could certainly include this if you have it available. This is "optional" rather than "recommended" so not a high priority.
> 
> Identifier: We do not map local physical item identifiers, so there is no need to add this to your mappings for the sake of DPLA. However, if you need or want to add it to your mappings for non-DPLA purposes, I don't think it would break anything on our end, as we currently derive your digital object identifier from the object URL rather than from a metadata field.
> 
> Rights Holder: No action is needed from you on this field since it doesn't contain the rights holder's name unless you want to unmap it all together. We unmap your dcterms:rightsholder field on our end, since it doesn't contain the expected information, and we get your standardized rights statement URIs from another field.
> 
> The only thing I’ll add is that sometimes when we have a new field map, our harvesting process can reveal some data quality issues there. I don’t imagine you will have any issues, but I’ll send you any feedback once I review the metadata.

**Based on this feedback, the steps I would like to take are adding the Place and Extent field mappings, please!**

**Comment by jrochkind** [comment]
Thanks @apinkney0696 , can you clarify what vocabulary terms we should use to add those? 

I guess Collection Name is `dcterms:isPartof`, and Extent is `dcterms:extent`?

Place in your chart above has two alternatives, `dc:coverage`  and `dcterms:spatial`, which should we use? (Or I guess hypothetically both?)

I believe none of these terms are currently in our OAI-DC serialization, they aren't already there used for something else or anything like that.

**Comment by jrochkind** [comment]
@apinkney0696 Also, if I understand right:

Should we _remove_  our existing `rightsholder` output? It is currently outputting the rights vocab URI (because we thought they asked us to do this before!), but they're saying they ignore it... and it doesn't seem right. 

OR, we *do* actually have a `rights holder` field we could map there!  I think in our actual data at present, it's always either blank or "Science History Institute".  Should we map that field to `dcterms:rightsholder`? It seems like that might actually be more correct?

**Comment by apinkney0696** [comment]
Hi @jrochkind yes of course!

Here are the vocabulary terms:
Collection Name is `<dcterms:isPartof>`
Extent is `<dcterms:extent>`
Place is `<dcterms:spatial>` (either simple or qualified DC works, but they prefer qualified if available)

The rights vocab URI is already being recorded in the `<dc:rights>` field which I'm guessing is why they are unmapping our current use of `<dcterms:rightsholder>`. If we can map the `<dcterms:rightsholder>` to contain the data from our `Rights Holder` field instead, that would be great.

Thanks!

**Comment by apinkney0696** [comment]
Hi Jonathan, great timing with this comment - the PA digital folks just emailed me and asked if we want to have our updates included in the next harvest and, if so, if we would be able to have our changes done by the end of the day tomorrow so they have enough time to review and check for errors. Is that enough time for you? There's no pressure - they said it's totally fine if we want to wait until the next harvest due to the quick turnaround.

**Comment by jrochkind** [comment]
That’s confusing that the email they sent out the list said Friday, but the email they sent out to us specifically said, actually ,end of day tomorrow?  What was the Friday deadline for then?

It would have been nice to have more than one day notice, but this should be do-able!


__________________________________

Jonathan Rochkind   (he, him, his or they, them, theirs)
Software Developer/Technical Lead
Othmer Library of Chemical History
t. +1.215.873.8239

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>
From: Annabel Pinkney ***@***.***>
Date: Tuesday, June 7, 2022 at 12:18 PM
To: sciencehistory/scihist_digicoll ***@***.***>
Cc: Rochkind, Jonathan ***@***.***>, Mention ***@***.***>
Subject: Re: [sciencehistory/scihist_digicoll] Look into updating OAI-PMH for PA Digital updated guidelines? (Issue #1672)

Hi Jonathan, great timing with this comment - the PA digital folks just emailed me and asked if we want to have our updates included in the next harvest and, if so, if we would be able to have our changes done by the end of the day tomorrow so they have enough time to review and check for errors. Is that enough time for you? There's no pressure - they said it's totally fine if we want to wait until the next harvest due to the quick turnaround.

**Comment by jrochkind** [comment]
@apinkney0696 OK, this is done and now live!

```
<dcterms:isPartOf>Oral History Collection</dcterms:isPartOf>
<dcterms:extent>62 pages</dcterms:extent>
<dcterms:spatial>California--Orinda</dcterms:spatial>
<dcterms:rightsholder>Science History Institute</dcterms:rightsholder>
```

**Comment by jrochkind** [comment]
Looking at this, I'm also curious to ask PA Digital what format(s) are best in dc:date, especially for things like ranges or multiple dates.  I'm not sure if all our dates are being picked up by them.

**Comment by jrochkind** [comment]
OK, we should maybe make another ticket for improving the dates!

We had not found/gotten that date guidance in our original implementation, and it looks like most of our date are not being correctly processed -- meaning in DPLA, if you do a date limit, you miss many of our records.

**Comment by jrochkind** [comment]
@apinkney0696 it's possible I might need to get involved in discussing dates with them. 

For simple single dates, I think I know what we need to change... but then we have things like date ranges, and circa, etc. When they say "EDTF", do they really mean they support *all* of EDTF, level 0-3?  Or just level 1? Or do they have certain ways they'd like "circa" represented (EDTF potentially has a couple), or don't support it at all, etc?

**Comment by apinkney0696** [comment]
That sounds great and definitely a good idea! I'll cc you on my email and introduce you to get things started.

**Comment by apinkney0696** [comment]
I think we can close this - the initial updates of the Place, Extent, Collection, and Rights Holder fields were cleared by PA digital. I will create a new ticket when I hear back about the adjustments we'll need to make to participate in the Wikimedia partnership.
