### ISSUE TITLE
Sort search results by month and day.

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1675]
When using the sort feature for "Newest Date" and "Oldest Date", results should be sorted not only by year, but also by month and day.

I can see how this more granular sort could be tricky for works dated with ranges when refining results to multiple years. We could look at some other institutions to see how they sort their "date range items" among the rest of results.

**Comment by jrochkind** [comment]
This is actually a bit trickier than anticipated, because of logic for figuring out the date to sort as, when there are multiple dates associated with a work and/or a date range -- and some can be full dates, others just years/decades/etc.  

For sort to work the way we think is expected, a bit tricky logic is needed. 

So I see why we initially just used years. Still, it's do-able.

**Comment by apinkney0696** [comment]
I tested a few different searches and everything looks like it is appearing in chronological order with the date ranges coming first in the results list. Looks great to me!
