### ISSUE TITLE
Image derivatives are missing for asset 41723om .

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1697]
Video https://digital.sciencehistory.org/admin/asset_files/41723om is missing image derivatives.

Asset id is: 972da7b1-fc7d-4c92-a208-3dda688804e8

Derivative creation job 4969ba1d-4ffc-4ce2-b0f5-724ff6aa8736 started at 14:57 PM  today; it's not clear what happened to it, although I'm not seeing any failed jobs at the moment.

**Comment by jrochkind** [comment]
Derivative creation job `4969ba1d-4ffc-4ce2-b0f5-724ff6aa8736 ` is confirmed in `worker.1`, so I think we have an understanding of _what_ happened, if  not why. 

I will simply re-run the job.

**Comment by jrochkind** [comment]
```ruby
asset = Asset.find('972da7b1-fc7d-4c92-a208-3dda688804e8')
Kithe::CreateDerivativesJob.perform_later(asset)
```

**Comment by jrochkind** [comment]
Oh wow, running it again resulted in another `R15 (Memory quota vastly exceeded)`, a logged `Resque::PruneDeadWorkerDirtyExit`, and the derivatives not existing. 

Even though that was the only job being processed by the worker dyno. 

Apparently trying to take the thumbnail really uses a lot of RAM?  That's unexpected. We'll have to look into it more.

**Comment by jrochkind** [comment]
Okay, we were asking ffmpeg to sample 900 frames to choose the most "representative" frame for a thumbnail. 

 900 frames should be around 30 seconds, from about second 60 to 90. This was clever, but my guess is that is what's using too much RAM, for high-res videos. 

We don't yet really know the value of this feature, how good it does at picking a thumbnail anyway. I'm going to try reducing to 300 frames (~10 seconds), but may also turn off this feature entirely -- it may be more useful use of time to write staff UX to let staff choose the thumbnail/poster frame manually instead of trying to fight this one.

**Comment by jrochkind** [comment]
OK, through experimentation I found that reducing sample frames to 300 -- still got killed by heroku. Reducing to 100 did not get killed, but produced `R14 Memory quota exceeded` (but not R15 "vastly"). 

Is there any way we can measure actual RAM usage?  I discovered the gnu version of `time` will give you a rough count of "max resident" RAM.  It's not available on our heroku dynos, but can be installed on the Mac -- `brew install gnu-time`, then run as `gtime`.  Memory usage won't necessarily be the same on Mac as on our dynos, but it gives us a rough comparison. 

|# frames sampled|max resident RAM on MacOS|
|------------------|-----------------------------|
| 900 | 3.1GB |
| 300 | 1.3 GB |
| 100 | 513MB |
| 60 | 324 MB |
| 30 | 249 MB |

Wow, yeah that is a lot of RAM!  Our worker dynos are Standard-2X with 1GB of RAM -- which has to be enough for possibly (at present) three simultaneous tasks, and overhead etc.  R15 should be triggered at 2GB. 

So I'm a bit surprised that 300==1.3GB triggered R14 -- but of course there's all the overhead from our running worker processes themselves, makes sense. 

We could try to write logic that sets the number of frame samples based on the resolution of the video (lower resolution we can afford our large number!) --

-- but as noted, we don't really know the value of this feature anyway. Let's just set it to a very low 30.  Sample about 1 second of frames, just to smooth out any especially weird anomalies. But mostly we're just taking the frame at second `00:00:60`, instead of spending the RAM to try to sample more for as yet unproven benefit.
