### ISSUE TITLE
debug download button

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1760]
Selecting the download popup menu button is requiring the user to click on it twice to open instead of opening on the first click.

**Comment by jrochkind** [comment]
If I copy a plain bootstrap 4 dropdown example on to the page... it also suffers from this problem. 

it's like it's a bug with bootstrap 4 dropdowns... but why would that have just started appearing recently? We get bootstrap via a rubygem, when did we last update the version?  Git blame on `Gemfile.lock` says we updated to bootstrap 4.6.1 6 months ago. https://github.com/sciencehistory/scihist_digicoll/commit/6842d122f005de61e55434fcacfaf87bc1455be2

I don't think we've had this problem for six months?

Will try to reproduce on a plain HTML page with bootstrap to be sure, but I'm thinking we must have changed some other local JS that is somehow interfering with bootstrap....

**Comment by jrochkind** [comment]
OK, this is WILD. 

Hypothesizing it was some JS conflicting with something, I started eliminating `require` statements from `./app/assets/javascripts/application.js` (one but not the only main JS starting point) to see if the problem would go away. 

Doing this, I narrowed it down to the inclusion of browse_everything JS. `//= require browse_everything` -- eliminating that made the problem go away. 

But we haven't not changed our browse_everything version in two years, to curent version 1.1.2. https://github.com/sciencehistory/scihist_digicoll/commit/d16a930c46a465ed3d8bbadfffe42ce3ab710f82

So what changed? Or, at any rate, what could be causing the problem? Looking at the [browse_everything JS file](https://github.com/samvera/browse-everything/blob/v1.1.2/app/assets/javascripts/browse_everything.js), the line `require bootstrap-sprockets` rang a bell. 

I recalled we had to change that line in our own app to instead be `require bootstrap`  here: https://github.com/sciencehistory/scihist_digicoll/commit/2bce9e403ce5eedc79fd71a11a4d26a545507735.  Because it was for somewhat mysterious reasons required for compatibility with latest Blacklight release, see here https://github.com/projectblacklight/blacklight/issues/2612

OK, so now our app is  getting bootstrap JS via `require bootstrap`, but  browse-everything JS (that we're including) is pulling it in via `require bootstrap-sprockets`.  If you require the _same thing_ twice, sprockets is (apparently, I guess), smart enough to only actually include it once... but now that we're requiring bootstrap JS with two different names... the bootstrap JS actually does get included in our aggregated Javascript _twice_...

Which in addition to ballooning the size of our JS unnecessarily, I'm thinking also results in this problem in with how bootstrap dropdown works!

PHEW. 

Meanwhile... browse-everything github main has already had `require bootstrap-sprockets` changed to `require bootstrap` a year ago here:  https://github.com/samvera/browse-everything/commit/d57198229baadcb2a6a8296ea7f8a05480273414. In a PR that apparently I approved! https://github.com/samvera/browse-everything/pull/367

But there hasn't been a b-e release since then. 

Will that solve it? Let's find out by pointing my dev copy Gemfile to browse-everything from github main...  YES, that solves it. 

So we may temporarily point Gemfile at browse-everything from github main.  And look into doing a b-e release, since we have recently done a bunch more to b-e too. 

In long term... the whole b-e approach to JS via sprockets has been showing itself to be untenable. I think this is still going to be causing problems for people honestly, there are so many other circumstances that could lead to bootstrap double-loading here.

**Comment by jrochkind** [comment]
We were planning on doing a b-e release anyway, and I posted yesterday in samvera slack that I was going to do so... so I'm going to go ahead and do that now.
