### ISSUE TITLE
Section Expandables/Rename Section Titles on Works Page

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1775]
Add/rename section headings to the works page.

1. Create a new section heading called "Details" that will go above the descriptive metadata and below the description text. Works that have transcriptions and translations could just not have this heading, or the tabs could go beneath the heading?
2. Change "Physical Location" to "Location" as this section can contain info about digital locations as well. (e.g., the link to the library catalog/archivesspace)
3. Change "Related Items" heading to "Related Works"
4. Create a new section heading called "Learn More..." to contain links to interpretive items. (See ticket # )
5. Insert an option for each section to be expanded or collapsed.

See Ticket #1777 for an illustration.

**Comment by jrochkind** [comment]
I don't love (1) and (5), I think it will make the page busier and actually make it harder for users to find what they need. 

I am curious what motivates these, and wonder if it's possible to do any user-testing. 

On (2).... the heading I had been considering was "At The Institute", as all the fields aren't really about "location" either.  But it is all about the item as held at the institute, instead of as an independent creative work that might exist in duplicate copies elsewhere, where everything but what's in this section would still apply and this section would not. What do you think?

**Comment by apinkney0696** [comment]
Update as of 8/2/22

1. Decided against.
2. Options include: `Administrative Details`, `Organizational Details`, others? Annabel to get feedback about potential favorites and other options.
3. Decided against.
4. Create a new section heading called "Learn More" to contain links to interpretive items. In progress, see ticket #1804.
5. Decided against.
