### ISSUE TITLE
New "Learn More..." Section on works page

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1776]
Create a new section on the works page for links to the Institute's interpretive resources. 

Each item could have an image, the title of the item, and a category for each. The categories of resources we would want to link to include:
- Distillations Articles
- Distillations Podcasts
- Historical Biographies
- Storymaps
- Blog Posts
- Digital Exhibitions

Not sure exactly how we will become aware of our digital collections being used in new resources or if there is any way to automate this. Probably will want to create a workflow with content creators so that they alert us when the reference or use the digital collections works.

I'm also unsure how this would look in the back end. I wonder if we would want this to function similarly to how interviewer profiles are applied to OH works - staff could create one "Learn More" item and apply it to multiple works. 

See ticket #1777  for an illustration.

**Comment by jrochkind** [comment]
My thinking was this would be an enhancement replacement to the current "Related Links" feature, not an additional new feature with "related links" remaining intact as-is. Does this match your thinking @apinkney0696?

The implementation is of course more than a new section on the page display, it also involves metadata modelling and entry for this new material. 

Is "Storymaps" a thing that already exists at the Institute?

I'm not sure that this is the right/best way to take care of Digital Exhibitions (or physical exhibitions too!). Just a "related links" feature won't give us a way to list/collocate all items from a given exhibition; I was thinking we'd want that, so would want to tackle this differently, something more like the Collection feature for Exhibitions, although it might not be exactly like the Collections feature.

**Comment by jrochkind** [comment]
I'd like to do an analysis of the current URLs listed in "related links" to see what sorts of things are currently listed there; perhaps just listing the unique hostnames with counts would be sufficient to paint that picture, at least for first try.

**Comment by jrochkind** [comment]
Per discussion, I think we will probably split this ticket in two -- one for an extended "related urls" feature to be tackled first, and another for "how will we deal with museum exhibitions" to be tackled later. 

To begin with though, I have some listing of how "related URL" field is currently used in our database:

Here are all all the hostnames found in current production related_urls

{"othmerlib.sciencehistory.org",
 "digital.sciencehistory.org",
 "archives.sciencehistory.org",
 "othmerlib.chemheritage.org",

 "www.sciencehistory.org",
 "guides.othmerlibrary.chemheritage.org",
 "www.encyclopedia.com",
 "archives.dickinson.edu",
 "catalog.hathitrust.org",
 "www.acs.org"}>

The first four are internal Dig Coll links; OPAC (including using old chemheritage form); and links to EAD. All expected. 

But then we have some links to two other internal websites, and four other external ones!

Let's get the details:

| Item | Related URL |
| ------------- | ------------- |
| https://digital.sciencehistory.org/works/1n79h4894 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/bn999735x | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/m039k4903 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/m039k4903 | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/02870v85d | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/p2676v53n | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/p2676v53n | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/2z10wr23f | https://www.sciencehistory.org/distillations/video/distilled-3-water-fit-for-a-king |
| https://digital.sciencehistory.org/works/8910jv725 | https://www.sciencehistory.org/distillations/celluloid-the-eternal-substitute |
| https://digital.sciencehistory.org/works/r207tp357 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/6108vb275 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/70795870d | https://www.sciencehistory.org/distillations/video/distilled-8-penicillin-jug |
| https://digital.sciencehistory.org/works/ns064603t | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/4t64gn212 | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/w95050503 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/dr26xx94g | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/0z708w40c | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/fagrxsp | https://www.sciencehistory.org/distillations/braving-the-elements-why-mendeleev-left-russian-soil-for-american-oil |
| https://digital.sciencehistory.org/works/ldg0a5b | https://www.sciencehistory.org/historical-profile/joseph-louis-gay-lussac |
| https://digital.sciencehistory.org/works/v405sb34p | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/h128nd69k | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/h128nd69k | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/k643b1186 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/xw42n791k | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/kh04dq53m | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/ww72bc44r | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/76537136c | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/sn009x805 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/8049g508k | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/z029p5724 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/f4752g788 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/cn69m5159 | https://www.sciencehistory.org/distillations/video/distilled-3-water-fit-for-a-king |
| https://digital.sciencehistory.org/works/xs55mc83v | https://www.sciencehistory.org/distillations/video/distilled-7-bicycle-horn-or-breast-pump |
| https://digital.sciencehistory.org/works/f7623d391 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/6q182k97t | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/7s75dc890 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/rj430493h | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/3f462543d | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/9c67wm86f | http://archives.dickinson.edu/people/c-scott-althouse-1880-1970 |
| https://digital.sciencehistory.org/works/9c67wm86f | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/nv935361x | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/z316q162x | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/6395w7662 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/rx913p90h | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/hd76s009b | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/tb09j565c | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/n7yy6se | https://catalog.hathitrust.org/Record/006496880 |
| https://digital.sciencehistory.org/works/dz010q07r | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/5425kb256 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/m039k5624 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/n583xt987 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/fq977v889 | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/k930bx013 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/pv63g130s | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/3f462544p | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/fx719m462 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/c247dt09d | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/5t34sk17b | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/vq27zn98m | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/jq085k01r | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/jq085k01r | http://www.acs.org/content/acs/en/education/whatischemistry/landmarks/beckman.html |
| https://digital.sciencehistory.org/works/zk51vh15t | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/2514nk52m | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/2514nk52m | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/ks65hc76p | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/j098zb10q | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/t722h880z | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/td96k360d | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/x633f100h | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/0c483j381 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/0c483j381 | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/ws859g16b | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/t148fj06m | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/w3763731m | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/dv13zt259 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/dv13zt259 | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/vq27zn431 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/vq27zn431 | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/fq977v64q | https://www.sciencehistory.org/distillations/video/distilled-5-porcelain-painting |
| https://digital.sciencehistory.org/works/2n49t172m | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/2n49t172m | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/xs55mc071 | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/nk322d33s | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/nk322d33s | http://www.encyclopedia.com/doc/1G2-2841300057.html |
| https://digital.sciencehistory.org/works/qj72p716m | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/v979v413n | https://www.sciencehistory.org/distillations/video/distilled-3-water-fit-for-a-king |
| https://digital.sciencehistory.org/works/m326m229b | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/vq27zn42r | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/9c67wm87q | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/d504rm19j | https://www.sciencehistory.org/distillations/video/distilled-7-bicycle-horn-or-breast-pump |
| https://digital.sciencehistory.org/works/pg15bf80s | https://www.sciencehistory.org/distillations/video/distilled-7-bicycle-horn-or-breast-pump |
| https://digital.sciencehistory.org/works/sn009x79d | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |
| https://digital.sciencehistory.org/works/jq085k79n | https://www.sciencehistory.org/distillations/video/distilled-2-an-early-gold-plated-not-quite-iud |
| https://digital.sciencehistory.org/works/3x816n53x | https://www.sciencehistory.org/distillations/video/distilled-3-water-fit-for-a-king |
| https://digital.sciencehistory.org/works/1544bp09p | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/5mm0m0y | https://www.sciencehistory.org/distillations/braving-the-elements-why-mendeleev-left-russian-soil-for-american-oil |
| https://digital.sciencehistory.org/works/ms35t861q | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/r207tq11v | https://www.sciencehistory.org/fine-art#provenance |
| https://digital.sciencehistory.org/works/f7623c62m | http://guides.othmerlibrary.chemheritage.org/DyesandDyeing |



OK… 

*  A bunch of things link to https://www.sciencehistory.org/fine-art#provenance … I'm not sure how much sense that makes… if we want every item with a Provenance statement to include a link to our statement on how we do provenance, we can automate that, instead of manually entering it in related urls?


* A bunch of things link to  http://guides.othmerlibrary.chemheritage.org/DyesandDyein … linking to a LibGuide is I guess another use case/category?


* I guess several records associated with Crompton & Knowles  link to an encyclopedia.com article on the company… odd. 


* A few links to biographies and distillations articles already!


* A few other interesting external links

**Comment by jrochkind** [comment]
Closed for #1803, #1804, and #1802

**Comment by jrochkind** [comment]
I realized related urls/related links exist in Collection too, and we should address those there too to keep everything consistent. 

Doing a similar analysis of what related_urls are currently used in Collections....

45 of them have links to their OPAC records, eg: https://digital.sciencehistory.org/collections/9k41zd965.  (There are possibly other Collections that could have these links but don't?)

ONE currently has a link to a Finding Aid, Eugene Garfield papers, https://digital.sciencehistory.org/collections/w1y114h (@eddierubeiz , note that we'll have to fix this when AS PUI comes online?)

There are no other uses of related URLs seen in Collections at present.

**Comment by jrochkind** [comment]
@apinkney0696 So, there are actually still about 100 works that have an OPAC link in "related URLs" but do NOT have a bibID in identifiers.... I thought we didn't want to do this anymore, but I'm not sure what's going on here. All of them that I've sampled are archival stuff...

https://gist.github.com/jrochkind/07ac56a9b323e54ae930e453cf60b20c

i could write a script to try and add all these as bibID in identifiers...  but I'm not certain that's what's intended, maybe there is a reason these were done like this?

**Comment by apinkney0696** [comment]
These all appear to be pretty old (all created in 2016 and 2017 from the small selection I looked at). Did the OPAC link automatically generate from the bib no ID at that time? If not that could have been the only way to link to the OPAC at the time?

**Comment by apinkney0696** [comment]
Will I need to go through and update these manually? Not a problem, I'll just have to set aside an hour or so to do it

**Comment by jrochkind** [comment]
At one point adding OPAC url as related link was the only way to generate the link, and a link was not automatically generated from bibID.  but I would have expected bibID to still be listed in metadata as an external ID, if it was relevant, even in those times. I wasn't sure if these 100 records are just mistakes, or if there was some reason to avoid listing bibID as an externalID while listing an OPAC link as related URL. 

If we think they are just mistakes, and should be fixed...  I can write a script to try to move them all over automatically. But it would probably take me an hour or two to do that too. So if it will really only take you an hour, not sure which method is best!

**Comment by apinkney0696** [comment]
I think they are probably just mistakes. I can't think of why we wouldn't list the bibID if we're linking to the OPAC in the Related URL field.

I'll do it! I'll try to get it taken care of sometime tomorrow if I have time so they'll be fine by the time you're back on Monday.

**Comment by apinkney0696** [comment]
Finished!

**Comment by apinkney0696** [comment]
Hi @jrochkind, I emailed Molly for a little background on those Provenance links. Here's what she said:

> Hi Annabel,
> 
> The museum usually hires a fine art provenance intern to do research on our paintings.  The paintings/fine art works in the digital collections that have the link to the statement are the items where further provenance research was done.  But with provenance, sometimes it’s a never ending process. 
> 
> We could add the statement to all the paintings or we could also just get rid of the link for those paintings.  I’m open to doing whatever looks cleanest in the DC.
> 
> Best,
> Molly         

I think it's reasonable to automatically add this link to the Provenance field. I'm just not totally sure of the parameters under which it should appear.  I'm thinking it should automatically show up on any work that has a Genre of "Paintings" AND a Department of "Museum." I _think_ that would cover everything considered to be in the "Fine Art" collection that the statement would apply to. Or maybe we want it to show up on anything that has something in the provenance field, although this now includes some rare books and other museum items. What are your thoughts?

The link could say "Statement on Provenance" instead of the URL, perhaps?

**Comment by jrochkind** [comment]
Interesting, so it shouldn't appear on *everything* that has a provenance field, but are supposed to be only those that are "Fine Art" (assuming we do use "provenance" on other things; if we don't we certainly could in the future). 

Do we think the current "related URL" *is* showing up on everything it should be? Has it been applied consistently? 

Especailly if it has not been... and if Molly is saying she's fine with getting rid of the link too... maybe we just get rid of it rather than dealing with the complexity of automatically figuring out where it should be, or otherwise making a special feature for it?

It could also be added as a collection-level related URL on relevant Collections, and using our new related url feature that will display a label to the user, not just a URL.  Maybe the label would be "More information about provenance". 

OR, if the current workflow is actually working fine, where people are manually adding this as a related URL to indivdual works -- it's not burdensome, and we have been succesfully doing it consistently where desired --  maybe we keep doing that, and migrate the related URLs to our new system as "other internal" links, with a label "More information about provenance"?

I'm reluctant to do a custom feature, now that it looks not completely trivial, if Molly isn't actually asking for it.

**Comment by apinkney0696** [comment]
Yeah, I think you're right, it really is a bit complex to build a custom feature. And to answer your question, I doubt the current URL is showing up on everything it should be or applied consistently.

I like the idea of adding a link to the Collection level, (such as the Fisher or Eddelmen collection, mentioned on the Fine Art page) as you suggest. The label "More information about provenance" is great.
