### ISSUE TITLE
add force download button to OH audio delivery emails

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#1782]
updated title/ticket to: "add force download button to OH audio delivery emails"

~Since several requesters have had issues downloading audio files, it could be helpful to have an explanation in the oral history request template of how to download audio files.~

**Comment by rachellane12** [comment]
I like the idea of having a link that forces a download, if that isn't too complicated to do. My sense is that if downloading files is easier, more recipients of oral history interviews will do so.

**Comment by jrochkind** [comment]
That is do-able. So that might actually be a better solution than adjusting the text, give them a better UI they hopefully won't need more instructional test for!

**Comment by jrochkind** [comment]
updated title/ticket to: "add force download button to OH audio delivery emails"

**Comment by jrochkind** [comment]
I suppose the "PDF" link can also get a "Download" link underneath it!

**Comment by jrochkind** [comment]
OK I have a draft of OH request emails with additional link options. 

it's a bit hard to figure out how to fit these in in a non-confusing way -- especially because it is difficult to do more than the simplest formatting in email. 

I could use some feedback! @rachellane12 @dcaruso-scihist @apinkney0696 @eddierubeiz 

First reminder, here is what emails look like now, pretty much the same for MP3 or FLAC:

* ![Screen Shot 2022-08-03 at 4 25 17 PM](https://user-images.githubusercontent.com/149304/182704947-84fb22aa-505e-462b-b449-0aa35cb67eca.png)

OK, so first -- when we have MP3 source audio in Digital Collections, we will be adding one additional link, to force the download:

* ![Screen Shot 2022-08-03 at 4 26 18 PM](https://user-images.githubusercontent.com/149304/182705157-8b27a492-f3de-44e7-ba20-c89187cfac43.png)

When our source audio is FLAC, things get more complicated. We are now automatically creating much smaller M4A derivatives. We are changing the "main" link to that M4A copy. Then we add download links for both the M4A and the original (very large) FLAC:

* ![Screen Shot 2022-08-03 at 4 27 57 PM](https://user-images.githubusercontent.com/149304/182705458-08f809be-a4c6-4793-959e-d978941c6229.png)

All those links are maybe a BIT confusing? This is the best I've come up with so far. Curious anyone's reaction!

**Comment by jrochkind** [comment]
Alternately, better or worse if I make the extra links look like "buttons".  (Also it's possible this whole approach is not great, just what I've come up with so far). 

![Screen Shot 2022-08-03 at 4 47 07 PM](https://user-images.githubusercontent.com/149304/182708604-f7d1a1c6-ed40-46fc-b82c-973494cadc3e.png)

**Comment by apinkney0696** [comment]
My first reaction is that it looks pretty busy, but I'm not sure if I have any alternative suggestions... My two cents is that I think I prefer the way the links look rather than the buttons, but I defer to @rachellane12 for any final decisions! 

Is the link to open the file in a browser a priority? Could we instead make the file name link to automatically download the smaller file rather than open a browser? Then only add a second link beneath if there is a FLAC file? Do users want the original FLAC files? 

I'm late to the game, but wanted to throw these questions out there in case they haven't already been discussed! Just ignore if not helpful. :)

**Comment by jrochkind** [comment]
@apinkney0696 you're suggesting the email would not give any way to listen to the audio in the browser, the only links it would provide would be download links? 

I had assumed some people would want to listen in the browser, and without the links be annoyed -- or worse, actually not be able to find/figure out how to listen to the downloaded files! Or not have enough space on their local device to download all the files. 

But I'm just guessing. Curious if @rachellane12 or anyone else has any sense of it from interacting with users. 

There's a limit to what we can do here without some kind of user-testing; I don't feel like i personally understand very well here what users want or need or will find confusing vs useful.

**Comment by jrochkind** [comment]
OK, another at attempt at making it less cluttered, without the "button" style. 

One thing here is just the confusing nature of the list of links, we don't really have anything to say about all the audio links except their filenames and the order they are in... wait, that's not entirely true. We could say the starting time in total audio of each audio file. We could also separate or label the PDF edited transcript vs audio files. Let me know if anyone thinks it's worthwhile to experiment with that. 

Otherwise....

![Screen Shot 2022-08-04 at 11 17 53 AM](https://user-images.githubusercontent.com/149304/182884399-a558e064-52c8-45df-be5c-fdbada0de86a.png)

@rachellane12 are you seeing these comments? I'm curious your opinions based on your interactions with users of these emails, as you are maybe the person who has had the most.

**Comment by jrochkind** [comment]
So I can't really do the downloads page on the web as it is, without investing in tools we don't currently use, that would enable more sophisticated formatting on emails. 

So can you say more about what aspects of that you are saying you want to emulate, specifically?  

* I can't really do a popup-menu like that
* I can't really do lots of different sizes and spacings of things, mostly this is just going to be text, with maybe a few embellishments
*  I can maybe do two columns
* That web page separates the PDF from the audio in separate sections, is that part of what you liked? 
* The start time for each audio file, in the context of the complete audio... I can put this, I'm not sure it really makes much sense though when you don't have a player in front of you that can play the entire audio, what do those "start times" even mean without that?  I could instead put in file duration in minutes/seconds...

I could spend a bunch more time on this... I'm not totally sure if we're going to get anywhere more useful... I'm cautious about our ability to know if we've gotten somewhere more intelligible to users and their needs or not. 

Unless we can find a way to get feedback from actual users, my inclination is to start out as simple as possible, rather than spend a lot more time on this without really being sure what users will find confusing or not. But at the same time I agree I'm not thrilled with what I've come up with so far. @apinkney0696 , maybe we'll talk about this more at Monday meeting and decide what we want to do?

**Comment by rachellane12** [comment]
@jrochkind That all makes sense. I wasn't thinking more complex formatting. I was just thinking of how it was divided: PDF, then a label Complete Interview Audio File with a link to download that, and then a label Separate Interview Segments with links to download those:

Download PDF: ___link here___

Complete Interview Audio File:
Download M4A: ____link here___

Separate Interview Segments:
Download FLAC: ____link here____
Download FLAC: ____link here___
Download FLAC: ____link here___

I defer to you and @apinkney0696 to determine if file duration for the separate audio files would be useful. And I completely agree that starting simple makes sense since we don't have feedback from actual users. Whatever you and Annabel decide is good for me!

**Comment by jrochkind** [comment]
Thanks! We don't actually have a "complete interview file" available for restricted OH's, and it would require additional development work to do so. 

(Some of the technical details for why that's trickeir than expected -- OHMS requires audio files to be publically viewable, but we require our restricted OH audio files _not_ to be, so we have different requirements for a "complete interview audio file" for public vs restricted audio. Dealing with public vs restricted in our app has ended up a bit complex for historical reasons)

**Comment by rachellane12** [comment]
Oh, very interesting. I'm sure there's a lot behind the scenes I don't realize. Side note: restricted oral histories I think conclusively are the bane of everyone's existence!

I think if there's a way to have a division between "open in browser" versus "download" or a division between PDF and audio files in the email text could be nice, but at the end of the day, as long as there's a force download button to the OH audio delivery emails, you will have solved the problem originally stated!

**Comment by jrochkind** [comment]
OK @rachellane12  -- while this definitely isn't perfect, we have gone live with a new version of the email that's very similar to the last draft I showed you. 

Please do let us know if you know of any problems -- or if you get any feedback from users or other sense of if it's working for them or confusing them!

We may do more work in the future to make the email even better and clearer, especially if we get feedback that it's confusing people and a barrier!

**Comment by rachellane12** [comment]
@jrochkind As I mentioned on Slack, I like the addition of "-listen" and "-view" at the end of the links that open up a PDF viewer/audio player. Also, it's much clearer how to download files. Thanks so much for your help!
