### ISSUE TITLE
Customize facets in Immigrants and Innovation OH collection

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1857]
Hello! I am working with Sarah S. to put together the new [Immigrants and Innovation Oral History Project ](https://digital.sciencehistory.org/collections/wkppqzw)collection page. Could the facet bar on the left be customized to match the one on the main oral history page? This will include:

Interviewer Date
Interviewer
Subject
Institution
Birth Country
Features
Availability

Thanks!

**Comment by apinkney0696** [comment]
Also, when completed and if I'm gone, would you be able to send a quick message to Sarah S. to let her know, please?

**Comment by jrochkind** [comment]
This will take some time, it's not as easy as it appears. Is there a deadline?

**Comment by jrochkind** [comment]
@sarahschneiderSHI says:

>  I would like to have the page updated by mid-October if possible; I'll be presenting at a conference in October and would like to share the link with folks then. Thanks!

> Having it ready by October 17 would be great.

@apinkney0696 it looks like your plan is to have all these OH's show up in TWO collections, the main OH one plus this "Immigrants and Innovation Oral History Project"?

I can't think of a reason this wouldn't work, but it's not something we have generally done, the original use cases were one work one collection (although the software has always supported multiple collections, since sufia days).  But good to just make sure me and @eddierubeiz know about the new use case, so we can keep it in mind. 

You/we might want to make the new secondary OH collection public and live well in advance of the deadline at which it will be presented at a conference, to try to catch any oddities or edge cases in advance. 

We might also want to list it on the main OH home page?

**Comment by eddierubeiz** [comment]
Duly noted. For the record, I'm a fan of using collections this way, and I'm comfortable with the idea of collections as potentially intersecting sets of works.

**Comment by apinkney0696** [comment]
Hi @jrochkind and @eddierubeiz - are you talking about having oral histories show up in both the "Oral History Collection" and the "Immigrants and Innovation Oral History Project"? I'm almost positive we had a conversation about oral histories being sorted into double collections - why I didn't think it needed to be addressed! Remember when we made all of the oral history Projects into Collections? (https://github.com/sciencehistory/scihist_digicoll/issues/1496) See, for example, [this interview](https://digital.sciencehistory.org/works/z316q261v) which is in both the Oral History Collection and the Nanotechnology Oral History Project collections.

Also, I totally didn't realize this would be a more in-depth request. Thanks for dealing with me throwing this at you right before I left for vacation among all of your other tasks! Happy to chat more about details at our meeting.

**Comment by jrochkind** [comment]
@apinkney0696 it's all good, I think!
