### ISSUE TITLE
Add sort and search to staff Collections list page 

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1921]
To the staff interface [Collections](https://digital.sciencehistory.org/admin/collections) list page, I would like to add some ways to make finding a collection easier.

Here are some ideas that I believe would be helpful: 

- A search box
- To see the collecting area (library, museum, COH, or Archives) for each in the list view
- Ability to view only collections of a certain collecting area
- Ability to sort by created and modified dates

**Comment by jrochkind** [comment]
We should be able to add all of those features! Will take maybe a few days to a week of work. 

While we're at it -- I don't think this list is paginated at all now, it probably should be paginated at 100 items per page, as the number of collections keeps growing! (I think originally I naively imagined there would only be a couple dozen of them, not understanding how collecitons worked!). Once we have a search bar, it should be fine to paginate instead of putting them all on the page at once.

**Comment by apinkney0696** [comment]
That sounds great! Thank you!
