### ISSUE TITLE
Discuss additional account types + an in-app QC system

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1946]
There is an increase in folks who will be using the digital collections in the future (intern season approaching, new curatorial fellows requesting accounts, and more staff needing access to the digital collections for new workflows). I'm worried about accidental deletions, and minor errors in metadata appearing. This ticket is for discussion of a few different solutions.

First, I would like to reorganize our account types into three categories

> **Admin** (highest rank, quality control):
> All permissions. Delete, create, edit, publish, add and create users
> 
> **Editor** (will need to have training in metadata and app use from an admin to achieve this role):
> Create, edit, publish; NO DELETE.
> 
> **Viewer:**
> View and add to the digitization queues. NO EDIT. NO DELETE.

Here is our current list of users and the new account types they should be given:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/apinkney/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>

aaugustyniak@sciencehistory.org | Ashley   Augustyniak | Viewer
-- | -- | --
apinkney@sciencehistory.org | Annabel   Pinkney | Admin
cmccarthy@sciencehistory.org | Caroline   McCarthy | Viewer
egavin@sciencehistory.org | Erin Gavin | Viewer
erubeiz@sciencehistory.org | Eddie Rubeiz | Admin
gzoller@sciencehistory.org | Gabriela   Zoller | Viewer
jauerbach@sciencehistory.org | Jahna   Auerbach | Editor
jmcdaniel@sciencehistory.org | Jocelyn   McDaniel | Editor
jrochkind@sciencehistory.org | Jonathan   Rochkind | Admin
jvoelkel@sciencehistory.org | Jim Voelkel | Viewer
mdimeo@sciencehistory.org | Michelle   DiMeo | Viewer
msampson@sciencehistory.org | Molly Sampson | Viewer
pshea@sciencehistory.org | Patrick Shea | Viewer
rlane@sciencehistory.org | Rachel Lane | Editor
snewhouse@sciencehistory.org | Sarah   Newhouse | Editor
sschneider@sciencehistory.org | Sarah   Schneider | Editor

</body>

</html>

Secondly, I would like to find a new solution to conducting quality control. It's easy for editors to make a typo or miss a piece of metadata - we're all human. Currently, with oral histories and the Bredig project, (and even before that during my work with Hillary), we use google sheets to keep track of recently edited records so that I may QC them. I would love for there to be a way to build a quality control workflow into the app for the admin account type. Perhaps wishful thinking, but I think it could be very helpful.

Let's use this ticket for discussion and I'll create more tickets for specific tasks as needed.

**Comment by jrochkind** [comment]
The first part, adding additional roles, is probably something we could get to right away -- perhaps this should actually be moved to the top of the list, Eddie do you feel capable of tackling it?  I would suggest as long as we are trying to find and go over all permissions, we also look to eliminate any place that assumes logged in user means at least "staff" -- for instance, any part of code that currently checks for `current_user?` should instead check for something like (under these new permissions) `current_user&.viewer?` -- even if the current implementation of `viewer` might be `def viewer ; true ; end`. 

The second part about QA workflow requires more thought I think. Both because it will be a lot more work to implement, and because I think the chances of getting it wrong are higher. But what are you thinking now? Do you actually want all edits to have to be reviewed by someone else before they go live?  That's particularly complicated to do with already published things.  A built-in list of "recently edited" works is a lot easier; showing you exactly what the edits were is harder though.   I think we should spend more time thinking about what we really want to accomplish; investigating what other institutions have done here; and then we have to square that with what is technically feasible to accomplish and maintain.

**Comment by apinkney0696** [comment]
Closing as tasks were completed in two other tickets #1948 and #1995.
