### ISSUE TITLE
Oral History Keyword Display

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1953]
@rachellane12 and the oral history department did some informal user testing with Michelle and family and friends to look at the use of OHMS interviews. They are subsequently reworking their guidelines for keyword use in the table of contents and need a little help with the development. 
(Ticket 1 of 2)

**1. Make the Keywords look less like buttons.** 
The keywords are meant to quickly signify to a user what a section is about; keywords will also be highlighted when searched, so should help the user locate sections about a certain topic.

OH staff received feedback from users that there are too many keywords per section, and are therefore overwhelming. They are going to decrease the number of keywords applied in their OHMS workflow going forward, but would also like the appearance to be less button-like, and simply appear like another text section, delineated by commas or semicolons.

**Comment by jrochkind** [comment]
Yep, when I designed this feature i was definitely thinking they would apply only a few keywords per section, because that's all the OHMS examples I had seen. I was surprised when they started applying so many instead, and agreed that the design was not appropriate for that! Glad we're circling back to fix it. 

That's exciting they did some user testing!
