### ISSUE TITLE
Add "Reel" category to Physical Container field

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2021]
Add "Reel" category to the Physical Container field. 

In Slack, we also talked about narrowing down what this field really means. I think the conclusion was that data here should record where one can find the physical object. For that reason, I don't believe "Page" and "Part" are necessary fields. Open to bouncing ideas around, but that's my proposal!

**Comment by jrochkind** [comment]
@apinkney0696 We don't have any other place to record "page" or "part".  

If we want them in there at all, but the issue is just that they don't really fit into "physical container" _exactly_... I'd probably just leave them there, not worth the trouble to fiddle with it just to put it in a different "category". 

So if we wanted to explore that, we might want to look at the way page/part have been used in existing data, and see if we want to keep it.  I think what it was intended for was like, if we scan just a chapter or section of a book, we might want to record the page number -- not only for location, but because it matters for citing?  But it's possible it hasn't gotten used much?

My inclination would be to leave page/part alone for now unless they are causing a problem!

Adding reel shouldn't be a problem... I would try to make it show up basically consistent with where any other "physical container" attributes show up, which also means it'll be included in the citation. Labelled `reel: X`, I guess.
