### ISSUE TITLE
JS error: "rails-ujs has already been loaded"

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2056]
On any page in production, open a JS console to see the following error:

```js
Uncaught Error: rails-ujs has already been loaded!
    at e.start (rails-ujs.js:683:17)
    at application.js:47:7
```

**Comment by jrochkind** [comment]
I guess this was caused by #2035, which was necessary to get rails-ujs to load (once!) in vite dev!

I guess we need to somehow wrap it in a conditional that checks if rails-ujs has already loaded. 

That's still just hackily treating the symptom instead of really understanding what's going on (why is rails-ujs not automatically loading in vite dev situation like it's supposed to, requiring #2035 ?) -- which I don't love, but I'm not sure I'm going to be able to get to the bottom of it.
