### ISSUE TITLE
Back up our our git repo to S3?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2075]
Let's consider storing a nightly copy of the code for the digital collections website alongside the nightly database backups in our S3 backup bucket.
The nightmare scenario is very, very unlikely: GitHub has to go out of business overnight, _and_ both developer laptops need to be obliterated at the same time.
That said, it might not be a lot of work to implement given our current workflows.

**Comment by jrochkind** [comment]
Seems pretty unnecessary to me. Even if easy to implement, it's another moving part we have to *maintain*.  Any backup system also has to be regularly verified/tested if you want to be sure it's actually working and making the backups you think it is. 

What prompted this idea?

If we did want to make sure we had another copy (and I'm not sure we do), I'd probably suggest we push it to another git host, like say gitlab, which would be a simple "git push", instead of trying to make sure we've correctly copied a git repo including complete git history in a static file system package. 

But it's not clear to me it's worth introducing something that we would have to maintain and verify. 

(Currently, I think the copy pushed to heroku is also another git copy!)
