### ISSUE TITLE
DC Redesign 

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2119]
Please find some sketches for the redesign located in P:\Othmer Library\Digital Collections - Internal Access\Website Updates\2023 Website Redesign Updates
https://files.sciencehistory.org/navigate/folder/d14ff8a8-a0ff-430f-87db-1b1e431d4a9d

These are my suggested looks for the DC which will closely match the new design and branding themes of the main website.  This is a draft of a large-scale eventual goal, open to adjustment and feedback based on what is feasible, of course. Please add your feedback to the comment section of each .pdf in Egnyte to keep them organized. 

In order of importance, here are the changes we should prioritize:
- Add new Main Website header and footer
- Add a thin DC header to separate the new MW header from our page body
- Create a DC footer with About, FAQ, and Contact options
- Update the colors and select fonts to match the new brand guidelines. 

Eventually, we can move on to upgrading pages, such as the homepage to add a new header image/mimic the [support](https://files.sciencehistory.org/navigate/file/5b44f1e4-3e67-4d98-a10c-e96f62d72c24) page; the OHMS page to apply changes from the feedback we received during user testing; and collections pages to also apply user testing feedback.

I understand that it isn't ideal to undergo rebranding efforts while other projects are put on hold, however, it is a priority to adopt the design, branding, and feel of the main website in the DC, even if it takes a few months and several rounds of iteration.

**Comment by jrochkind** [comment]
> • Add a thin DC header to separate the new MW header from our page body

While at first I was partial to this solution, I actually think we can do something that looks good and matches the main site better _without_ adding a "divider" bar.  I'd like to try it out and show it to you.

**Comment by apinkney0696** [comment]
Sure; as long as it's clear that the user is on the digital collections site and there is still a search bar, I'm totally open to other ideas!

**Comment by apinkney0696** [comment]
Feedback from updates on Wednesday, May 3rd. Minor adjustments to conclude phase 1:

(1) make the FAQ, ABOUT, and CONTACT buttons all the same size, center text, and slightly larger than they are currently.
(2) to adjust the section titles on the homepage and the OH collection page so their margins begin at the same point as the header icon/text
(3) add a little bit more white space between the text on the contact/faq/about pages and the footer.

**Comment by jrochkind** [comment]
Thanks @apinkney0696 !

1. I'll see if I can find a way to do this, it's a bit tricky with the way CSS works to make them all the same size regardless of the text contained within, but I think maybe i can find a way that will mostly work. 

2. Is it okay if this waits until phase 2?  That was definitely on my list for when I redesign the home page as a whole for phase 2, but I was trying to mostly alter the things in between the header and footer in phase 1 --  there's actually a lot to be done there, and I'd rather approach it as a whole (including because the CSS is a bit tricky)

3. Same, those margins haven't changed from current production, is it okay if I take care of this in phase 2, so I can do my best to do it with CSS that is general purpose solution to the site as a whole, as part of re-doing the CSS in general?

**Comment by apinkney0696** [comment]
Great, thanks @jrochkind !! And yep, no problem 2 and 3 can definitely wait until stage two!

**Comment by jrochkind** [comment]
List of different page templates that need to be redesigned/checked

* [ ] Home page [example](https://staging-digital.sciencehistory.org/)
* [ ] Work show page -- ordinary image-based [example](https://staging-digital.sciencehistory.org/works/p408o02)
    *  can be good to check variations, with additional titles or not, check related links, different sized descriptions (or missing), etc. 
 * [ ] Work show page with bredig-style transcription/translation [single-page](https://staging-digital.sciencehistory.org/works/rrst45l) [multi-page]
 * [ ] Work show page, video [example](https://staging-digital.sciencehistory.org/works/9rwub9c)
 * [ ] Oral History custom home page [example](https://staging-digital.sciencehistory.org/collections/gt54kn818)
 * [ ] Oral history works
     * [ ] OHMS [example](https://staging-digital.sciencehistory.org/works/y02f8m6)
     * [ ] playable audio, no OHMS [example](https://staging-digital.sciencehistory.org/works/ksyktpa)
     * [ ] upon request [example](https://staging-digital.sciencehistory.org/works/grwtk2l), [request page](https://staging-digital.sciencehistory.org/works/grwtk2l/request_oral_history_access)
     * [ ] permission required [example](https://staging-digital.sciencehistory.org/works/bwv8gvz), [request page](https://staging-digital.sciencehistory.org/works/bwv8gvz/request_oral_history_access)
* [ ] search results [example](https://staging-digital.sciencehistory.org/catalog?search_field=all_fields&q=chemistry&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=)
* [ ] Collection pages
  * [ ]  [standard](https://staging-digital.sciencehistory.org/collections/wh246s128), [search results](https://staging-digital.sciencehistory.org/collections/wh246s128?q=chemistry&sort=)
  * [ ]  [featured topic](https://staging-digital.sciencehistory.org/focus/food-science), [search results](https://staging-digital.sciencehistory.org/focus/food-science?q=chemistry&sort=)
* [ ] Text pages (FAQ, About, etc) [example](https://staging-digital.sciencehistory.org/about)
* [ ] Rights statement page [example](https://staging-digital.sciencehistory.org/rights/NoC-US/9c67wn266)

**Comment by apinkney0696** [comment]
PHASE TWO FEEDBACK:
Before launch:

-	Blue link text looks fine to me for now, but I am looking forward to comparing the different options.
-	I think Eddie may have mentioned this already, but I also think the offensive content footer paragraph looks a little off when it’s fully justified. I’m curious to know if you tried to left align and what you thought of it?
-	I find the red x on the OHMS page a little distracting. It really draws my eyes when I open the page, whereas I think we want the title and portrait to be the first thing noticed. 
-	I found that all the text in the OHMS TOC sections blends a bit. I wonder if using the red color for the section headings “BEGINS WITH” and “KEYWORDS” will help distinguish the different pieces of info here.
-	On collections / featured topic pages, my eyes expect the paragraph of text to be left aligned at the same margin as the collection title text and search box, not with the teal or red colored box. (Might just be me, but it feels off slightly)
-	I’m still torn about having the title visible in the OHMS page on scrolling; curious to say what OH team says or if they say anything.


After launch:
-	Consider doing the “zoom in” thing to collections and featured topic buttons on hover
-	The [Missing] option in the date facet doesn’t seem to work, but I think this is true in the site currently
-	 I couldn’t get the cookie banner to show up as is – I trust it’s fine now, but as we already discussed we will come back to this to either remove it completely or update it to comply with international standards.

**Comment by jrochkind** [comment]
> I think Eddie may have mentioned this already, but I also think the offensive content footer paragraph looks a little off when it’s fully justified. I’m curious to know if you tried to left align and what you thought of it?

Ah, I think I didn't really understand the suggestion. Back when we originally implemented this, I showed you both normal left-justified and full-justified versions, and you liked the full-justified one.But of course the design is different now.   

I was worried full-justified made it harder to read, but thought it made it look neater and less obtrusive, which I still think. 

Can you say anything more about what looks "off"?

Here's the non-justified version:

![non-justified-warning](https://github.com/sciencehistory/scihist_digicoll/assets/149304/1eb3e1ad-7c71-4a31-b324-30a5a61f59af)

I have no strong opinions if you like that better. 

> I find the red x on the OHMS page a little distracting.

I thought I asked about that, but it might have just been Eddie I got feedback from!

We're kind of running out of colors here, since it needs to be stand out from background and (at least how it's designed now), the button it's next to. I'll see if I can find something. 

> I found that all the text in the OHMS TOC sections blends a bit. I wonder if using the red color 

I can experiment with that -- as long as we aren't using red for links!

> On collections / featured topic pages, my eyes expect the paragraph of text to be left aligned at the same margin as the collection title text and search box

I know what you mean... I just don't think I can manage to make that work, technically.  it's a challenging problem for weird reasons, especially dealing with multiple screen sizes. 

I was actually wondering if you were going to say something about this when I showed you the first draft of the collection page!

I can spend more time with it, if we have time. 

> I’m still torn about having the title visible in the OHMS page on scrolling; curious to say what OH team says or if they say anything.

I can add it back. It'll just take up a little bit more space in fixed bar, as well as being on the screen a lot. Just let me know. I don't really know either.
