### ISSUE TITLE
Sofia pro font isn't displaying diacritics like ō

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2208]
The title for e.g. https://digital.sciencehistory.org/works/azd0kva (jp)

and the metadata for https://digital.sciencehistory.org/works/v405s943f (ru)

contain fancy diacritics which aren't part of the font we're using. It looks a little jarring. 
Clearly not a show-stopper. I do wonder if there's a version of the font with more Unicode glyphs in it.

**Comment by jrochkind** [comment]
Hi, I'm confused if you are reporting a problem with current production, or with our current staging with new redesign font. 

If with new redesign font -- can we confirm now whether the problem already exists with previous fonts, or is actually new/worse? I am not certain -- for the russian transliteration at least, I think it may be the same, not new?

Adobe fonts, from which we are using the fonts, does offer some options for character sets included. 

* Default (intends to includes characters for  English, French, German, Italian, Portuguese, and Spanish)
* All Characters (all included in font, different fonts have different ones)
* Language Subsetting (where you choose your languages)

Right now we have Default selected for the new redesign sofia-pro.  

I am not sure what was selected for pre-redesign font, since that is in an Adobe Fonts account we don't have access to, so can't look at configuration. 

Choosing "All Characters" will include all characters included in font -- at cost of much larger font that takes longer to load for clients.  And whether it actually makes these examples display better depends on what characters are included in Sofia Pro. 

In the case of the Russian transliteration -- library cataloging notoriously uses an archiaic no-longer-very-used form of russian transliteration, and I'm not totally sure what those characters are. I have seldom seen them displayed very well on the web -- I am not sure if sofia pro is going to include them or not. 

We could choose Language Subsetting, but I'm not sure what alphabets Adobe Font is going to believe those characters we want belong to!

Experimentally, I'm going to try turning on "All Characters" to see if it makes a difference for your example, stay tuned.

**Comment by eddierubeiz** [comment]
Thanks for investigating. Yes, I am talking about the contrast between:

- before: ![before](https://github.com/sciencehistory/scihist_digicoll/assets/94723/178d7716-d0bd-466b-8430-d0c4455aa0c0)
- and after:  ![after](https://github.com/sciencehistory/scihist_digicoll/assets/94723/43c08227-8e08-4280-a63f-990335ec93a3)

**Comment by jrochkind** [comment]
OK, in that before/after (different than mine), you are comparing our current font (abril) to the new one (sofia pro). 

Do you see a before/after difference with the russian transliteration there? I don't think I do.

**Comment by eddierubeiz** [comment]
Oh, and confirming that for glyphs like i︠a︡  (transliterating Russian letter я)both the old and the new font show problems, which I hadn't noticed before - sorry.
- Before: ![old_font_2](https://github.com/sciencehistory/scihist_digicoll/assets/94723/a2142beb-bfa9-4b0c-a0ae-20c75739beef)
- After: 
![new_font_2](https://github.com/sciencehistory/scihist_digicoll/assets/94723/cb26cc56-e08b-4b45-9217-1def155a4c9f)

**Comment by eddierubeiz** [comment]
Yup. And we don't have a lot of foreign titles except Western European languages + Latin, none of which exhibit this problem. So - not a showstopper.

**Comment by jrochkind** [comment]
OK wait. If we change the order of the fonts listed as possible substitutions, to put `Arial` first... that particular `o with macron` character comes out a BIT better from Arial than from whatever other substitution font it was using:

![Screen Shot 2023-06-14 at 12 42 26 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/5b4e6ba9-0335-49ca-b511-16dcd7c9f7bf)

That's with fonts specified as:

> sofia-pro,Arial,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Noto Sans,sans-serif,"Apple Color Emoji","Segoe UI Emoji",Segoe UI Symbol,"Noto Color Emoji"

(Arial was already on list, but has been bumped to top of list right after sofia-pro). 

Still noticeable, but better enough to be worth changing?

It may look different on different OSs, if they have different versions of "Arial" installed, or other fonts in that list. 

It is possible that it will make other substitution chars look worse even though it makes this one better... but "Arial" not a weird font or anything, should be fine?

I also tried `sans-serif` as the preferred substitution font.... very similar and better than what we started with, but on my MacOS, slightly worse  match than Arial. 

![Screen Shot 2023-06-14 at 12 51 07 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/c5418c22-9e0b-4789-ae5c-11bac875de52)

Change the order of fonts listed, so `Arial` is preferred substitution font?

(to my eyes, it doesn't make much difference to the russian transliteration example, but I'm not sure if I"m seeing the same "problems" as you, the russian transliteration example to me seems not too bad to start with)

**Comment by jrochkind** [comment]
For the record, I believe the font it was using for substitution for the prolematic very heavy o-with-macron in the issue report was: 

`BlinkMacSystemFont`

Whatever that is, it just has a really bad font-weight 900 which was a lot of the problem... or it MAY actually be a bug in Chrome with BlinkMacSystemFont!!  https://www.bram.us/2020/04/24/chrome-vs-blinkmacsystemfont-a-workaround/

Although it looks the same on Firefox, so I don't think it's a Chrome-specific bug actually that we're having. And we are having the font-weight applied, just font-weight 900 looks terrible and is a poor match!

It was listed second in our font list, copied from Bootstrap. 

Actually, it'd be worth seeing what Bootstrap 5 uses as the default font list (ours is from Bootstrap 4).  Bootstrap 5 default font list:

> system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"

Does not improve things -- `system-ui` (on Mac) and `-apple-system` I think end up referring to the same font as `BlinkMacSystemFont`, the one that has problems with font weight 900, perhaps because of a bug in Chrome. 

But I think I'll update to the current bootstrap font list, then adjust to put Arial first, and/or the apple system fonts last....

**Comment by jrochkind** [comment]
OK, `system-ui` or `BlinkMacSystemFont` on Mac ends up being San Francisco -- and possibly even San Francisco Display at large sizes. It doesn't really have "problems" -- it's just a really really thick weight at 900, and not a good substitute for our font, at least at that weight!

We just need to adjust our font stack, to have better substitutes (still need subs for when our web font doens't include something, as in this case!) and probably leave that one out entirely.

**Comment by jrochkind** [comment]
OK, some more info, let's be clear. 

* When a character/glyph can't be found in the primary font, a fallback font is used -- we specify the fallback fonts in CSS
* The things Eddie found are cases where fallback font is being used for some characters -- and as far as I can tell, were, in exactly the same cases, under our previous font "adelle sans" (from adobe typekit), as currently with "sofia pro" in adobe typekit.  It's just that the fallback font looked closer so we didn't notice -- at least on MacOS, the way we specified fallback fonts could vary depending on platform!  
* With sofia, and especially with font-weight 900 in titles, it was no longer a good match -- and I haven't found a good match
* The issue @eddierubeiz meant to point out with the russian translitereted text was that Sofia has a "single story" lowercase a (without the hook on top" -- which is pretty unusual. But the fallback has a "double story" lowercase a.  **I have not been able to find any free font that is a good match for sofia and has a single-story a.** at font-weight 900 makes it even harder
* We have switched to Arial as our primary fallback font, which is a better/decent match, but does have a double-story a (and somewhat different x-height). 

Here's another example of a replacement involving a macron, and a double-story a:

Now, okay, the plot thickens -- if I go to fonts.adobe.com, and choose sofia, and enter that string in the same/demo/test box -- it seems to *correctly display the vowels with macrons without substitution*!

![Screen Shot 2023-06-15 at 10 57 55 AM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/92dde214-dd09-485a-9485-f2acdfb17640) in https://staging-digital.sciencehistory.org/works/9vaq8vo

(It does still use substitution for the `Ḥ` capital h with dot below it -- or in this case can't display it, on my other computer it used substitution!). 

So that makes it seem like we should be able to get it to do so for us too, for those characters. I may try to file a support ticket for adobe.

**Comment by jrochkind** [comment]
OK, when I try to create a demo reproduction with sofia pro and "Abū Mūsā Jābir" -- so far it's displaying the macrons fine, without need for fallback!

So this was a really good find @eddierubeiz , something somehow is going wrong in our app, although I can't figure out how, whether it's some bug we triggered in browser font handling or what. 

Definitely trying to investigate further!

**Comment by eddierubeiz** [comment]
Huh. So Sofia pro DOES have the ā and friends. Yeah -- in that case, definitely worth investigating. And maybe changing the title of this issue!
