### ISSUE TITLE
Collections images blurry 

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2236]
Noticed today while browsing collections on a large monitor PC, that the collections page images look rather fuzzy, even after uploading new high-res images. Jonathan on Slack says: 

It's too small a thumbnail for its display size.
 We have to probably actually get the collection image processing pipeline to make an additional bigger thumbnail than it’s making now — and then use it on those pages.
 (The smaller one may still be good for the collection list page).

(Honestly, the existing size may not even be right for the collection list page, may want to adjust that and re-generate too while we’re at it — but I think we will want two thumbnail sizes where before we had one).

**Comment by jrochkind** [comment]
We need a bigger thumbnail -- we can look at the existing "show" collection page to decide how big it needs to be. 

Before we were sometimes deciding to have it be 2x as big as the space on page, so it looks high-resolution on "retina" displays -- do we want to do that?  If we do, maybe we want to do something we weren't doing for collection thumbs before -- generate TWO thumbs, a 2x one and a 1x one, and use the appropriate HTML tags to let the browser pick which one is needed for the screen. 

It's a bit weird, because our ccollection thumbs use a weird sub-class of Asset think?

**Comment by jrochkind** [comment]
@apinkney0696 Can you give me an example image that is showing up blurry for you? One that is already uploaded to Dig Coll (staging or prod) is fine, or you can give me it here or on P drive, or any other way. Thanks!

**Comment by apinkney0696** [comment]
Here's one on staging: https://staging-digital.sciencehistory.org/collections/wkppqzw It doesn't look so bad on my Mac at home, but on my work computer with a large monitor it looks very pixelated

**Comment by jrochkind** [comment]
Thanks @apinkney0696 , I see it, and I see it looking better after the fix!

https://staging-digital.sciencehistory.org/collections/wkppqzw
