### ISSUE TITLE
Add text and/or graphic indicating OCR presence on work

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2279]
We want to indicate when a work has OCR applied. Some text on the record page beneath the large photo? Not sure at the moment what it should say - will want to brainstorm.

**Comment by jrochkind** [comment]
@apinkney0696 actually here is the existing "stub" issue for this!

**Comment by apinkney0696** [comment]
I've done some research about this, and I'm ready to chat about some possibilities!

**Comment by apinkney0696** [comment]
Decided to pull the PDF option out of the dropdown downloads menu and create its own button with the title "Searchable PDF." Jonathan to mock up the page appearance.

**Comment by jrochkind** [comment]
@apinkney0696 This ended up being a bit tricky to implement, so I decided to start with just a graphical mockup, to see if this is the right direction or not -- no problem if you think it is not, feedback welcome!

I did try adding both Zip and PDF links to the main page -- for both "Searchable PDF" and non-text PDF, but trying to label distinguishing. 

Even though you were leaning against it, I did try adding some text about the "searchable" PDF to the page -- there was just kind of a spot in the layout for text, and I thought it helped distinguish Searchable from not better.   Just to see what it looked like, can be changed. 

-----------------

![Screen Shot 2023-09-20 at 11 41 15 AM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/65b68251-6d3c-4375-baa1-9b9fb23008bc)

-----------------

![Screen Shot 2023-09-20 at 11 31 33 AM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/47a6effb-d296-48e0-833d-a09664ac59cc)

-----------------

The intent is that clicking on the PDF on this link will actually open up in the browser (for easier searching) instead of forcing a "download" as in other location -- although you still will sometimes get a progress bar first, if it isn't already cached. 

While not shown in this mock-up, the intention is that the PDF/Zip links _will_ still be in the "Download" popup _only_ for the _main_ image (as well as in the viewer), it will no longer be repeated for each thumbnail.

**Comment by apinkney0696** [comment]
Looks nice! Here's my feedback:

- I think both buttons should say download, not one view and the other download. I don't think it should open in the same window, I don't want a user to have to hit the browser back button to get back to the Digital Collections and then lose the file. User testing with researchers has taught me that new tabs are preferred. Let's have it push a download just like in the downloads menu. There will be a full-text search in the browser eventually.

- "graphic-only PDF" might be confusing to a user who doesn't already know there's another option. Let's take that out completely.

- I'm okay with having a sentence under the Searchable PDF, but let's tighten it up to one line. "Computer generated; may contain errors" or simply "May contain errors."

- The sentence under ZIP tightened slightly to "All full-sized JPGs"

I think the layout is fine. The graphics might be a bit large in these mockups, but otherwise, I like the look a lot.

**Comment by apinkney0696** [comment]
Yep, I know how it works. When you download, a user has the opportunity to choose whether it opens in the browser (in a new tab) or on their device. It should be up to the user what the best way to view and search the PDF is until we can say with user testing whether the browser is actually preferred.

**Comment by jrochkind** [comment]
@apinkney0696 Thanks. 

Interesting, it may be that Windows works differently than Mac?  Sorry for the confusion assuming that you were seeing what I see.  

I'm still not certain if we're talking about the same thing or not. 

On my Mac Chrome, the current PDF download links do not give me an opportunity to choose whether it opens in a browser.  It just forces download to my device, without any opportunity to view it in a browser. 

This is what seems to me a non-ideal UX for the "searchable" use case we are targetting, to require many extra clicks (on my browser), in a somewhat confusing UI (on my MacOS Chrome), in order to get to the point where you can actually search within the PDF. 

I could try to make a screencast to show you what I mean, or we could have a zoom where we show each other our screens to try to get on the same page (as it were!) about this?

It's gonna take me some time to get the rest of this done anyway, no rush.

**Comment by jrochkind** [comment]
The original mocked up size of the "file" icons were supposed to be the same as the thumbnail icons on eg https://digital.sciencehistory.org/works/ouqouy0 , but those are not currently shown to end-users anyway, and I suppose they don't need to be consistent.
