### ISSUE TITLE
Export CSV from Cart

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2284]
Add an "export CSV" option for items in the cart.

Metadata should include:

- Title
- URL
- External ID
- Department
- Creator
- Date
- Place
- Genre
- Series Arrangement
- Physical Location
- Collection

However, if it's possible, I think it might be ideal if the export included all or most of the metadata fields. I can then remove data based on my needs once I download the CSV export. Here are some examples of instances I've requested metadata exports before, for reference:  
Ticket #   (Data Requested)
#1951 (Title, Date, Place, External ID)
#1927 (Title, Creator, Place, Date, Genre, External ID, Department)
#1563 (Title, URL, Department, Genre, Creator)
#1449 (Title, URL, Date, Description)

An issue is how to structure the data in the CSV. Jonathan has a great summary of this problem in ticket #1449:
 
> "Our data for a Work doesn't always "obviously" map to a flat list of individual values though. For one obvious example, let's say if they wanted individual asset filenames or sizes. A given work might have 1 asset, or 2, or 10. How do you map the filenames and sizes of multiple children to a single line for a "Work" in a CSV? You can come up with various schemes if you want, whether they'll be workable or not I don't know.
> 
> Or, just staying within Work metadata, for instance, we model "inscriptions" as a "location" and "text". There can be 0 to multiple inscriptions, each of which has a "location" and a "text". How do you map this to CSV? Again, i could come up with some hacky way, but there isn't just one true way....
> 
> Or even subjects -- a work can have many subjects, do you just put them all in a single CSV value, seperated by... maybe not a comma, that gets confusing, because CSV already uses commas to separate values! By semi-colons? And you count on no subject ever containing a semi-colon itself? I think that's a safe assumption in the case of FAST/LCSH.
> 
> This is just a list of examples. In general, determining "how do I represent this all in a CSV" is a non-trivial task, that could take, oh a week or two, to try to go through and get "all" the metadata, and if we just try to come up with something we think is "reasonable"...

I think separating multiple values in one cell by semi-colons, as Eddie did in the export in #1927 would work well. Let's talk through any other info you need and a timeline.

**Comment by jrochkind** [comment]
"All or most metadata fields" in a CSV gets pretty hairy. What do you think @eddierubeiz ?

I suppose we could imagine a feature that let you SPECIFY fields to include, but that is much more complicated to implement. 

Thanks for pre-answering the question about repeated fields, @apinkney0696 , saying to separate with semi-colons. (The problem would be if any data values can include semi-colons themselves, which I'm not sure we can rule out universally, but we can just hope they don't?)

Another problem is with _structured_ data.  

* `Physical Location`. By which I think you mean what we call `Physical Container` in the metadata form? It's actually composed of 7 different possible sub-fields, `Box`, `Volume`, `Shelfmark`, etc.  What do we do with that in a CSV? 
* "External ID" also has both a category and an ID
* "Place" has both a type of place and a value
* There might be more

We can, I guess, combine them all in the same way we do for display... but that is some custom logic for each field specifically, which shows the challenge of doing it for "every possible field", some fields need custom handling. 

I was imagining this feature mainly just for getting the _list_ of things, mainly just with title and ID, to give to developers to say "OK, here's a list of things, now do something to them that I can't do through UI"  Like we also do sometimes, but require you to create that list manually, so I figured it might be helpful to not make you copy and paste all those IDs.  @apinkney0696 , do you see _that_ use case as even existing, or was I projecting?

You are expanding it to be usable for _reporting_ functions. Which I see how that's useful!  It's also potentially more complicated.  

But let's think this through -- some of your reporting needs have been based on _criteria_. All the tickets you reference as examples (thank you!) are like this -- and I think this *cart* based function wouldn't actually have helped you there much?

* #1951, it seems burdensom if you had to add everything in Bredig collection with a certain specific author to a cart first?
* #1927, was for all published records, cart-based feature isn't going to work
* #1563 is for all parent works (no children), also cart-based feature isn't going to solve that
* #1449 is for ~300 items from a certain collection with a certain string query for `mint` -- I am not sure if a cart-based feature is going ot work for that, is it feasible to actually add those 300 items to cart by clicking 300 times?

Can we think more carefully about use cases?

I get that a self-service reporting feature is a long-standing wish (and maybe we should make a ticket for that?). 

* But is a _cart-based_ feature likely to meet many reporting needs?  Will what you've specified here actually meet the reporting use cases you identify, which were mostly for large number of records identified by metadata criteria, rather than manually identified one by one? 
* Is my original idea of a cart-based feature just for assembling _lists_ of records to give to us (say, to then do a report!) actually a use case, or not really a use case?  
* Perhaps we should make a ticket for a more generalized self-service reporting feature -- this would be a larger project, not least because it would involve some requirements/user-analysis to understand your use cases and figure out what feature(s) are actually needed to meet them -- instead of starting with the feature as we did here.

**Comment by apinkney0696** [comment]
After Slack conversation, amending to only include: 

- Title
- URL
- External ID
- Department

**Comment by Gabz73** [comment]
Hello,
As I told Eddie and Chuck today, I'd like to return to this ticket, based on a need Jahna and I have discussed, which is the ability to export the metadata for works in order to QC the metadata in a way that allows easy comparison across multiple records (for instance, finding variations like "William A. Lester Jr" vs "William A. Lester" in the Title or Desc)

Reading through the existing ticket, it appears that the initial list of metadata fields to export was winnowed down to Title, URL, External ID, and Department, based on a particular inquiry Annabel had re. the Booth papers.   
The current use case expands the list of metadata to export. 

From the Works page, admin user can add one or more works to the cart, then export the cart. 
It would be v helpful if you could "Select all on page" to add to cart.

User can search for all works in a DC collection, and can select some or all of the works, add them to the cart, and then export the cart. 
•	Title
•	URL
•	External ID – can be just the value, not the category (2023.17, not “Accession Number” and “2023.17”
•	Department
•	Creator 
•	Date
•	Medium
•	Extent
•	Place
•	Genre
•	Description
•	Subject/s
•	Series Arrangement
•	Physical Location
•	Collection 
•	Rights
•	Right Holder
•	Additional Credit
•	Digitation Funder
•	Admin Note
•	Created 
•	Last Modified 

I would recommend separating repeating data with a pipe ( | ), since commas and semicolons and other elements of punctuation appear in the data itself.

**Comment by jrochkind** [comment]
Thanks! Can we make a separate ticket for "select all on page"?  it's got some technical difficulties which are kind of orthogonal.  And if what you _really_ want is "add all results from this search", we can see if we can figure out a way to do that instead. 

We'll just have to decide how to prioritize these in the midst of various other things we've found ourselves in the middle of!  we can talk about it at a future monday planning meeting!

**Comment by Gabz73** [comment]
Will do.  I think we do want “add all results from this search”!


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>
