### ISSUE TITLE
Asset with no content type - investigate.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2310]
https://app.honeybadger.io/projects/58989/faults/99365407
```
"arguments" => [{"_aj_globalid" => "gid://scihist-digicoll/Work/1b06bb09-b21b-4e54-8023-2039636fc70d"}],
```
https://digital.sciencehistory.org/admin/works/8ozkl75#tab=nav-members

**Comment by jrochkind** [comment]
When running OcrCreatorRemover on given work

```

NoMethodError: undefined method `start_with?' for nil:NilClass

      select { |m| m.content_type.start_with?("image/") }
```
from:

    work_ocr_creator_remover.rb:69  block in image_assets(...)

**Comment by eddierubeiz** [comment]
All assets at https://digital.sciencehistory.org/admin/works/8ozkl75#tab=nav-members  appear to have a `content_type`.

**Comment by eddierubeiz** [comment]
(And that work has `id` `1b06bb09-b21b-4e54-8023-2039636fc70d`

**Comment by jrochkind** [comment]
That work does not currently seem to have any assets lacking content_type, I can run the same code on it without error.... I'm going to just run the whole service again....

    WorkOcrCreatorRemover.new(work).process

Completed without erorr, queued up some jobs. 

Which is weird, since ActiveJob probably retried it once and got that error on second retry but it will just be a mystery now I think. 

Will start up a few workers to process the jobs that that process created, to OCR assets....

All jobs completed succesfully, will close this ticket.
