### ISSUE TITLE
Asset admin page: navigation between adjacent assets in the same work

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2322]
Let's look into making it easier to browse through the admin asset pages sequentially.

Compare:
- https://digital.sciencehistory.org/works/3n203z173/viewer/f7623c65f
- https://digital.sciencehistory.org/admin/asset_files/f7623c65f

The viewer page has a `30 / 32` and `<` and `>` buttons, which makes it easy to navigate between sequential pages of a book.
The admin asset page doesn't. Should we add these features to it?

## Why we might want to do this
**Use case**: Identifying and correcting small metadata problems (OCR and transcription especially) that affect pages that occur in sequence, in works that have a lot of pages.

Once a book has more than 10 pages or so, _going "up" to the work's asset view, finding the asset you were looking at, shifting your focus to the next or previous asset, and going back "down" to the new asset_ is tedious when you have to do it several times in sequence, and adds cognitive load.

## Why we might not
The page is really crowded already.

**Comment by jrochkind** [comment]
Sort of a pain to do because of how the web works -- currently this page has no idea what previus and next asstes would be. 

But I guess not too hard, we just need to load the whole asset list on the individual asset page, to find the current assets place in teh list, and what next/previous assets are?  Or perhaps cleverly SQL for just the immediately preceding and succeeding assets somehow?  Or another solution?

It can be done if it's important -- has this come up as an actual admin user request that would make their lives easier?

**Comment by eddierubeiz** [comment]
Absolutely did not intend to close this. Unclear how I even did it.
