### ISSUE TITLE
upgrade to latest postgres 15.5

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2423]
We're running postgres 14 (EOL Sep 2026) in production (using heroku pg)

Pg 16 came out a month ago, and is EOL Nov 2028. 

New pg may have performance improvements etc, makes sense to upgrade to latest when it's convenient for us!   Probably will be entirely backwards compat, but will need to be tested etc.

**Comment by eddierubeiz** [comment]
I just upgraded staging to 15, following instructions at:
https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-upgrade


Created a follower DB:
```
heroku addons:create heroku-postgresql:standard-0 --follow HEROKU_POSTGRESQL_COBALT --app scihist-digicoll-staging
```

Waited for it to be ready:
```
heroku pg:wait --app scihist-digicoll-staging # until the follower is ready
```

Turned on maintenance:
```
heroku maintenance:on --app scihist-digicoll-staging
```

Turned off workers:
```
heroku ps:scale worker=0 --app scihist-digicoll-staging
heroku ps:scale web=0 --app scihist-digicoll-staging
```
💡  (for prod, we'll also turn off hirefire scaling here)

```
heroku pg:info --app scihist-digicoll-staging # eventually reports that new DB is behind by zero commits.
```

Ran the upgrade on the new DB:
```
heroku pg:upgrade HEROKU_POSTGRESQL_NAVY --app scihist-digicoll-staging
```

Waited for the upgrade to finish:
```
heroku pg:wait --app scihist-digicoll-staging # until the upgrade is finished
```

Told the app to use the new DB instead of the old one:
```
heroku pg:promote HEROKU_POSTGRESQL_NAVY --app scihist-digicoll-staging
```

Got a note:
```
Checking release phase... pg:promote succeeded. It is safe to ignore the failed Detach DATABASE (@ref:postgresql-amorphous-64469) release.
```

Sure enough, got two errors, which I ignored:

 - `ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket?`
 - `A deployment for scihist-digicoll-staging failed due to a release phase command in release v1112. To inspect the failure, check your release phase log in the dashboard or run 'heroku releases:output v1112' in the CLI.`

Turned workers back on:
```
heroku ps:scale worker=1 --app scihist-digicoll-staging
heroku ps:scale web=1 --app scihist-digicoll-staging
```
(for prod, we'll also turn on hirefire scaling here)

And maintenance off:
```
heroku maintenance:off  --app scihist-digicoll-staging
```
And got rid of the old db:
```
heroku addons:destroy HEROKU_POSTGRESQL_COBALT_URL --app scihist-digicoll-staging
```

Voilà.
