### ISSUE TITLE
Adjust progress options for items in digitization queue

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2476]
Hi! In doing metadata this morning I thought of a small change that might be useful for my predecessor. The digitization queue currently has a drop-down menu listing the following status options:

Awaiting Dig on Cart
Imaging in Progress
Post Production Completed
Batch Metadata Completed
Individual Metadata Completed
Closed (Which hides the queue entry)
Hold
Re Pull Object

From a workflow perspective, I think the following list would be more helpful and accurate:

Awaiting Digitization
Imaging in Progress
Image Export Complete
Metadata In Progress
Closed
Hold

If you'd like me to justify why these changes would be helpful I can, but probably would be easier in person at our next Monday meeting.

**Comment by jrochkind** [comment]
Eliminating "re-pull object" is the only one i'm especially curious about... eliminating that one was intentional? 

I'm a bit nervous about changing these when you won't be here to _use_ them and ensure the changes actually work and ask for more changes if they don't... but if you're sure, I guess?  It's not a difficult change to make. (If any exist using to-be-eliminated statuses, we'd have to map them to one of the new statuses)

**Comment by jrochkind** [comment]
Post Production Completed => Image export complete
Batch Metadata Completed => Metadata in progress
Individual Metadata Completed =>Metadata in progress
