### ISSUE TITLE
Support PDF files in Digital Collections

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2492]
@jrochkind I'll let you note the technical to-do's below. 

Our first PDFs in the DC should be the Best Of Distillations magazine files for 2019 and 2023.
The two PDF files can be found here: https://files.sciencehistory.org/navigate/folder/e3c82a7b-cb79-490a-a262-2ac294475a83

Their complete metadata records, awaiting assets, are here:
https://digital.sciencehistory.org/works/h3bv3vt
https://digital.sciencehistory.org/works/hvlp3f4

**Comment by jrochkind** [comment]
Awesome. Those PDFs are about 50MB each. Not sure if we might want to investigate making an "access copy" with lower resolution images for a smaller download, either as the main thing we ingest or an alternate download?

**Comment by jrochkind** [comment]
And those copies also have a "page" being the two-page spread, which I guess we'll leave that way?

I am curious the provenance of these PDFs to understand what's going on.

**Comment by apinkney0696** [comment]
I believe these were the PDFs shared with Clay by the designers from their InDesign files. We would have to pay them about $800 for access to the original InDesign files if I remember correctly. 

I would wait to see what Michelle and/or Clay respond to the email about whether they even think we should put the large file in the DC at all.

**Comment by jrochkind** [comment]
Cool cool, I don't see any need to have the original InDesign!

the PDFs we create ourselves from scanned images use 150dpi JP2s for around 500kb per page on average -- where each page is really nothing but a photograph, since we create them from photographs. But just to have a sense of what size we decided for access copy previously. 

I haven't fully investigated these PDFs to see if they are whole-image pages, or (hopefully!) real born-digital PDFs with just text and the images are only used for image elements. I haven't looked at what formats the images are in.  But they weigh in at around 5MB per page, so a lot larger than what we are otherwise using for access copies.  

One thing to consider them would be downsampling the images to something more similar size/quality to what we are otherwise using for access copies.  I think the main reason to do this would be convenience of our end users, more managable files.  It could be done manually using Adobe Acrobat, for instance.

**Comment by Gabz73** [comment]
Hi, following up on our earlier meeting with some thoughts. In my files I have an email from Annabel to Michelle and Clay, cc'ing Jonathan and me, inquiring whether their desire is that the "DC preserve the original files or only act as an access point". To my knowledge, they did not respond. 

If their answer is that the DC doesn't have to preserve the original PDF files, couldn't we convert the PDFs to TIFF in Acrobat Pro and ingest the resulting TIFFs?  Or am I misunderstanding something fundamental?  

A related question is, if we are keeping the original PDFS, should we convert them to PDF/A, and should we be distributing PDF/A versus regular PDF?

**Comment by Gabz73** [comment]
This is the 1/10/24 email:
Before my departure from the Institute, I wanted to get a few things squared away regarding PDFs in the DC. The DC is not currently designed to support PDFs, but a need has arisen to support the "Best Of Distillations" annual publications. 

Is the intention for the DC to preserve the original PDF files or only act as an access point? I ask because the "Best Of" PDFs are quite large. We can ingest the large PDFs and create a derivative access file in the app if preservation is a priority. Alternatively, we could only ingest an access file.

To set some expectations:

•	The PDF record display will only show a large representative image of the front page and will open the PDF in a new browser window when clicked. It will not display page thumbnails like our records do for works with image files, as per [this record](https://digital.sciencehistory.org/works/r64pt85). Additional development time will have to be coordinated if use cases arise where the individual page display and download capabilities are desired.

•	The work's OCR can be indexed in our system (i.e., they will be full-text searchable in the Digital Collections) but cannot be indexed in Google. In other words, searching Google for an article in Distillation's Best Of will not bring up the Digital Collections record as a search result. This is a Google thing and is largely out of our control.

Jonathan, if there is anything else you'd like to be clarified from a development standpoint, or if you have any notes on the above, please jump in!

Thanks all, sorry for the long email!
Best,
Annabel

**Comment by jrochkind** [comment]
I am not aware if the question  “Is the intention for the DC to preserve the original PDF files or only act as an access point?” was ever answered?


__________________________________

Jonathan Rochkind   (he, him, his or they, them, theirs)
Software Developer/Technical Lead
Othmer Library of Chemical History
t. +1.215.873.8239

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>
From: Gabz73 ***@***.***>
Date: Wednesday, July 31, 2024 at 1:27 PM
To: sciencehistory/scihist_digicoll ***@***.***>
Cc: Rochkind, Jonathan ***@***.***>, Assign ***@***.***>
Subject: Re: [sciencehistory/scihist_digicoll] Support PDF files in Digital Collections (Issue #2492)

This is the 1/10/24 email:
Before my departure from the Institute, I wanted to get a few things squared away regarding PDFs in the DC. The DC is not currently designed to support PDFs, but a need has arisen to support the "Best Of Distillations" annual publications.

Is the intention for the DC to preserve the original PDF files or only act as an access point? I ask because the "Best Of" PDFs are quite large. We can ingest the large PDFs and create a derivative access file in the app if preservation is a priority. Alternatively, we could only ingest an access file.

To set some expectations:

• The PDF record display will only show a large representative image of the front page and will open the PDF in a new browser window when clicked. It will not display page thumbnails like our records do for works with image files, as per this record<https://digital.sciencehistory.org/works/r64pt85>. Additional development time will have to be coordinated if use cases arise where the individual page display and download capabilities are desired.

• The work's OCR can be indexed in our system (i.e., they will be full-text searchable in the Digital Collections) but cannot be indexed in Google. In other words, searching Google for an article in Distillation's Best Of will not bring up the Digital Collections record as a search result. This is a Google thing and is largely out of our control.

Jonathan, if there is anything else you'd like to be clarified from a development standpoint, or if you have any notes on the above, please jump in!

Thanks all, sorry for the long email!
Best,
Annabel

**Comment by Gabz73** [comment]
It was not, to my knowledge - Annabel would have shared the response with us -- which makes me think it isn't the reason they wanted them in the DC, but I would ask again of course.

**Comment by jrochkind** [comment]
I am not aware if the question  “Is the intention for the DC to preserve the original PDF files or only act as an access point?” was ever answered?

Also, we don't have any answer about PDF/A, something that actually was on my list to talk about today too, but we didn't get to. This is perhaps something you want to talk to stakeholders about and develop an answer on? Perhaps consult with @archivistsarah , although I'm not sure if her job description currently includes attention to born-digital Institute products (or Institute products at all) or not?

We COULD convert the PDF to graphics and only ingest those.  Several reasons I would not recommend this:

1. In order to get _text_ out to search, we would have to OCR the TIFFs.  Having software try to recognize images from a pure graphic file -- when we have the original text in the PDF that could be extracted instead -- does not seem to me like a wise course of action.  It is better to use the text from the original PDF. 

2. Additionally, providing the original PDF for download -- or a down-scaled version of it additionally or as an alternative -- will result in a better, smaller, more usable PDF than trying to create a PDF from TIFF files, as we currently do by necessity with photographed images. 

3. It also seems like more work to staff than ingesting the the PDF? 

In general, we do a number of things by necessity when we are starting with photographs that we can do more reliably and efficiently if starting with a publisher's PDF source. 

If we had off the shelf software that could only deal with photographic images, we might be forced to do that anyway, and accept the inferior product. But since we have a development team that can support ingest of the PDF instead, that seems preferable to me.

**Comment by Gabz73** [comment]
Thank you! That's very helpful in explaining why we aren't converting PDFs to TIFFs. I had thought of Sarah N as a resource to talk about PDFA as well.  I will reach out to her, and to Michelle / Clay re preservation expectations.

**Comment by jrochkind** [comment]
(It looks like the PDF files referenced above have been cleaned up in the great P drive cleanup?  

I have them locally, but if it's easy to restore them to P drive, they are useful to have as a reference in a common location? Or maybe we can actually attach them here, if they are not non-public?)

@eddierubeiz ?

**Comment by jrochkind** [comment]
Looks like I can't tag Jahna on github, gah!

@eddierubeiz would you mind getting those from Jahna and updating the description above? We need those as examplesfor the issue.

**Comment by jrochkind** [comment]
(Files are too big to upload here in the Issue on github)

**Comment by eddierubeiz** [comment]
@jrochkind, please try the first thing I suggested above. If you know the name of one of the files, and we kept at least one copy on the P drive, it should be easy to find at https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Othmer%20Library .
Thanks much.

**Comment by jrochkind** [comment]
i believe the file names were `Dstlltns_BO19_FINAL.pdf` and `Dstlltns_BO23_R5_041423.pdf`

i am unable to find them there in that search. 

Sorry, I see it was @Gabz73 that said Jahna knew were they were, I misread it as @eddierubeiz!  

We should get Jahna a github account maybe so she can partiicpate here? Otherwise in teh meantime, @Gabz73 how do you feel about asking Jahna for them and then updating links in description above?

**Comment by eddierubeiz** [comment]
For what it's worth, the second file is at:
https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Eddleman%20Institute/Distillations/Magazine/6-Archives/Annual%20Print%20Issue/Vol%202%20(2023)/Proofs/R5

**Comment by Gabz73** [comment]
I'm actually on vacation but I think Eddie could email her or ask on slack for someone to find the files in the Othmer Library folder.


Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

________________________________

**Comment by eddierubeiz** [comment]
@JAuerbach26  is Jahna's handle, @jrochkind ! :)
