### ISSUE TITLE
Date display when managing a work in admin

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#250]
When viewing metadata when managing a work in admin, date reads "start:" ahead of inputted date when finish date is not provided.  When finish date is not present, please have date only displayed.  E.g., instead of "start: 1922" in example below, should read "1922":

https://kithe.sciencehistory.org/admin/works/eib6761

**Comment by jrochkind** [comment]
My thinking was that the "staff view" metadata should more closely match _what the editor actually enters in the form fields_ than the public view. Is one reason I left 'start' there, it is a thing entered in the 'start' field (on the input form, and in how it is persisted in the database). 

But if editing users are finding it confusing, it can/should be changed. 

However, this brings up a larger issue for discussion -- should the metadata display on the 'staff view' just match exactly the public view?  Is that what staff would want/expect?  Should it differ at all, or should we just put something much more like (perhaps exactly like) the right-hand metadata column in the 'public' view there?

Since the public view does some transformations of the actual on-form/in-database actual metadata (and these transformations can change and be tweaked over time), I thought it was worth experimenting with providing a more "bare metal" actual metadata view in 'staff view'. Also to draw some separation between our valuable metadata (expensive to change, and presented differently in different contexts eg our web app vs oai-pmh), and it's presentation (cheaper to change and contextual). 

But maybe it would meet staff user needs more to just make the staff view metadata match the public view? Now that the public view exists, that can be done. 

Before spending tweaking the staff view metadata, we should decide if we just want to replace it with something more closely mirroring the public view. (Although if we do not, it can indeed be tweaked!)

**Comment by HKativa** [comment]
Unless I'm misunderstanding @yonyitz "start" and "finish" labels are present on edit metadata form in current app, regardless of whether or not there is a value in the field. See "edit work" view for https://digital.sciencehistory.org/works/7p88ch821. Personally, I don't see a reason to remove those labels from edit form if field is empty.

**Comment by jrochkind** [comment]
Won't do for now.
