### ISSUE TITLE
Update to  Ruby 3.2.3 if possible

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2502]

**Comment by jrochkind** [comment]
Not actually on heroku yet,check back tomorrow. 

Once it is on heroku, we MAY get 3.2.3 with next deploy, without having to change any source.  -- depends on if heroku is taking ruby version from `Gemfile` (would automatically take latest 3.2.x) or `Gemfile.lock` (specifies specific version), I'm not sure.

**Comment by jrochkind** [comment]
OK heroku did add ruby 3.2.3 support on 22 Jan

https://devcenter.heroku.com/changelog-items/2790

**Comment by jrochkind** [comment]
I was hoping that since our Gemfile allows `ruby ~> 3.2.2`, it would automatically use the latest ruby allowed, latest ruby 3.2.x, next time we pushed. 

But sadly that does not seem to be the case.  Tried a push to staging, and

```
remote: -----> Using Ruby version: ruby-3.2.2

remote: ###### WARNING:
remote:
remote:        There is a more recent Ruby version available for you to use:
remote:
remote:        3.2.3
```

I guess ruby Gemfile.lock now lists exact ruby version the bundle was built with (it didn't used to), and heroku is now using that?  That's my guess. 

So I guess we really do need to update locally  (update .ruby-version to 3.2.3 specifically) and rebundle, to update on heroku?  Unless there's a way to tell bundler not to include specfic ruby in gemfile.lock, which I might spend a little bit of time looking into.

**Comment by jrochkind** [comment]
Looks like no way to get bundler to omit this, and heroku intentionally is indeed using the lockfile:

> The locked version of the Ruby version will always “win”. So if different members on your team are using different Ruby versions, they must be careful not to commit the wrong version to the Gemfile.lock.

https://devcenter.heroku.com/articles/ruby-versions

The simplest workflow for us without jumping through weird hoops, is we just have to update to new `.ruby-version` locally and commit `Gemfile.lock` to update on heroku. Sad, but so be it.
