### ISSUE TITLE
Video unplayable in public view; showing grey placeholder image instead of video controls.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2538]
This is a work with one unpublished video asset.
[Public view](https://digital.sciencehistory.org/works/ocfp93d) shows grey placeholder image, no video controls.

The [video asset](https://digital.sciencehistory.org/admin/asset_files/3nrgry2) looks correctly characterized, and went through HLS processing fine as far as I can tell, and has the following thumbnail derivatives available:
- 	thumb_mini
- 	thumb_large
- 	thumb_mini_2X
- 	thumb_large_2X
- 	thumb_standard
- 	thumb_standard_2X

**Comment by eddierubeiz** [comment]
I'm ingesting this video in staging:
https://staging-digital.sciencehistory.org/admin/asset_files/9qp5jnr

**Comment by jrochkind** [comment]
@eddierubeiz I think I fixed it in production!

The work didn't have it's "representative" set properly.  This work only has one Asset, so there was only one choice. But it can become unset if you are deleting and re-adding assets, while DC tries to keep up, sometimes it gets confused and "representative" becomes unset or set to an Asset that no longer exists. 

To fix it, in this case, just opening up the metadata editor and clicking "save" without intentionally changing anything will fix it -- since there was only one valid "representative" asset available, it is the only option shown in the "representative" select box at the bottom of the edit form, and just clicking save will select it. 

The workflow for ingesting videos seems to result in QUITE A BIT of assets getting ingested and then deleted -- more than with other kinds of media ingested, it seems like.  This ends up exposing lots of edge cases in our app, since this wasn't considered to be a a primary use case. I wonder if at some point it's worth us doing some "user research" to understand why ingested videos are getting deleted so much as part of ingest workflow, and if there's something we can do to make the workflow smoother for ingesters.

**Comment by eddierubeiz** [comment]
Should have thought of this! Of course. Thanks for investigating.
@archivistsarah  - let me know if you see anything else weird about this video; otherwise we can move this to the "review" column.

**Comment by archivistsarah** [comment]
Thanks!

This is a side effect of our push to get as many videos digitized/uploaded as possible. The videos that get deleted are ones that I didn't watch all the way through before ingesting, and after ingest I find something that needs to be edited out (in this case, an unexpected 15 seconds of bars and tone at the end). I'm adjusting my workflow so that I watch everything through before ingest, which will mean a bit of a slower process, but hopefully fewer issues like this!

**Comment by jrochkind** [comment]
Thanks @archivistsarah ! We want to make things easier on you, not harder -- if it works better for you to upload first, I don't want to stop you!  We might just keep running into occaisonal weirdness, which we can fix when we find it. Just a tradeoff!

For this particular issue, when the asset appears to be there but poster and/or video aren't showing up right, we just need to remember the first thing to do si try editing metadata and clicking "save" without changing anything -- see if that fixes it!
