### ISSUE TITLE
Consider changing color of oral history requests sign-out banner

### ISSUE THREAD

**Issue by sarahschneiderSHI** [sciencehistory/scihist_digicoll#2559]
It would be nice for this banner (that appears after signing out of oral history requests) to be dark green to match the other banners:
![image (3)](https://github.com/sciencehistory/scihist_digicoll/assets/103284115/d723bdc7-a3c1-4f04-8f8d-b77d394ad724)

Thanks,
Sarah

P.S. I cannot mark things with the tag oral history, so please feel free to do so.

**Comment by jrochkind** [comment]
Technically that's showing up with color theme labelled "info", whereas other ones are with color theme labelled "success". Thus the difference in color. 

But we dont' use too many of these alerts user-facing, and haven't been too intentional with how we use them, this is kind of just what we inherited from bootstrap.
