### ISSUE TITLE
FAST place name drop-down isn't populating with most relevant headings

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/scihist_digicoll#2650]
Previously in the DC, typing in a name to the "place" field would populate the drop-down menu with the most likely results from the FAST vocabulary. So, typing "Philadelphia" would give you the FAST heading, "Pennsylvania--Philadelphia", at the top of the list, with other possible matches below it. I don't know exactly how these were being sorted/weighted on our or OCLC's end, but other place names worked the same: typing "New York" would give you "New York (State)--New York" at the top of the list; "Washington" would give you "Washington (State)" and "Washington (D.C.)" both at the top of the list. Users could then click on the correct name and it would appear in the text box. (Apologies for not having a screenshot of this -- you never take a screenshot when it's working as expected.)

Today I noticed that typing "Philadelphia" didn't result in the drop-down options I expected. Most importantly, the correct heading (Pennsylvania--Philadelphia) is not on the list at all -- just 20 other results containing the word "Philadelphia" in no discernable order. 

![DC place dropdown](https://github.com/sciencehistory/scihist_digicoll/assets/25084902/f9c69eba-5968-441d-9d68-671c8a550d9e)

To get the correct place names, users will have to go to the OCLC web interface, search there, and cut and paste back into the DC.

Also note that the search does work as expected in the FAST web interface: https://fast.oclc.org/searchfast/?&limit=keywords&facet=geographic&query=Philadelphia&sort=usage+desc&start=0#&fullview=null&sep=null 

Other FAST fields (Subject Heading and Creator) appear to be functioning as usual.

I think this is probably a OCLC FAST API issue, but documenting it all the same.

**Comment by eddierubeiz** [comment]
I can send this to OCLC on Friday, @jrochkind .

**Comment by eddierubeiz** [comment]
```
Hi there,

I work at the Science History Institute, a library, archives, and museum (see https://digital.sciencehistory.org/).

We use the search FAST API to provide auto-complete in our staff cataloging interface for years. We love it.

I have noticed that it would be really helpful for us to be able to request usage data in the results, and - even better - for the API to provide us with sorted data on that key.

A quick example to show you what I mean: let's use the term "philadelphia".

Here's what we're currently using:

http://fast.oclc.org/searchfast/fastsuggest?&query=philadelphia&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20

Compare those results with:

https://fast.oclc.org/searchfast/?&limit=keywords&facet=all&query=Philadelphia&sort=usage+desc&start=0

So much better! The results are automatically sorted by usage, which puts "Pennsylvania--Philadelphia" at the top of the list.

Is there some way you could add the usage data into the fastsuggest results and allow a sort=usage option to the API?

Thanks so much for considering this.

Best regards,

Eddie Rubeiz
```

**Comment by eddierubeiz** [comment]
💡 This is a separate issue (and might become a separate ticket later on) but I'm writing this down here, for now:

It's also worth noting that the "place" heading lookup is returning *all* results, not just places.

The results you get from typing `philadelphia` into the place suggestion field are listed at: http://fast.oclc.org/searchfast/fastsuggest?&query=philadelphia&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20

Much better, for the "Place" dropdown, would be these results:
http://fast.oclc.org/searchfast/fastsuggest?&query=philadelphia&queryIndex=suggest51&queryReturn=suggest51%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20

which lists places (that's what `suggest51` means).

**Comment by jrochkind** [comment]
@eddierubeiz I understood that we think the results from this API endpoint have _changed_ recently, and dont' return what they used to return. I was expecting the message to be about that, asking if it has changed, if it was intentional, if we could get the old behavior back. 

But that isn't what your message to them was about. But maybe you have more information after talking to staff, and I am misunderstanding the situation?

**Comment by eddierubeiz** [comment]
Oh yeah, that was just the introductory email. Once they responded I followed up. I'm not gonna post the whole convo (not worth it) but the upshot is:

To the best of their knowledge, usage statistics have only ever been used for display ranking in the searchFAST web interface, **not** the `fastsuggest` interface QA is using.

We can continue the convo. They encouraged me to ask any follow-up questions we have.

But for now, this response is both disappointing and difficult to square with  Sarah's account of the original state of affairs above.

**Comment by jrochkind** [comment]
I wonder if there could be a change in how ranking worked that is not related to usage statistics. Perhaps match at beginning of non-first word wound up higher matched than it does now somehow?

**Comment by eddierubeiz** [comment]
Disappointing. The response from OCLC is:
- There is not _currently_ any results display sorting built into the API logic.
- They were unable to locate any information on how the API _used_ to sort.

Plus some polite verbiage about "has been logged as an item for future development".

**Comment by archivistsarah** [comment]
Disappointing, but not really surprising. As long as everyone creating metadata knows to check the FAST web interface, we can work around the inaccurate drop-down options.

**Comment by eddierubeiz** [comment]
They got back to me and changed their mind about the above.
Compare:
- https://fast.oclc.org/searchfast/fastsuggest?&query=philadelphia&query&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20
- https://fast.oclc.org/searchfast/fastsuggest?&query=philadelphia&query&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20&sort=usage+desc

The second one, with the added `sort=usage+desc`, is what we want.

This is a great first step, but based on a glance at our setup, to use this option we have to mess with Questioning Authority, which is quite restrictive about adding extra parameters. I assume we would have to create a PR for them. Not sure if we want to go down this road. @jrochkind - let me know if you have any advice.

**Comment by jrochkind** [comment]
That makes sense. 

We could merge our own PR to QA. 

We could also copy-paste-fork the QA adapter to a local one with this change. I think. We'd have to figure out how to. 

Just some work to be prioritized, I guess?

**Comment by eddierubeiz** [comment]
Yup.
Method `#build_query_url` at
https://github.com/samvera/questioning_authority/blob/main/lib/qa/authorities/assign_fast/generic_authority.rb
is what we ultimately want to change. If you add the param to the URL returned by that method, you get the results we want.

**Comment by jrochkind** [comment]
@eddierubeiz So this `sort` parameter is completely undocumented at the API docs for the API we're using. 

https://www.oclc.org/developer/api/oclc-apis/fast-api/assign-fast.en.html

Do you have interest in replying to the person you are already in communication with, with the suggestion they add this to the docs?

**Comment by eddierubeiz** [comment]
I did suggest it, a couple weeks ago. They didn't reply!

**Comment by jrochkind** [comment]
@archivistsarah @JAuerbach26  @Gabz73  I'm currently testing a fix on the staging server. Can you take it for a test drive and confirm that it's working as you would expect/want now?

Also thanks for the great write-up @archivistsarah !

![Screen Shot 2024-07-25 at 10 19 28 AM](https://github.com/user-attachments/assets/0df2f17d-5072-49be-ba28-d281850a475d)

**Comment by archivistsarah** [comment]
The place results are better! It's now suggesting the state of Pennsylvania when I type in "Pennsylvania" instead of "I-95." But testing did make me notice the special characters not displaying, which is an issue on production, too, I just hadn't noticed it before. 

![special characters_place_staging](https://github.com/user-attachments/assets/1a013f5b-dcba-4d26-a80f-e52cb3455680)

I do see some weird behavior in the creator FAST search. Like "Science History Institute" doesn't show up at all in the suggested creator headings on staging, but it does on prod. 

![creator_SHI_staging](https://github.com/user-attachments/assets/5d500da9-da67-4239-a35d-70e60b17215f)

Also note the differences between searching for "MIT" on staging (where we're getting subject headings first, and Massachusetts Institute of Technology _does_ show up, just very far down on the list & off screen of this screenshot):

![creator_SHI_staging](https://github.com/user-attachments/assets/0b677ff7-987d-4d1a-950d-5851981e2d92)

and on production (where we're just getting name headings):

![creator_MIT_prod](https://github.com/user-attachments/assets/eae12ed7-2771-43e5-a53d-2d9e14fb0fd5)

Is there a way to filter/set the creator field to only search name authorities?

The subject heading results are different than they are in production, but I can't put my finger on anything that's worse or better. They still seem to be sorting the most relevant to the top, even if in a slightly different order.

**Comment by Gabz73** [comment]
I am a bit hesitant about (if it is possible) filtering FAST, in the creator field, to find only name authorities, only because a name will only appear in FAST in the first place if it has been used as a subject in OCLC (so, a work about the person, or organization – it is Faceted Application of Subject Terminology) .  FAST doesn’t include any names that are used in OCLC as authors, unless there is an explicit request to add them to FAST for use.  So I don’t want to create the false impression that FAST is 100% accurate for looking up creator names.  I am no sure I’m explaining that well.


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by Gabz73** [comment]
Oops, meant to offer this example:

SHI doesn’t appear in FAST (right side) but it does have an authority record (left side)
***@***.***

The only record in OCLC that uses “Science History Institute” as a subject heading was contributed very recently (6/4/24), so that heading hasn’t been “harvested” for including in FAST yet, though it should be soon – I don’t remember off the top of my head how frequently they update the FAST list.


***@***.******@***.***


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by archivistsarah** [comment]
But SHI *does* show up as a creator in production. Do we know why it isn't showing up in staging?

Also I didn't realize that's how FAST worked! I assumed there were sub-lists for subjects and people, like how Library of Congress functions. It's a good reminder that I really shouldn't be relying on the drop-down for creators.

**Comment by Gabz73** [comment]
I deleted my comments b/c yes, SHI is indeed in FAST!

I think they do, within FAST, have some way of separating name subjects vs topical subjects vs geographic subject, as topic vs corporate (name) vs person(al name) appear in the Facet column when you search in searchFAST (https://fast.oclc.org/searchfast/?&limit=headwords&facet=all&query=berl&sort=usage+desc&start=0#&fullview=null&sep=null)

But yes, you shouldn’t rely on it exclusively for creators – if you strike out with FAST, check the LC authority file for name headings, which you can search via our ClassWeb subscription (I can show you how!)



__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by archivistsarah** [comment]
I'm on searching with NAF! one of my most-used bookmarks.

**Comment by jrochkind** [comment]
Hi! Thanks for your reviews! @archivistsarah @Gabz73 

My GUESS is that most of the additional issues you identified were present before when it worked the "old way" too, although it's hard to be sure about that. I _think_ we may have succesfully restored it to working how it used to work.

Sadly, we have limited control of how this OCLC service we're using works. At this point, basically we have the option of A or B, what's in production or what's in staging. Is there a consensus on which way is best?

We can possibly file additional tickets to look into if there's anything we can do about additional issues, or send suggestions to OCLC (experience shows they are unlikely to implement any changes or additional features to this service though alas). 

Here are my thoughts on the specific issues I identified you mentioning!

1. special characters not displaying. — I'm not totally following what you mean, but my GUESS is that this has always been happening with this search, is this possible?

2. "Science History Institute" doesn't show up at all in the suggested creator headings on staging, but it does on production => Could this be that because now that we're sorting by usage, "Science History Institute", as little used in OCLC cataloging database, does not sort high enough? Is it possible this was true "before" too?

3. Also note the differences between searching for "MIT" on staging => Yeah, my guess is this is similar to above, when it's putting the most-used headings matching `mit` first the one you want ends up off the page; and had been happening previously when things worked the "old way" too. Does that seem possible?  

4. "Is there a way to filter/set the creator field to only search name authorities?"  I am not sure if there is a way! I sort of recall considering this before, but can't recall why we didn't do it that way, or if we were able to. We could file a separate ticket to look into it — I am reasonably sure it's always been this way for us.

**Comment by Gabz73** [comment]
Thanks Jonathan!  That is very helpful.  We do want “creator” to include person, corporate, and conference names.


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by archivistsarah** [comment]
Ah, thank you! that is helpful context. As long as we expect the behavior, we can work around it (like by not searching for an acronym, as in my example).

**Comment by jrochkind** [comment]
I do see what you mean about special characters now that I look more closely at your screen capture. 

If it's happening on production as well as staging, it's not relevant to whether we make the change here or not, and is probably an unrelated issue. 

Can you file it as a separate issue, that we can schedule and handle separately? It will sadly probably involve communicating with OCLC again and trying to get them to admit there is a problem at all!

**Comment by jrochkind** [comment]
@archivistsarah Our choices are basically the way it is now in production, or the way we demo'd it changing the sort -- we don't have much control to change other things at present, although we could file more tickets to look into it. 

As it is, can you confirm you prefer the change where it's sorting by most used headings? 

Thanks!

**Comment by jrochkind** [comment]
@archivistsarah PS:

> Also note the differences between searching for "MIT" on staging (where we're getting subject headings first, and Massachusetts Institute of Technology does show up, just very far down on the list & off screen of this screenshot):

So, this may not have been clear, and it's still not the top hit, you CAN click on `MIT USE Massachusetts Institute of Technology` to get the heading `Massachusetts Institute of Technology`!  Not at the top, but on-screen in your example!

If users are not realizing they can click on these "USE" headings, that would be a UI failure, sorry!

**Comment by archivistsarah** [comment]
Oh, I see -- you're right it is on screen in that screenshot it just got lost for me. I think both Jahna and I are aware you can click on "use" headings, so this example is a user error not a UI error!

**Comment by jrochkind** [comment]
Phew! Thanks!
