### ISSUE TITLE
special characters not displaying in FAST headings

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/scihist_digicoll#2692]
![special characters_place_staging](https://github.com/user-attachments/assets/cd833f31-026e-46a6-a8c1-a8daf2738dbe)

This screenshot taken from the staging server, but it's the same in production currently (7/25/2024). Special characters in FAST headings aren't displaying. Have no idea if this is an OCLC issue or our issue!

**Comment by jrochkind** [comment]
Thanks! "Washington" in production doesn't show the problem, since it has a different result set. Do you have an example search that currently shows the problem in production too, a search that in production has results with special chars that don't show up properly?

**Comment by archivistsarah** [comment]
Sure! Here's an example from production (search for "cordoba"):

![special characters prod](https://github.com/user-attachments/assets/8e4f3e27-c9bc-401b-bd1c-ed4d710d015d)

**Comment by jrochkind** [comment]
Unfortunately, the OCLC "Assign FAST" API seems to returning characters garbled here in a way I can't figure out how to un-garble on our side. I have sent the following bug report to OCLC, via the form at: https://www.oclc.org/research/forms/fast-contact.html

---

The assignFAST API (https://www.oclc.org/developer/api/oclc-apis/fast-api/assign-fast.en.html) seems to return corrupted characters for headings including non-ascii characters (eg accented characters). 

For instance, see this search:

https://fast.oclc.org/searchfast/fastsuggest?&query=cordoba&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20

Note the suggested headings include the corrupted string "CoÌrdoba" where it ought to say "Córdoba", including a lower case o with acute accent. 

The problem does not seem limited to just this one term, but to any examples we can find that ought to include accented characters. 

We've been using this API for assignment suggestions for several years. We've  only just noticed this problem in the past few years, so have some suspicion that some change happened recently to introduce this problem; but we also can't at present rule out the possibility we just noticed it now. 

The problem does NOT seem to occur in your own web app at eg: https://fast.oclc.org/searchfast/?&limit=keywords&query=cordoba

Is that service using a different API endpoint or parameters, and if so I wonder if such might be available to us? 

Note that JSON responses by standard must be in a unicode encoding.  It's possible these responses are accientally in some some other encoding, but I haven't been able to identify any such encoding, I think they are simply corrupted, probably as a result of a trans-coding gone wrong at some point in the pipeline. 

Thank you for any information or fix you can provide!  We appreciate this API to allow our staff to efficiently assign FAST verified headings; this problem is obviously a barrier to use!

**Comment by jrochkind** [comment]
Did get a response that OCLC FAST Team has received and is looking into it.
