### ISSUE TITLE
(Post launch) Item count on featured topic page is wrong.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#279]
Post launch: the number of "items" listed on the top of the featured topic show page (e.g. https://kithe.sciencehistory.org/focus/alchemy ) is not really the total number of items in the featured topic. Instead, it's just the number of items returned by the latest Solr search. 

This is a known bug we inherited from Sufia. One simple fix would involve just hitting Solr more than once per page load: once for the total count of items in the featured topic and once for the actual faceted search results.

See the corresponding functionality on the Collection show page for the ideal behavior: a count of public items, and a second count of all items, only shown to staff users.

**Comment by jrochkind** [comment]
I think we may actually already be hitting Solr more than once per page load (at least we were in chf_sufia I think) -- we're just not doing it effectively to get the right count, apparently!  But yes, that was the intention all along. 

chf_sufia didn't provide a second count of all items for featured topic, cause that's harder to do from solr; so initially, we don't need to do that either, this ticket can be just getting the public count correct. (The private vs public count on collections were done in response to specific request to support staff workflow; apparently that wasn't needed for featured topics, or at least nobody's ever asked for it).

**Comment by jrochkind** [comment]
Note that the count also can currently different based on whether you are a logged-in staff or not -- if you are logged-in staff, it displays a count including non-public items (if present), if you are a public user it only includes public items. That is, the count is of items that are visible to the current user. 

I won't change/fix that as part of this ticket unless directed to!

**Comment by jrochkind** [comment]
Blacklight is making this much harder than it should be. 

We are currently frozen on Blacklight 7.7.0, because most upgrades to BL ended up breaking our app and we got tired of dealing with it.  BL is currently on 7.15.0. 

When I figure out a hacky way to do this with our current Blacklight version... it would actually break on future Blacklight versions. And be tricky to figure out how to fix, because this is tricky to figure out in the first place. 

The API's Blacklight provides here are extremely abstracted and complex. 

I may experiment with upgrading Blacklight to most recent version to see if that's not too bad, then at least I'm not writing functionality I know will break right away.

**Comment by jrochkind** [comment]
Passes all tests on BL 7.15.0... but with TONS of deprecation warnings. That are tricky to figure out how to fix, some of which are triggered by plugins like blacklight_range_limit.
