### ISSUE TITLE
Upgrade to ruby 2.6.5

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#327]
2.6.4 is released. https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/

No rush, not a priority, but good to stay up to date. I forget if we have our infrastructure such that this kind of upgrade is totally trivial?

There are some issues with coordinating what ruby is provided on the deploy machines, with what ruby our `Gemfile` insists on having. Right now it insists on having a certain one. But we can perhaps fix the code to allow a range, so code doesn't have to be changed when ruby is upgraded a patch level.

**Comment by sanfordd** [comment]
It's not hard but it isn't trivial. Our current setup is to build an AMI with the preferred Ruby version and use that as the basis for new machines. So we'll need to
- [ ] Build a new ami (trivial)
- [ ] Build new web and jobs servers (while we deploy with cap to solr, I don't believe it uses ruby in any other ways)
- [ ] Rotate the new servers into use
The last step requires a elastic IP move and a quick check that the old jobs server isn't running anything when it's taken down. 
If we do have a range of versions, it makes it easier to run the code on both the new and old servers. Our new automatic discovery means if we deploy the code it will go to both new ruby and old ruby servers unless we block the old ones from getting the newest deploy.

**Comment by jrochkind** [comment]
Cool, no rush then, we can just leave this open for when we have time. 

For a future "when we have time" improvement, is there anything we could hypothetically do to make it more trivial? Sometimes there are releases with important security patches, and it would be nice if it could be a trivial thing we could just do without having to interrupt ourselves. Or is it just kind of an aspect of our architecture that it won't be trivial/automated?

**Comment by jrochkind** [comment]
> a quick check that the old jobs server isn't running anything when it's taken down.

If at the moment we are tolerating/expecting interuptions to jobs on every deploy, I think it's fine to generalize this and just not care about that.

**Comment by sanfordd** [comment]
If we want to add rbenv or rvm it's trivial to run multiple versions of Ruby and then remove the old ones once the new version is added. The last time we talked about rvm there were performance considerations to using it in a production environment.

Manually building ruby is slow enough that doing it in production isn't feasible unless we edit our application to target a specific ruby path rather than the general system path. If we do that we could certainly manually build multiple ruby versions and remove the old ones. I think that isn't the most cloud-native method though compared to spinning up new servers as needed.

This is where having a load balanced group would make it easier to rotate new servers in and out of service when we make upgrades, a practice that is to my knowledge the more common way to handle this sort of thing.

I could make an ansible script as a one stop script versus running the 3 ansible scripts (build ami, build web, build jobs), the EIP move shouldn't be automated though unless we can conditionally limit it to a successful cap deploy otherwise we risk outages.

**Comment by jrochkind** [comment]
Don't actually upgrade to 2.6.4, wait for 2.6.5. :(

https://bugs.ruby-lang.org/issues/16136

**Comment by jrochkind** [comment]
Ruby 2.6.5 is now released, so we can update at our convenience.

**Comment by sanfordd** [comment]
@jrochkind Just checking if we also are still pinned on our cap deploys to a specific ruby version so we'd need to update that or if we can deploy to any ruby 2.6 version without needing to update our Gemfile.

**Comment by jrochkind** [comment]
Yep, we are, good thought. It's not actually cap related, but that the app won't run at all (after a cap deploy or anything else), unless the ruby matches what's in `./.ruby-version`, which is currently `2.6.3`.  Becuase the `Gemfile` has a line that reads the `.ruby-version` file, and expresses that as a ruby version requirement. 

I can change it to allow `~> #{ruby_version`, which would mean it will allow any 2.6.x, which gets us here, but doesn't really explain how we'd do an update to a new minor/major when needed. 

I could remove the thing in the Gemfile altogether, so it doesn't require any particular ruby version, although it would open us to up to confusion, it's maybe a nice failsafe to have it be like "This isn't the ruby version you expect."

I guess I'd start with the first probably? 

But since we aren't in production yet, and can handle some downtime... can we just do this 'manually' somehow?  Not sure.

**Comment by jrochkind** [comment]
And actually my first thought about `~> #{ruby_version}` might not actually work due to further changes in bundler... not sure, we might have to experiment.

**Comment by sanfordd** [comment]
We might be able to avoid downtime, though it'll involve a bit of manual editing. 
1. We build the new AMI
2. Freeze deployment to the old 2.6.3 servers
3. Edit the old 2.6.3 servers to _not_ have the scihist_digicoll application tag (causing them to be skipped by capistrano and ansible). They're still live but won't receive any updates. This is the manual update.
3. Build new jobs, web, and solr server.  Solr's got ruby solely for getting deployed to so we need to update it I think. Make sure they point to each other for the local_env configuration.
4. Update the application to support 2.6.5
5. Deploy code to the new server(s)
6. Reindex Solr
7. Move Elastic IP over to the new web server. Users will experience a few seconds of delayed reactions during the move and the first loaded page will be slow.
8. Delete the old servers.

**Comment by sanfordd** [comment]
With changes made, I am reworking the steps for the switch and documenting them here for any future needs.
- [ ] Build new Ruby and Ruby with Java AMIs with the ansible build_ami playbook
- [ ] Build a new Solr server, register the new Solr address in Ansible.
- [ ] Build a new web server, pointing at the new Solr server
- [ ] Build a new jobs server, pointing at the new Solr server
- [ ] Deploy master branch to all servers
- [ ] On the _new_ jobs server, manually ssh in and run reindex so that the new Solr server has a full index
- [ ] Check with staff if any current ingests are being done, alert them to the change and make sure they are not happening.
- [ ] Switch the Elastic IP address over to the new web server
- [ ] Delete the old web server.
- [ ] Check that the old jobs server has no remaining activity and delete it once any running tasks are done.
- [ ] Commit changes on server addresses to Ansible.
