### ISSUE TITLE
Related URL -- missing on public work view

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#329]
If I compare the metadata edit view and public view of https://kithe.sciencehistory.org/admin/works/gsu1aw0/
I note that the related URL, "Sad DPLA Pin", is not shown on the public view.
This could be any of: a missing feature; a bug; or me not understanding the rules for related URLs. But need to investigate a bit further.

**Comment by jrochkind** [comment]
That does seem like a bug!

**Comment by jrochkind** [comment]
Oh no, it's not a bug. It's because if a related URL matches `digital.sciencehistory.org`, it's judged to be intended for "related item" display. So the software takes the id out of the end of the URL, and  tries to look up that object in our database, and use what it finds to fill out "related items" section. 

However, in this case the related URL is: https://digital.sciencehistory.org/works/2n49t2512

And that object is marked `private` (at least in kithe.sciencehistory.org), so can't be included in 'related items', cause only public items are shown in our front-end UI. 

This is a fairly hacky feature. But it is currently working as intended.
