### ISSUE TITLE
More staff search filter options

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#342]
After discussion, changed ticket to:

Staff Work search needs filtering options:

* published/not
* department
* genre
* format
----
old: 

This is so [embargoed content ](https://digital.sciencehistory.org/catalog?f%5Bsubject_sim%5D%5B%5D=Nobel+Prize+winners&f%5Bvisibility_ssi%5D%5B%5D=restricted)can be separated from staff-only content. Can visibility faceting on the back end be included so staff can view staff-only and private works (let me know if that should be a separate GitHub ticket)?  Thanks!

**Comment by jrochkind** [comment]
Huh, it is news to me that we have "embargoed" content. My understanding was that we were only ingesting materials meant to be public as soon as they were finished, and the only reason they would not be public is that they were not finished yet. 

Has this situation changed or is my understanding incorrect?  I'd like to make sure I understand the overall picture of the use cases and workflows for the app, to make sure we're meeting them in a holistic way, not just adding individual feature workarounds.   At present, in the new app there is no notion of individual staff accounts 'owning' a record, so I'm not sure what the difference between 'private' and 'staff-only' status would be, either way it would be visible only by staff and by all staff. 

Right now, as we have discussed previously, _only_ public content is in the "front-end search" you are linking to above. There's no non-public content there at all. So it's actually a mistake that it gives you a facet for public/private -- you'll never get any hits on private or otherwise non-public content.  This is _unlike_ chf_sufia. 

In my memory, we all agreed to start out this way, and see if staff needs for non-public content could be met with the staff interface. But maybe I am misremembering, or maybe you've learned more about what you need now that we've "started out" that way?

I think we'll need to discuss this on the phone to get to the bottom of our mismatch in shared understanding here.

**Comment by jrochkind** [comment]
> Can visibility faceting on the back end be included so staff can view staff-only and private works (let me know if that should be a separate GitHub ticket)

Right now we have "published status" which can be "published" or "not". This is per previous conversation, although it can be changed. 

But we can add "published status" filtering on the staff back-end, yes! Yes, please make a separate ticket for that. If there are other things you know you need to filter on the staff back-end (department? Genre?), or if you'd like to discuss it, let me know!

**Comment by yonyitz** [comment]
Thanks for your feedback, @jrochkind.  I emailed Hillary with a link to this ticket in case she wants to chime in here or we can discuss during our meeting this afternoon.  To be continued!  In the meantime, I'll make a ticket for published status filtering and will think as to whether other filtering options would be helpful. Is it too onerous to replicate the filtering that currently exists on the front end?  If not, that would be ideal.  If it is difficult, I can give what fields are useful further thought.

**Comment by jrochkind** [comment]
If we actually want to "replicate" the front-end filtering -- I would suggest we should just allow non-published content in the front-end, so you can use the front-end. 

Right now, the way the back-end is implemented, we can't do true "faceting" -- this means the UI where we show the list of values with the number of results for each value. 
![Screenshot 2019-09-09 11 01 43](https://user-images.githubusercontent.com/149304/64542252-3b93bd00-d2f1-11e9-8f72-8d4cdc7ee306.png)

What we can do is support a "limit" where you just choose from a select menu what you want to limit for. This is amenable to fields where we have a limited number of possible values (like department or genre) -- because we can show you all possible values and ask which you want to limit to -- but not fields where the values are hugely numerous like "Subject". 

If you actually need true "facetting", or need to limit on fields like "subject", then we will probably need a different implementation on the staff search -- or just to allow logged in users to see non-public things on the front-end search, as they could in chf_sufia. We decided to _start_ by not doing this, but we can change our minds. 

We can talk about this more face-to-face/phone/video conf.

**Comment by HKativa** [comment]
As discussed at the tech check-in on 9/9/2019: there was a misunderstanding about 11 archival records in current app whose visibility status was set to "private" (see original comment above re embargoed content). These records were not embargoed, but rather unpublished by Patrick Shea, who no longer wanted them in the repository. Per follow-up with Patrick on 9/10/2019, @yonyitz deleted these records from repository. 

Visibility statuses in use in current app are "public," "your institution," and "private." "Private" is primarily used for dummy test records and all other works are set to "your institution" upon ingest. Visibility status is changed to "public" once cataloging and QA are complete. As discussed at tech check-in, visibility status in new app will be limited to "published" and "private," with ability to sort between published/not in staff view.

**Comment by jrochkind** [comment]
@yonyitz and @HKativa , a first try at providing some filtering options on the staff work search form is now live on https://staging.kithe.sciencehistory Looks like this:

![Screenshot 2019-09-11 17 07 24](https://user-images.githubusercontent.com/149304/64735553-bfe36d00-d4b6-11e9-9d8b-6d6eda86e5b0.png)

Feel free to comment on this ticket and/or re-open this ticket if questions, problems, concerns, this isn't helpful, etc..
