### ISSUE TITLE
Required fields to publish a record

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#372]
Please require the following fields before publishing a record (other than title and external ID, which are already required to save a record):

Date
Format
Genre
Department
Rights

Thanks!

**Comment by jrochkind** [comment]
Part of this would be also preparing a report of things already in the db that are invalid according to these rules. 

We might want to fix them before deploying the code to require published items to have those things, to avoid odd interactions.

**Comment by jrochkind** [comment]
There are a LOT of published items missing date. (I did do a couple spot checks confirming missing date in sufia too, does not appear to be a migration error). 

It's possible many/all of them should be marked "Undated"? Which is a possible thing to do, but these aren't marked Undated, they have no dates at all. We could write a simple script to change them all to Undated if we wanted. 

A few others missing genre, rights, or others. 

Here is the list. 

https://gist.github.com/jrochkind/9ab75d74b0b7042f7d0a956075611e5f

@HKativa @yonyitz would it make sense to fix these manually, at the same time we are putting code in to prevent you from publishing items without these in the future?

**Comment by yonyitz** [comment]
Thanks for this info, Jonathan.  The metadata guidelines state that undated can be used.  Not sure whether it has been in the past @HKativa .  I'm fine with fixing manually depending on what @HKativa  recommends!

**Comment by jrochkind** [comment]
we're going to hold off on the software change until the existing bad data is reviewed

**Comment by jrochkind** [comment]
Actually I might start dev'ing it now, even if we don't deploy it. 

The UI I am thinking of is -- if you hit the 'publish' button, and there are missing required fields, it will drop you into a Work Edit form, with a "Missing fields required to publish" message, and those fields highlighted. 

If an item is already published, and you're editing it, the fields will show up and validate same as existing universally required fields (title and external id). 

Hopefully that makes sense, please let me know if it does not! @yonyitz @HKativa

**Comment by jrochkind** [comment]
So as above, my original idea was if you try to publish a work that lacks required fields, it drops you to the work edit field, with an error message. 

But working on it, I realize now that when you publish a work it ALSO publishes all that work's children. If the work has work children that lack required fields to be published... the UI is not simple, best we can do is maybe let you know that? 

Or should it publish the children it _can_ and just leave some children un-published? I think that probably is too much of a risk of not noticing you haven't done what you intended to do and leaving some children unintentionally unpublished. 

But any thoughts on how this should be handled welcome @yonyitz @HKativa , otherwise I'll just keep trying to do what seems to make the most sense to me.

**Comment by HKativa** [comment]
@jrochkind thanks for the update. I agree that it's problematic for child works to be automatically published with the parent work and would greatly prefer the option to leave all children unpublished until a cataloger consciously decides to publish them. When publishing a parent work in Sufia, you were given the option to publish all associated works as well. Maybe we could implement something similar here?

**Comment by HKativa** [comment]
With regards to the list of published records missing dates 
(see https://gist.github.com/jrochkind/9ab75d74b0b7042f7d0a956075611e5f), let's go ahead with a script to mark them "undated." Researching these items and adding inferred dates will make for a nice intern project come January.

FYI, all the records missing genre terms have been resolved, with the exception of the records awaiting the addition of the new "specimens" genre term (see issue #536). Once that term is added, we'll update the records and genre should be good to go.

**Comment by jrochkind** [comment]
Hi, I did not mean to suggest that it was probelmatic for child works to be automatically published with the parent work -- although if it is, we can fix that, it's sort of unrelated to this issue. What was relevant for this issue was when a child work did not _validate_ under the new rules for publication, and how to handle that in the UI. 

in my memory I checked with y'all and said "When you get that 'Do you want to change permissions on child works notification' in chf_sufia, do you EVER click 'no'?"  -- and learned no, staff universally chose "Yes, edit permissions on child work". So to add the question seemed like an inefficient annoyance into your workflow, it would be quicker just to do what you always wanted to do anyway, without making you do an extra click. 

If I am misremembering, misunderstood, or if understanding/analysis/needs have changed, we can certainly change the UI. We could make it very similar to  chf_sufia -- where when you click "publish" (or unpublish) you have to stop at a new screen asking you if you want the action to apply to child works. Or there may be a preferable UI that would be less inconvenient, like an initial menu with both options one way or another (or even a checkbox next to 'publish' button for 'also apply to all children). 

I am not sure if contained _assets_ are going to be treated differently than "child works" -- I can't think of a use case for publishing a work _without_ it's contained assets, it seems to me that would probably be a mistake?

I think it needs more discussion and consideration as to what kind of UI is needed, if the present UI is not acceptable. I think it's distinct from this ticket, please feel free to open another one -- it's okay and probably preferable if such a ticket just start to explain the problem/needs instead of assume a particular UI solution, to begin with.

**Comment by eddierubeiz** [comment]
The "Specimens" genre term is available in production. :)

**Comment by jrochkind** [comment]
> With regards to the list of published records missing dates
(see https://gist.github.com/jrochkind/9ab75d74b0b7042f7d0a956075611e5f), let's go ahead with a script to mark them "undated." Researching these items and adding inferred dates will make for a nice intern project come January.

OK, just confirming, after that script is run you won't be able to tell the difference between items that are already as of now marked "Undated" (due to an intentional choice), and items that as of right now had no date value chosen (so it's not entirely clear if they were consciously chosen or not). 

Not sure if you have corrected the other missing values in published works yet, or want to do so before deploying new data validation requirements for published records?

**Comment by yonyitz** [comment]
I added the "Specimens" genre term to the relevant records per a list @HKativa supplied me with so all records should now have genre terms!

**Comment by eddierubeiz** [comment]
Isn't everything a specimen, really?

**Comment by eddierubeiz** [comment]
;)

**Comment by jrochkind** [comment]
@eddierubeiz This week please bulk updates _published_ Works missing dates to instead be recorded as “Undated” value

**Comment by eddierubeiz** [comment]
I'm thinking along the lines of:

```
def items_needing_to_be_changed()
  Work.
    where("jsonb_array_length ( json_attributes -> 'date_of_work' ) = 0").
    where(published:true)
end

puts items_needing_to_be_changed().count

Kithe.indexable_settings.disable_callbacks = true

Work.transaction do
  items_needing_to_be_changed().find_each do |work|
    work.date_of_work = Work::DateOfWork.new({"start_qualifier"=>"undated"})
    work.save!
  end
end

puts "All done!"

puts items_needing_to_be_changed().count
```

**Comment by jrochkind** [comment]
@eddierubeiz 

Hmm, array length== 0… it could also not have the key there at all, or  have the key there with a javascript null/undefined value. So that might not catch all of them. 

This shows some of the pitfalls of json!

For this one-time thing, I think I'd probably just fetch every Work into memory with `Work.find_each do |work|`, and check em in ruby -- `Work.date_of_work.blank?`  (Rails `blank?` will return true for either nil or empty array). 

I think it's good enough, should still only take a few seconds I think.

**Comment by eddierubeiz** [comment]
Good call! Will amend.

**Comment by eddierubeiz** [comment]
```File Edit Options Buffers Tools Ruby Help
Kithe.indexable_settings.disable_callbacks = true
i = 0
Work.transaction do
  Work.where(published:true).find_each do |work|
    next unless work.date_of_work.blank?
    puts work.friendlier_id
    work.date_of_work = Work::DateOfWork.new({"start_qualifier"=>"undated"})
    work.save!(validate: false)
  end
end

puts "All done! Fixed #{i} works"```

**Comment by eddierubeiz** [comment]
Ran `fix_dates.rb` in production without incident. 170 works had "undated" added. The output list the `friendlier_id`s of works changed.
[fix_dates.rb](https://github.com/sciencehistory/scihist_digicoll/files/3945361/fix_dates.rb.txt)
[out.txt](https://github.com/sciencehistory/scihist_digicoll/files/3945363/out.txt)

**Comment by eddierubeiz** [comment]
Looks good. You should be able to deploy the validation code to production now.
