### ISSUE TITLE
Add support for multiple admin notes

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#400]
To accommodate items like https://digital.sciencehistory.org/works/4f16c291q , which has three.
The import will have to change too, as will the audit and the upcoming Fedora check.

**Comment by jrochkind** [comment]
Should we actually add support for multiple admin notes, or just squish all the admin notes into one field on import?

For squishing:
   * While attr_json lets us make a field mutiple, we don't have UI yet for a repeatable multi-line text entry, only for repeatable single-line
   * I think stakeholders agreed one admin note field was fine, you can edit it and add multiple paragraphs. (I recall checking this when implementing)

For actual multiple:
   * While the import is straightforward (just join multiples with `\n\n` or something), makes auditing somewhat more complex. (Although maybe not THAT much more complex if we join with a special string like `\n\n--imported note separator\n\n` or something. Might be less work than actually making them multiple if we don't really need it).

**Comment by HKativa** [comment]
I don't recall the stakeholder conversation referenced above, but I'm happy to this discuss now. In practice, the content of admin notes tend to be distinct and entered by different users (this record is a better example of that practice than the Beckman one above: https://digital.sciencehistory.org/works/bk128b060). This practice doesn't necessarily prevent us from squishing separate notes together, but is something to keep in mind.

One question re squishing admin notes together into one field: would this affect our ability to parse out or run a report showing all notes added by a single user or notes with particular content, for example "Wikipedia" or "Beckman Legacy Project." We've discussed such scenarios in the past and I wonder if it has any bearing here.

**Comment by jrochkind** [comment]
We can definitely add back multiple admin notes, will just take some development -- of the UI for adding/editing/removing admin notes. Since it affects data import, we'd want to prioritize that asap if we wanted to do it, so we can get the notes imported from chf_sufia before go-live. We're definitely noticing this a little bit close to the deadline, so should decide what to do with it asap. 

> would this affect our ability to parse out or run a report showing all notes added by a single user

Neither chf_sufia nor the new app keeps track of what user added an 'admin note'. So there's no way to show all notes by a given user in either app, including legacy chf_sufia app.

**Comment by HKativa** [comment]
Thanks for the info - a point of clarification: who added the admin note is part of the metadata of the note itself, for example "Released on Wikipedia as "File:WHAT HAS ROSIE THE RIVETER TO DO WITH Fresh Strawberries for Thanksgiving tb09j594t.tiff" (M. Mark-Ockerbloom, 09/27/2019)." So that's what I was referring to in terms of tracking what user added an admin note.

**Comment by jrochkind** [comment]
Ended up tracking this work on #414 instead.
