### ISSUE TITLE
Import bug: some multi-value metadata is not ending up in the right order.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#43]
Including series arrangement and extent.

**Comment by eddierubeiz** [comment]
Hm. This may not be fixable if these properties are not stored in order within Fedora itself.

**Comment by jrochkind** [comment]
Yeah, I'm not sure if it's consistently ordered in fedora itself. 

Actually, in the distant past when we talked about this, I believe the stakeholder response was that they didn't _expect_ these to be ordered in any particular way, metadata staff was not entering them in any particular desired order, and it was okay. Some fields we alphabetize _on display_ in order to have a predictable order which is forced alphabetical. 

Let me see if I can find an existing ticket recording that past discussion...

Here's one about alphabetizing on display: https://github.com/sciencehistory/chf-sufia/issues/247 and another where we fixed that for a certain field https://github.com/sciencehistory/chf-sufia/issues/527

Here's one from 2016 suggesting it it resolved predictable ordering (but I distinctly remember we later knew it did _not_, which is why we did 247 above): https://github.com/sciencehistory/chf-sufia/issues/240

I can't find one with discussion where we acknowledged there wasn't a predictable return order from fedora and accepted that, it may not have been captured in a GH issue, but I remember it!

**Comment by sanfordd** [comment]
I recall that this was also an issue and we had a discussion that it was not. The only people who had any impression ordering might matter was the Museum with regards to the materials an object was made of but in the end we decided that was not needed since PastPerfect allows them to keep the materials in an order useful for them.

**Comment by jrochkind** [comment]
The good(?) news is the new system _will_ keep them in a consistent order in the future. Just might change in migration (since it could change in old system from time to time on it's own too).

**Comment by eddierubeiz** [comment]
Got it. Thanks for the info above. We can sort the metadata during the import, or anytime after it. I'm closing this for now.
