### ISSUE TITLE
Related URL not showing up as Related Items with thumbnail

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#447]
When inputting url into "Related Url" field, does not show up under "Related Items" header with thumbnail as seen below (right side):

![image](https://user-images.githubusercontent.com/30178818/67871583-fc226980-fb06-11e9-8984-e420dde77f85.png)

**Comment by jrochkind** [comment]
Can you also paste in the URL you entered as a "related URL"?

**Comment by yonyitz** [comment]
Staging example missing thumbnail: https://staging-digital.sciencehistory.org/works/go35vv0

Current example with thumbnail (how it should appear): https://digital.sciencehistory.org/works/p2676w44w

**Comment by yonyitz** [comment]
This is the related URL I attempted to use: https://staging-digital.sciencehistory.org/works/9wmo716

**Comment by jrochkind** [comment]
OK, it actualy only recognizes URL as "related items" if you use the "permanent" URL beginning with `digital.sciencehistory.org`, not `staging-digital.sciencehistory.org`. 

This is in part because this "related item" metadata is "permanent", and we shouldn't enter staging URLs in there. And that when we copy production data (that uses the "permanent" URL) to staging -- it still needs to recognize `digital.sciencehistory.org` as a "related item". 

The "related item" feature based on "related URLs" is definitely kind of hacky, but it's what we had, in both old app and new app. 

Can you switch the URL to `https://digital.sciencehistory.org/...` and see if it works as expected?
