### ISSUE TITLE
Metadata in "Medium" field should be hyperlinked

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#460]
Currently, on Sufia, metadata in the "Medium" field is hyperlinked (see work v692t628j for an example), but not on Kithe.

**Comment by eddierubeiz** [comment]
It's faceted in the public view (see https://kithe.sciencehistory.org/works/v692t628j ).

**Comment by HKativa** [comment]
Huh, @eddierubeiz it doesn't appear faceted for me (I'm using Google Chrome). If you'd like to swing by and take a look, let me know.

**Comment by eddierubeiz** [comment]
Reproduced! If you're logged in, the URLS are there. Logged out, they aren't.

**Comment by jrochkind** [comment]
The medium facet is only present (in the sidebar, as a limit you can use in searches) if you are logged in, in _old_ chf_sufia app. This was a concious decision. 

Perhaps it was a bug *in the old app* to make it hyperlinked when it was not offered as a search limit? If we meant to offer it only to logged in users? Does it make any sense to have a limit for public users that is accessible as a hyperlink on an individual record, but *not* as a sidebar limit?

If not, then possibly the new app is behaving correclty, and the bug is in the old app?

**Comment by HKativa** [comment]
Thanks to the added perspective from Jonathan, I've decided that it is unnecessary for "Medium" to be available as a facet for non-logged in uses. Hence, I'm closing this ticket!
