### ISSUE TITLE
Import report file & status bar.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#48]
Instead of printing to stdout, the import should write info and debug messages to a report file with a timestamp in its filename.
This frees up stdout for a status bar, which should be re-added if it's currently commented out.

**Comment by jrochkind** [comment]
You can use stdout (or it might actually be stderr that's currently being used) for logging with the project bar, you just need to use the [progress bar log method](https://github.com/jfelchner/ruby-progressbar/wiki/Logging) -- it will output the lines you log above the progress bar, without messing up display of the progress bar. 

I'm not sure if a separate log file is necessary/desirable. To start out, I'd say do whatever is quickest. 

Just to record, one of the main things we want logged first is a list of any records that could not be imported due to validation errors, along with necessary context (record id, the 'bad' data element contents). So we can use this as information to decide what to do about it -- relax validation, fix data in v1 app, etc.

**Comment by eddierubeiz** [comment]
This is great. By the way, a related item is https://github.com/sciencehistory/scihist_digicoll/issues/42

**Comment by eddierubeiz** [comment]
OK -- logging to stdout via the progress bar log method (thanks!) and printing out basic list of records with problems and the type of problem.

**Comment by jrochkind** [comment]
Want to put the list of records/problems here when you got em? Or elsewhere? I'm curious to see em.

**Comment by eddierubeiz** [comment]
Sure, here you go. This gives you a good idea of what's going on: [import_stdout.txt](https://github.com/sciencehistory/scihist_digicoll/files/2881860/import_stdout.txt)

**Comment by jrochkind** [comment]
Great, can you have the actual field contents output too? Instead of just `GenericWork z603qx61q: ERROR: bad date`, actually output the contents of the date field in some way. I realize it's more complicated than just outputting a string, because it's not a string. 

But I think having a report that shows the data is what we need to decide next steps. Ideally maybe separated into categories, all the bad dates, all the bad inscriptions, etc. But one step at a time.

**Comment by jrochkind** [comment]
perhaps we want a separate ticket, "report on data that doens't validate"

**Comment by eddierubeiz** [comment]
Yup! For now, I've been putting my detailed reporting into a separate "audit" rake task:
https://github.com/sciencehistory/scihist_digicoll/issues/42
Can absolutely revisit the import reporting to make it more detailed, but I want to finish the audit code first.

**Comment by jrochkind** [comment]
sounds great

**Comment by jrochkind** [comment]
I _think_ it would be tricky to include the  report on things that did not import due to validation errors can't be included in the "audit" rake task, at that point all you know is a thing is missing, not why. You'd have to try saving it again to confirm it was a validation error, I think. So makes sense to do that one on the import pass I think.

**Comment by eddierubeiz** [comment]
Good point!

**Comment by eddierubeiz** [comment]
Done, and the news is good. As surmised, the errors follow a nice Pareto distribution.

Over 90% of the date import problems are because`{"start_qualifier"=>"Undated"}` doesn't validate.

Aside from that, we have a manageable number (< 50)  of date typos ...
```
"1978-11-6"

"1935-06-023"

"1941 "

"193-01-08"

{"start"=>"1930s", "start_qualifier"=>"decade"}

instead of

{"start"=>"1930", "start_qualifier"=>"decade"}
```
... and a dozen or so trivial outliers.

[Full results](https://github.com/sciencehistory/scihist_digicoll/files/2885600/verbose_import_report.txt) attached.
