### ISSUE TITLE
Adding new file(s) to published work requires manual change to file visibility

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#557]
Scenario: You add new file(s) to an existing published (public) record. Upon saving the record, the new files are added, but their visibility is set to "private." Making the new files public requires manual change to files' visibility setting under "Members" tab. Alternately, unpublishing and then republishing the record will make all attached files public. 

This behavior differs from Sufia, where new files added to an existing published record were made public upon saving. Ideally, new files(s) should inherit the visibility of the work to which they're added, "private" for unpublished works and "public" for published works.

**Comment by jrochkind** [comment]
Confirmed just for my own confidence that this is indeed how chf_sufia appeared to work.

**Comment by jrochkind** [comment]
Confirmed just for my own confidence that this is indeed how chf_sufia appeared to work. 

When adding new Assets/files to a Work, they should take the publication/visibility status of the parent work they are being attached to. 

I assume the same should be true of adding a child work? Although I haven't tested that in chf_sufia, I will make that so too for consistency.

**Comment by jrochkind** [comment]
There's currently no controller-level specs (automated test) for these things; only feature/system specs. 

Rather than adding another feature/system spec, I will spend some time adding controller test for adding children, so it can cover this case too. In the case of assets, may require figuring out how to mock/provide bytestreams to the controller in a test.

**Comment by jrochkind** [comment]
Also, we noted in discussion that one thing this opens us up to:

In this app (*possibly* unlike chf_sufia), the `Asset` object is immediately persisted, before the file is actually fully ingested, and before derivatives are created. It will also, after this change, be immediately published in some cases. 

So it could be published and displayed, with a missing image (or other original/derivative) for a temporary period, after this change. 

There are potentially ways we could try to deal with this, but in discussion @HKativa decided this wasn't worth trying to deal with for now; it's a relatively rare case that we add children to an already published work anyway, this problem may have existed we think in chf_sufia already, and it's not a disaster if it temporarily displays with a broken image etc. 

We can always revisit later.

**Comment by jrochkind** [comment]
Actually I can't figure out how this applied to child works (rather than assets) in chf-sufia (I can't even figure out how people actually added child works in chf_sufia). 

So won't implement "start with publication status of parent" for child works before we discuss it further. We should confirm what we want there before closing this ticket. @HKativa

**Comment by jrochkind** [comment]
Decided child works are fine as is, so @eddierubeiz this is is ready for review and merge and deploy!
