### ISSUE TITLE
If an ActiveJob job fails, rerun it automatically.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#607]
@jrochkind  notes:

> At some point we should probably configure “run any job that fails a second time automatically” for our bg jobs. I think that is possible to do generically. And all our jobs should be idempotent now, so.

**Comment by jrochkind** [comment]
I think this one would actually be a nice one to take care of on further reflection, so I took the liberty of moving this to the top of backlog, to remind us to check in on it again and consider doing it, when we have time.

**Comment by jrochkind** [comment]
There is retry func built into ActiveJob.  Generically, it allows you to do things like "retry in 5 minutes, the second time 20 minutes" etc. 

However, basic Resque that we're using doens't support "schedule in advance".  So we can only do "retry immediately". 

Still, a "retry immediately, only once" would be sufficient to resolve a number of problems -- including "jobs got interupted because of worker dyno restart/shutdown".  And is probably fairly straightforward and worth doing. 

I might like to propose this as moving clsoer to the top of our lists. 

(See also #1245 for switching to a non-resque backend that supports future-scheduled jobs)

**Comment by jrochkind** [comment]
Hm, I knew that resque by default didn't support future-scheduling jobs, but I thought we could use ActiveJob `retry_on` anyway, telling it `wait: 0`, no future scheduling. But even so we get an error:

`Aug 10 13:05:24 app/worker.1 ERROR: [ActiveJob] Failed enqueuing TestFailureJob to Resque(default): NotImplementedError (To be able to schedule jobs with Resque you need the resque-scheduler gem. Please add it to your Gemfile and run bundle install)`

Still messing with things, but this may mean our current stack wont' allow ActiveJob retry. :(  I don't really want to add resque-scheduler into the mix, although that would be an option.

**Comment by jrochkind** [comment]
We could work around this several ways, monkey-patching something, or writing our own thing in terms of `rescue_from` instead of `retry_on`. 

(The definition of retry_on is not too complicated in terms of rescue_from.... https://github.com/rails/rails/blob/94ccd5410d84313be48dc949fdf1d185c98a9d7f/activejob/lib/active_job/exceptions.rb#L58)

I'm not sure if it's worth it.
