### ISSUE TITLE
Increase Netdata CPU Alarm to 1 hour

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#616]
Even raising things to 30 minutes doesn't quite seem to have covered our occasional CPU usage from bulk uploads. Change the alarm to only trigger after an hour should handle most of those cases.

**Comment by jrochkind** [comment]
Would we want an alarm when we're out of burst credits?  

Which seems to be the actual potentially "things mat stop working well for a while"  condition we might want to be aware of-- although 100% CPU can warn you it's *coming*. 

Is there any non-horribly-crazy way to get an alarm on being out of burst credits?

**Comment by sanfordd** [comment]
The 100% CPU alarm is, in a more general context, meant to be a sign that a task is usually active, even if we're on a non-burst credit instance. Even if we're not out of credits I think there's a case for wanting to know when a server is being taxed. 

The burst credit issue could be solved by using the AWS SDK for python and writing a custom plugin. The simpler way would be to use AWS's CloudWatch tool and set it to alert us when the credit balance falls below some reasonable percent of credits. That's one of the built in options and takes minutes to set up.

**Comment by jrochkind** [comment]
OK, we might want both, but being out of burst credits seems to be to a condition we'd want to be alerted about. I think? What do you think? @eddierubeiz ?

**Comment by jrochkind** [comment]
The trick in general of course is that we've discovered on jobs server being at 100% CPU does *not* mean "unusually active". 

Which is not a bad thing -- if there were jobs waiting in the queue but the CPU *wasn't* at 100%, it woudl mean we weren't taking maximum advantage of our available CPU. That it is at 100% means we are. Which means there's nothing unusual about it. 

Since we expect 100% CPU utilization from jobs, I'm not sure it's an unusual/alarmable case even if it goes on for an hour. It just means there's a lot of ingesting going on. we could determine on average how many files waiting in queue to ingest resulted in how many minutes of 100% CPU utilization, so minutes-of-100% roughly corresponds to "number of files waiting to ingest". Is there a certain number of files waiting to ingest we'd want to be alarmed about?  It's not obvious to me?

Note, this is *entirely differnet* for a web machine and a jobs machine. I don't know if you are currently able to configure them differently or doing so? 30 minutes of 100% cpu on a web machine probably does mean something is unusual and possibly wrong and that end-users are suffering a service degradation. 100% cpu on jobs might not though.

**Comment by sanfordd** [comment]
I was about to suggest we look at different alarms for jobs, it's clearly handling a different level of activity than other machines.

**Comment by sanfordd** [comment]
Right now we have a central server called monitor which collects statistics and runs alarms for all of our individual servers. Unfortunately setting a central alarm server which allows your alarms to apply to servers in different groups hasn't been implemented yet.

We can switch to running netdata alarms locally on each server, but that puts a bit more stress on the individual server(s) to handle the alarms and data retention. 
The other option is to simply set less aggressive alarms globally with the knowledge that it will mean other servers could take longer to alert us about any issues.

An unrelated task to add a burst credit CPU alert via AWS CloudWatch seems like a good option regardless of any other changes.
