### ISSUE TITLE
Encryption of R&R patron data

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#621]
Just putting this on our radar for the next tech check-in on February 10th.

**Comment by jrochkind** [comment]
Thanks! i'd like tech team (@eddierubeiz, me, and possibly @sanfordd)  to try and write up our list of pros/cons/considerations before then.

I'd like us when doing that to focus on what we've currently identified as most likely solution if we *do* want/need encryption:  Application-level encryption of individual db columns. 

While there are other approaches, its confusing to consider everything at once, so by starting with that, we can get a sense of things and determine if we'd want to consider other approaches too. 

We can perhaps list pros/cons/considerations here, maybe in a comment we all edit, rather than a whole string of comments. 

For the tech people, a good article for some background is: https://ankane.org/sensitive-data-rails

Some of the available Rails solutions for app-level per-column encryption include (there may be others):

* https://github.com/attr-encrypted/attr_encrypted
* https://github.com/ankane/lockbox
* https://github.com/spikex/strongbox

**Comment by sanfordd** [comment]
Sounds good, let me throw out some quick comments (that others are free to edit).

We have a few potential targets for encryption
1. Some PII exists (email address) which the linked article points out is a medium weight type of information. That's probably the minimum data we'd want to secure. 

2. Distinct from PII, there's also broader librarianship concerns about patron privacy which would extend to non-PII but information about the data used such as resource titles or object IDs that while not PII we may want to keep encrypted.

**Comment by jrochkind** [comment]
Hm, I'm kind of wanting to reconsider using postgres-level per-column encryption again though. Seems potentially less opportunity for us to mess it up (mess up security-wise, mess up performance, just buggy/lose data, etc), with potentially the same security story. 

Postgres docs say:

> The pgcrypto module allows certain fields to be stored encrypted. This is useful if only some of the data is sensitive. The client supplies the decryption key and the data is decrypted on the server and then sent to the client.
https://www.postgresql.org/docs/current/encryption-options.html

But I'm having trouble finding docs/examples on how you do that.

**Comment by sanfordd** [comment]
There are a few risks with this, specifically in regards to #569 since the encryption data becomes part of the postgres log (https://dba.stackexchange.com/questions/24370/how-to-use-aes-encryption-in-postgresql)

It might still be better, but we'll want to treat our postgres logs more carefully as a result.

**Comment by eddierubeiz** [comment]
Adding this article (@jrochkind found it) so we can keep all our reading material in the same place -- https://security.stackexchange.com/questions/213146/data-encryption-by-application-vs-data-encryption-in-database

**Comment by jrochkind** [comment]
So, the proposal right now is to use application-level individual-column encryption to encrypt just the "sensitive" columns in the R&R table. 

If the code is correct and bug-free, this would mean that an "attacker" could not tell what was in those columns without having the encryption key. 

However, our application needs the encryption key so the values can be displayed, so it can be a challenge to make sure an attacker who had access to the data would not also have access to the key. 

A basic approach would minimally protect the data from an attacker who only had access to the database server (or backups) and not any of our 'application servers'; but if our 'application servers' were compromised, the attacker would get the key too. There are more complex approaches using separate "secrets storage" to try to keep the secret key off the disk in our application servers too; this would require a more sophisticated attack to get the secret key even with access to application servers. 

## Considerations

* Encrypted data can't be easily *searched*.  Although there are approaches to allow some forms of searching securely, they would take additional work (and may be easier or harder depending on implementation choices made in original encryption, which may not be obvious in original implementation). 

* We can easily get it wrong
  * In a way that effects security, so it's not as secure as we thought it was. Encryption is easy to get wrong. 
   * In a way that effects implementation, so we can't do things we realize we need to do. Things like searching, or adminsitrative things like the ability to *change* the secret key (if it becomes compromised, or regularly as a good security practice) without data loss or downtime. That's an example, there can be other things we won't have thought of in advance,. 
  * So it's not just initial implementation, this will definitely increase ongoing maintenance costs to *some* extent, in predictably hard to predict ways. 

* We should try to pick a Rails-compatible library for this -- rather than reinvent the wheel ourselves -- and find one that seems to have been written by someone who knows what they are doing (more experience than us), with regard to good security practices and implementation considerations. 

* I can't find any other LAM community who has done this!
  * Which doesn't mean we shouldn't! Some people say they think they probably ought to, but haven't been able to find the time for it or are intimidated by it and things they could get wrong. If we did it, we could write it up as a service to community. 
  * But is the sensitivity of our data really worth the non-trivial extra work we are undertaking? Email addresses are pretty easy to find; then we additionally have R&R requests made, which yes are confidential patron info, but, how sensitive really? (Possibly very!)

**Comment by jrochkind** [comment]
We decided to do this, I will change the title and assign Eddie. 

I'd like to suggest "writing it up to share with community" be an explicit part of this ticket; that takes time to do, I'd like to us to decide to take the time.

**Comment by jrochkind** [comment]
https://bibwild.wordpress.com/2020/03/05/encrypting-patron-data-in-rails-why-and-how/
