### ISSUE TITLE
False alarm on the fixity check page 8 days after metadata dashes

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#633]
a) Every night, we check a certain number of files' fixity. That number is exactly 1/7 of the total number of files in the collection **as of tonight**.

b) But we also add files every day, thus increasing the total from night to night.

c) This means that our *effective* check rate is actually *slightly* less than 1/7th of the total collection every night.

d) If a large number of items were added to the collection during the past week, it's normal to see a number of assets whose most recent fixity check is 8 days old instead of 7.

e) But we count an asset as having a "stale" fixity check if it hasn't been checked for 7 days.

f) This results in a warning on the fixity check report page that causes needless alarm.

g) As long as the date listed under ```Fully-ingested Asset with oldest most-recent fixity check``` date is a week ago, there's nothing to worry about.

**Comment by jrochkind** [comment]
This makes sense, nice analysis, thanks @eddierubeiz .

I guess even 8 days *could* still result in an alarm, if a whole lot of files were added in a given 7 day period. (We'd have to do math to say how many, I'm not certain). But would presumably significantly lessen the chances of alarm. 

We could also change it to 1/6th instead of 1/7th to try to stick to our "7 day limit". (Although it would still be possible to be exceeded of course). 

The important observation is that our current algorithm actually *doesn't* guarantee every file will be checked every 7 days. It depends on the rate of new flies? My head is swimming a bit. Not sure if we want to try and change the algorithm to actually guarantee some X days. 

We could additionally and/or alternatively also provide a button for "check all files with stale checks", that would just make bg jobs for eg in this case the 22 files.

**Comment by sanfordd** [comment]
Adding a quick note, after we ran a staging sync (which as a reminder is similar to a backup restore) we also got a notification at the end of 7 days with 2 files not being checked in time. It's possible a backup restore or sync will cause have a similar issue. It's not a major concern but worth documenting here in case someone wants to know why they're seeing it.

**Comment by eddierubeiz** [comment]
Closing this ticket. We've made changes to the fixity check routine, and this issue is now stale.
