### ISSUE TITLE
OHMS Front End: Footnotes

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#685]
Most (we think) transcripts in the collection contain footnotes or endnotes. COH uses the notes to provide: full citations for published works under discussion; historical or other explanatory context if we felt it was helpful/necessary to do so; full citations to oral histories in our collection with individuals mentioned during the interview. (This last is a more recent addition to our footnoting practice).

The OHMS standard viewer supports linked endnotes in transcripts, with relatively minor formatting work required. The subject for discussion is whether we want our custom viewer to also offer this feature.

EXAMPLES:
https://ohms.uky.edu/preview/?id=89281 (Hanford, see footnote in transcript, eg around timecode 00:40:00)
https://ohms.uky.edu/preview/?id=89262
https://ohms.uky.edu/preview/?id=89282 (renfrew has the most yet, starting at around 19:30)

**Comment by jrochkind** [comment]
Lee also mentioned she suspects most of the existing PDF transcripts have footnotes, it is a commonly used thing in our existing PDF transcripts. 

I would say this feature is probably a few days to a week-ish to add, or a few days more, since it will involve some Javascript stuff which isn't always our strong point.
