### ISSUE TITLE
New dropdown label for 'Project' field

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#697]
Label: "Life Sciences Foundation" - alphabetical order like existing labels, so after "Imagining Philadelphia's Energy Futures"

**Comment by yonyitz** [comment]
Closing since Lee Berry confirmed projects should only be ones listed in top project section of this webpage: https://oh.sciencehistory.org/oral-histories/projects

**Comment by HKativa** [comment]
UPDATE: conversation with @lsberry16 in March 2021 during ingest of limited-access oral histories determined that "Life Sciences Foundation" is present on oral histories projects webpage (https://oh.sciencehistory.org/oral-histories/projects) and SHOULD be included on Projects list in Digital Collections. Accordingly, please add Label: "Life Sciences Foundation" - alphabetical order like existing labels, so after "Imagining Philadelphia's Energy Futures"

**Comment by HKativa** [comment]
In addition, for purposes of documentation going forward, the following legacy project labels are not present on the oral histories projects webpage and SHOULD NOT be included on the Projects list in the Digital Collections:

Beckman Heritage Project
Biotechnology
Women in Chemistry

**Comment by jrochkind** [comment]
No problem!

This is fine here, but in the future for things like this, I would find it easier to manage if you opened up a new ticket. It makes sense to reopen a ticket when it turns out it wasn't actually finished compeltely, more work has to be done. 

But not when it's a brand new task that just happens to be similar to one we did before. It makes it more confusing to me and harder to keep track of what work we've done to reopen something we really did complete satisfactorily before.

**Comment by HKativa** [comment]
Noted. We actually have a second value to be added to the Project list so I'm going to close with ticket and open a new one for the two new values.
