### ISSUE TITLE
Hide "combined audio derivatives" button if there are zero published segments in an oral history

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#704]
Instead, show copy to the effect that:
* only published segments are incorporated into the combined audio derivatives, per our policy
* thus we have no segments from which to create said derivatives
* thus we're not showing the button.
This is related to #674 but is much simpler to implement.

**Comment by eddierubeiz** [comment]
This actually conflicts with #734 but I'll at least show an error message.

**Comment by jrochkind** [comment]
Not totally sure it does; I see a difference between refusing to show the button becasue the software thinks "this is not needed, you already have a derivative", and refusing to show the button because the software thinks "I am literally UNABLE to create the derivative, because there are no source files". 

But also not totally sure I see your point too. Do what you think is best for both UI and code simplicity/clarity!
