### ISSUE TITLE
(new tab for) View PDF of Transcript (Published Version) without navigating away from Downloads tab 

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#710]
The Downloads tab of the oral history viewer lets the user play or download audio files without navigating away from the page, and same for downloading the PDF, but viewing the PDF replaces the Downloads page with a PDF view page, so if the user wants to go back to the record of the oral history, they need to hit the back button. This appears to me to be unique in the Digital Collection--when you want to view a TIFF file, for example, a custom viewer slides up and lets you look at the image. It has a X button at the top right corner and you can click that to close the TIFF viewer and resume looking at the item record--no back button needed. On the COH microsite, we've chosen to have a new tab open to display the PDF file when a user clicks "View the Front Matter and Index," and I prefer that if it's not possible to mimic the behavior of the TIFF viewer for PDFs in the Digital Collection.

**Comment by jrochkind** [comment]
The PDFs in Digital Collections have opened in the same tab, since even before OHMS functionality. 

We may not have any other PDFs in Digital Collections that are not OH?  But if we did, they would work the same way. 

Images open in a little window-inside-a-window, but that isn't easily available for PDFs -- we let the browser display the PDF, so it takes over the entire browser window to do so.  So a "window inside window" isn't an option.  

So we can't actually mimic the TIFF viewer in that way.  Neither choice mimics the TIFF viewer, neither choice gives you a window-inside-window.  The TIFF viewer does not open a separate tab, everything happens in the same tab, so I'm not sure which one is "more like" the TIFF viewer. 

My understanding of the general policy for sciencehistory.org as a whole is to only open a new tab when going to an 'external' site.  While the boundaries of what 'external' means can be unclear (is going to the microsite from digital collections 'external'?) -- it seems clear that a PDF from digital collections is not 'external'. 

Are you thinking that users are confused by needing to use the browser 'back' button, or don't know how to do it?  But will be less confused by a separate tab opening?

In general, my worry with opening lots of new tabs is that this confuses users and leaves them with lots of tabs open in their browsers, which can be especially confusing on mobile. If you leave a link as 'default' opening in same tab -- a user can exersize their browser functionality to choose a new tab instead (for instance right-click on desktop, choose 'open in new tab'). But if you force open in new tab, there is no way for the user to 'undo' this, and they can end up with lots of tabs open.

**Comment by jrochkind** [comment]
Replaced by #986

**Comment by apinkney0696** [comment]
Reopening. Want a new tab or download for PDF transcripts.

**Comment by jrochkind** [comment]
@rachellane12 @archivistsarah 

Will have PDF links open PDF in a new tab. 

This will apply to "Front Matter" links eg https://digital.sciencehistory.org/works/ouqouy0 as well. I think that is desirable?

**Comment by rachellane12** [comment]
@jrochkind This applying for "Front Matter" links as well makes sense to me. @sarahschneiderSHI, do you agree?
