### ISSUE TITLE
More flexibility when (un)publishing a work and its assets

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#712]
Currently, publishing a work publishes all its assets, and un-publishing a work un-publishes all its assets.

This poses a problem when it comes to recreating combined audio derivatives, which 
a) can't be recreated when the work is published
b) only incorporate published assets.

Possible fixes:
* Easier way to publish all assets in a work without publishing the work itself.
* Prompt user, when un-publishing a work, whether to un-publish all assets as well.
* Allow the user to publish/un-publish assets directly from the asset list table, instead of only allowing it on the asset edit page.

**Comment by eddierubeiz** [comment]
OK -- talked to Nicole this morning and I would like to propose a simple fix.
**IF** a work is an oral history
**AND** it is unpublished
**AND** it has a bunch of audio segments. Let's say 12 of them.
**CURRENTLY** users do not have access to click the blue button that says "Generate combined audio derivatives".
**INSTEAD**, show the button.
**WHEN IT IS CLICKED**, prompt the user with the two following options:
**OPTION 1**: "Publish all 12 audio segments, and create audio derivatives from them. (The work will remain unpublished.)"
**OPTION 2**: "Cancel"

**Comment by eddierubeiz** [comment]
My *belief* is that the change above will solve a large number of the problems needed to solve #767.  My *hope* is it will solve all of them.

**Comment by jrochkind** [comment]
This is a clever solution. 

What about instead:

* A feature to "publish all audio members without publishing the work" *separately* from "combined audio derivatives"?  Or in addition?  Is this need really connected specifically to creating a combined audio derivative?  Or is it really a general feature to "publish all members" Right now, there is no convenient way to do that without publishing the work, but sounds like we have a need?  Maybe it would be useful generally?


* Separately, I'm not sure what feedback you get currently when the combined audio derivatives button doesn't show up -- is it just missing invisible with no reason to know why it's not there? If part of the point of this feature is to make taht less confusing -- would an on-screen explanation work better? Like a greyed out/inactive button, with the explanation "You can't create because there are no published audio members". 

* I am just trying to brainstorm to see if things can be kept *simpler* and more *general purpose*. Worried about continuing to add more complicated logic to deal with previous logic we added; can we simplify instead?  In general purpose ways? A generic feature "make all members published" (without publishing parent) seems potentially simpler than adding a UI choice form, with two logic paths, triggered by certain state, etc. (Although not clear how it applies to multi-level children. :( )

**Comment by eddierubeiz** [comment]
Good points. It's certainly reasonable to consider a) adding a controller (with a button to invoke it) that simply publishes all unpublished audio child assets, or b) adding a controller that publishes all descendants regardless of content type -- just not not the parent work. In either of these admittedly more elegant scenarios, after publishing, the user can come back and take the next step -- kick off the combined audio derivative job. Part of me really likes the idea of separating these two steps.

However, when you ask. "Is this need [to publish first-level audio child assets] really connected specifically to creating a combined audio derivative?" the answer is: "Yes, it really is". (The pattern of having to publish all direct audio children and *then* create the c. a. derivatives is a tedious and often-repeated procedure.) So, while slightly less elegant, I think my solution will be more convenient, if I understand the current workflow correctly. It's also (paradoxically) easier for the user to understand even though what's going on in the background is more complicated. We are basically *removing* an opportunity for the user to get confused and forget what they were doing.

Remember, when you publish the work, all its descendants are recursively published anyway. This mini-feature is just a shortcut that makes it easy to test the item, with audio, in production, without it being search-accessible to the public.

**Comment by eddierubeiz** [comment]
Oh -- by the way -- _"Separately, I'm not sure what feedback you get currently when the combined audio derivatives button doesn't show up -- is it just missing invisible with no reason to know why it's not there? If part of the point of this feature is to make taht less confusing -- would an on-screen explanation work better? Like a greyed out/inactive button, with the explanation "You can't create because there are no published audio members"._ That is currently the UI in production -- it's greyed out and there is helpful text. I'm proposing the *removal* of that friendly text and replacing it with an even friendlier button that ... just does what the text instructs you to do automatically.
