### ISSUE TITLE
Search facet toggle button on result pages (almost) invisible at low screen widths

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#719]
Start at  https://digital.sciencehistory.org/catalog
Narrow the screen to a narrow width.
The button used to show search facets is replaced by a white rectangle with no icon in it, for all practical purposes invisible to users.
There was probably an icon on the button that is no longer showing for whatever reason.

Mary Mark Ockerbloom noticed this -- thanks to her, and to @yonyitz  for passing this along!

**Comment by jrochkind** [comment]
There are actually currently two problems -- the facets are becoming "collapsible" at an earlier screen-width than intended. 

![Screen Shot 2021-02-02 at 12.07.30 PM.png](https://images.zenhubusercontent.com/5d81444759191331a1462f18/75f838c5-87f7-4790-ac9d-c83e292c1bd1)

They shoudln't be collapsed at all up there, since it is still two columns! 

They are supposed to be collapsed at one column as below:

![Screen Shot 2021-02-03 at 10.26.00 AM.png](https://images.zenhubusercontent.com/5d81444759191331a1462f18/86448d52-d2f5-4b03-9452-745c5ff3a86f)

And then at that point, it remains a problem that the white rectangle is missing the icon that used to be in it. Supposed to be a "hamburger" style.

**Comment by jrochkind** [comment]
Some CSS built into Blacklight is interacting with CSS custom to us in ways that are hard to disentangle, the BL CSS is complicated and weird. 

We are trying to make sidebar collapse at a different point than BL does. Should we give up on this and accept what BL does? First we'll see if we can alter BL somehow.

**Comment by jrochkind** [comment]
just for transparency, @MDiMeo i took this out of inbox and moved it to work on in-progress, cause I needed some "filler" work to do, and search results looking broken on mobile screens for at least a few months seemed like something to take care of.
