### ISSUE TITLE
Move emails from self-hosted server to AWS SES

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#760]
Since we're already getting SES setup for other projects, moving our collections emails to SES will remove the need to manage a local mailserver.

**Comment by jrochkind** [comment]
How to configure in Rails? Looks like best practices have changed over the few years since SES was released, so hard to google and not get outdated info. Maybe this gem?

https://github.com/drewblas/aws-ses

**Comment by jrochkind** [comment]
Possibly you can use SES with a standard SMTP interface? Then it wouldn't require any special gems on Rails end, just the SMTP host and other config info?

https://hixonrails.com/ruby-on-rails-tutorials/ruby-on-rails-action-mailer-configuration/#amazon-ses-account-setup

**Comment by sanfordd** [comment]
You can use STMP with SES
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html

**Comment by jrochkind** [comment]
We're probably going to need some emails for OH work, so tagging this with "oral histories" category, and we may have to get to it sooner rather than later. 

We think Dan may have already created an SES resource for us. It's unclear if he got it cleared for "production" use yet -- I think Amazon makes you manually email them to get a non-toy-sized email limit for production use. 

Then we just have to configure the app to use it, probably via connection details supplied in local_env.yml. 

Maybe @eddierubeiz would be interested in carrying this over the finish line.
