### ISSUE TITLE
Add runner tag to single jobs server

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#793]
As part of #792 it would be helpful to tag a single server as the one to run remotely invoked tasks. Add a runner role to one and only one jobs server.

**Comment by sanfordd** [comment]
Also adding #568 as a related ticket.

**Comment by jrochkind** [comment]
More related to #568  really -- now we can sometimes have more than one server with `jobs` role. 

But there are some things we mean  to run with capistrano _once_, on one server:


* running rake tasks
* (maybe) ssh'ing to a server
* (Does not apply, because we use `:cron` role, but similar) installing cron jobs

Currently we use `:jobs`  role to do some of this. But if there is more than one jobs role -- the capistrano task for "run a remote rake taks" for instance will end up doing it on each jobs server, when we really only want one. 

We could fix it to "run on only one of the jobs servers, arbitrarily".  But is arbittrarily enough? Is it okay that it might pick a "temporary" jobs server, or a "normal" jobs server?

Really, while the "jobs" server is a good server to run this sor tof stuff on, it's really a *different* role. "runner".  For, well, running one-off tasks. It might be assigned to (one of the) jobs servers, but it's a separate role. 

So maybe we can set things up so we assign it to the server we actually want to use for this role, and only one at a time.

**Comment by jrochkind** [comment]
closing, irrelevant in heroku envkronment
