### ISSUE TITLE
[Low priority] Asset listed as "not fully ingested" in the fixity report.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#806]
[The fixity report in production](https://digital.sciencehistory.org/admin/fixity_report)  lists one item as "Not yet fully ingested".
In the production console, searching for any assets where `"file_data ->> 'storage' != 'store' or file_data ->> 'storage' is NULL"` yields one asset, a collection thumbnail, `friendlier_id` = `860ka5o` .
We have other fires to put out at the moment, but I just wanted to make a note of this here.

**Comment by jrochkind** [comment]
The asset with `friendlier_id = 860ka5o` actually has no `file_data` at all. 

```
=> #<CollectionThumbAsset id: "67aaca2e-6b14-414a-a549-b286c82dc106", title: "collection-thumbnail-placeholder", type: "CollectionThumbAsset", position: nil, json_attributes: nil, created_at: "2020-06-02 18:09:59", updated_at: "2020-06-02 18:09:59", parent_id: "df82d600-8d65-48ca-8c68-534efe9ac997", friendlier_id: "860ka5o", file_data: nil, digitization_queue_item_id: nil, published: false, kithe_model_type: "asset">
```

Collections refer to their thumbnail (mis-)using `representative_id`, so we can find the Collection using this thumb like:

```
Collection.where(representative_id: "67aaca2e-6b14-414a-a549-b286c82dc106").first
```

It's "Papers of Georg and Max Bredig", which is not currently published. 

Is it intentional that it's not currently published? Is it intentional that it does not have a thumb? I will ask. 

My guess is that our logic for collection thumbs will end up creating a "placeholder" CollectionThumbAsset even if no thumbnail is assigned. 

We could:

* Fix the collection editing logic to not do this?
* Fix the fixity checking code to ignore "empty" assets?
* both?

**Comment by jrochkind** [comment]
Verified that creating a collection without adding a thumbnail currently creates a dummy "placeholder" Asset (actually CollectionThumbAsset subclass), that has no asset data in it.

**Comment by jrochkind** [comment]
> yes, that is intentional. These are test records for a project to gather info about metadata work related to these materials. Our plan is to publish the records when the collection is processed and the finding aid is available.

**Comment by jrochkind** [comment]
Did "Fix the collection editing logic to not do this" in #824. 

Went into production console and manually deleted "empty" Asset row for 860ka5o
