### ISSUE TITLE
Trouble with email on staging. (Production is fine.)

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#853]
https://app.honeybadger.io/projects/58989/faults/67279601 suggests the staging server may have run into an auth failure in attempting to send a fixity check failure email.

**Comment by eddierubeiz** [comment]
Easily reproducible on Staging. Go to https://staging-digital.sciencehistory.org/users/password/new,  type in your email and request a password reset.

**Comment by eddierubeiz** [comment]
The production server sends email correctly.

**Comment by jrochkind** [comment]
Error was on scihist-digicoll-jobs1-staging , so was trying to send email from jobs server, so that's the one to troubleshoot.

**Comment by jrochkind** [comment]
local_env.yml SMTP-related settings seem to be identical on `scihist-digicoll-jobs1-staging` and `scihist-digicoll-jobs1-production`. So this remains mysterious.

**Comment by eddierubeiz** [comment]
If the email settings are correctly loaded on the staging server, `action_mailer.smtp_settings` ought to look like:
```
irb(main):004:0> pp Rails.application.config.action_mailer.smtp_settings
{:address=>"email-smtp.us-east-1.amazonaws.com",
 :port=>587,
 :user_name=>"same_as_the_production_user_name",
 :password=>"same_as_the_production_password",
 :authentication=>:login,
 :enable_starttls_auto=>true}
```

**Comment by jrochkind** [comment]
Good idea @eddierubeiz , indeed  `Rails.application.config.action_mailer.smtp_settings` is **not** right on staging, it looks like:

    {:address=>"email-smtp.us-east-1.amazonaws.com", :domain=>"sciencehistory.org", :ssl=>false, :enable_starttls_auto=>false}

And yet `local_env.yml`   on staging _does_ look right. 

So... somehow staging is differing from production in how it loads local_env.yml?  That doesn't make a lot of sense, very odd, have to debug further.

**Comment by jrochkind** [comment]
Weird, on staging in a console when I try `ScihistDigicoll::Env.lookup(:smtp_username)`, I get `ArgumentError (No env key defined for: smtp_username)`

OK, I think we just have an old/wrong branch deployed to staging, one that doesn't have the new code! Will deploy master to staging....

**Comment by jrochkind** [comment]
Ha! OK, after actually deploying master to staging, `Rails.application.config.action_mailer.smtp_settings` is correct, and... a password reset email succesfully reaches me too. 

Issue was simply that an old branch (or a branch without changes in master merged into it) was deployed to staging. So it got the new smtp_host, without the new additional logic for username/password, and failed to email. 

False alarm!

And what this teaches us is the best "right" way to do this would be to somehow structure the logic and config variables in a way that a branch with the old logic would still succesfully send email the old way, even in the presence of new config. Instead of old logic/new config resulting in error unable to send email. I guess that would require a new duplicate set of config keys, and would be generally more confusing to roll out though. So I dunno.
