### ISSUE TITLE
Admin workflow for oral history requests.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#887]
_Placeholder issue._

_This covers some work that is peripheral to issue #828 and doesn't quite belong under the same heading._

Once we have the oral history request form in place, we should spend some time on any admin functionality we want to build to keep track and manage the requests. We will probably want:
- [ ] A screen to show all (or all recent) requests, detailing who requested the OH, when and why.
- [ ] If the request has a status (e.g. "pending", "fulfilled", etc.), or staff need to store notes on it, or it ever needs to be deleted, the admin interface needs to allow for that.

**Comment by eddierubeiz** [comment]
Getting rid of this issue; I noticed some verbiage in the ticket that I had overlooked before that specifies exactly what Lee wants.

**Comment by jrochkind** [comment]
To begin with, let's focus on the use case we have -- the ones that do not need human intervention, but will be fulfilled automatically immediately after form is filled out. 

So we don't need any status (pending, fulfilled etc) -- for this initial use case, the only reason something is in the table is because it's already fulfilled. 

I don't think we need a way to delete requests -- why would we, has this come up? I don't understand the use case. 

We do need a way for Lee to specify a range of dates and download a CSV. Secondarily, it would be convenient to list the most recent (by X number or date or both?) of requests in the web, so you can easily go check for recent activity without having to fill out dates and do a download. 

That's all we need for the first draft; if we end up needing more, we can add that after the first draft. Don't overcomplicate it or add work that may or may not be necessary, we start with the things we know are necessary without speculating.
