### ISSUE TITLE
Start using ICC colorspace profiles again in generating image derivatives.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#946]
Prior to January 8th, all derivatives generated at ingest were re-encoded as sRGB: `--eprofile srgb_profile.icc`
The --eprofile option was temporarily removed from the **image** thumbnail generation process in PR #943, which was merged and pushed to production on January 8th.
This means that newly ingested grayscale images (like [this one](https://digital.sciencehistory.org/works/frc2gjq))  will have grayscale derivatives; their derivatives won't be converted to sRGB.
If we decide to go back to having all our thumbnails encoded as sRGB, we should permanently fix the bug described in issue #942 and reinstate the `--eprofile` option.
After this is fixed, all images ingested after Jan. 8th will need to have their derivatives regenerated.

**Comment by jrochkind** [comment]
Ideally we'd do a bit of detective work to identify why we were using the eprofile option in the first place. 

I believe that without it, some images may have colors corrupted -- especially because I think we are also *stripping* profile information from the derivatives. I think this is safe to do only if they are SRGB. 

I think the current situation will result in corrupted color information in our thumbnails, and it should be prioritized to fix it.

**Comment by jrochkind** [comment]
@eddierubeiz writes:

> Note: https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html makes me wonder if we might be able to fix this by using --eprofile srgb.

I don't understand how this would make any difference?  If the problem was that a greyscale scan can not be moved to rgb colorspace?

However, it does seem preferable to what we were doing: "The magic string srgb selects a high-quality sRGB profile that’s built into libvips."  -- that was not available when we wrote previous code, there was no sRGB profile built into libvips, so we had to do it explicitly with an open source one we found. So this is an improvement to use the built-in one, but I wouldn't expect it to solve this problem.

**Comment by eddierubeiz** [comment]
Notes from Jonathan on slack:

_I’d say don’t be shy to file tickets or emails to ask for help figuring out what’s going on — why this works on one version and not another on vips for instance. The vips maintainer is very happy to answer questions and helpful.
Whether it is in fact broken on recent vips (as you wondered) or fixed on recent vips matters. Ask the vips maintainer?
If there’s a way to get more recent vips installed on heroku, if it appears to fix the bug. File a ticket on the github repo for the apt buildpack?
And then above are my thoughts for fixes if we can’t do either of those things. 1) Stop stripping profile too, even though it’s against best practices. 2) check if it’s greyscale first somehow and keep doing profile stuff only if it’s not.  3) maybe something else we haven’t thought of?
^^ make any of the above changes in kithe, not just an override._
