### ISSUE TITLE
Batch edit does not apply to Collection field

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#964]
I attempted to add work pr76f4633 and its child records to the Neville Collection using the cart, i.e. batch edit, and the edit didn't take (note: I subsequently edited the individual records to add them to the Collection). I played around a bit in staging and successfully edited other fields using the batch edit, but again, the collection edit didn't take. I have a vague memory that not all fields are enabled for batch editing, but could well be mis-remembering. This is low-priority - ultimately, I'd like to confirm whether or not the batch edit is intended to work for the Collection metadata field.

**Comment by jrochkind** [comment]
I think the developers just forgot about Collections when developing this feature. 

since collection does not have the same metadata as work... it's probably a mistake that it lets you add it to the cart for batch editing.  We just didn't think of that I think.

There probably only 2 or 3 fields in common between Collection and Work... I guess those 2 or 3 could be applied to Collections in batch edit too? And the others ignored for Collections? 

I'm not totally sure how this could/should work.

**Comment by HKativa** [comment]
Sorry, to clarify, I wasn't trying to edit a collection record. I was trying to batch edit works to add a value to the collection metadata field

**Comment by apinkney0696** [comment]
Applying a collection to the Collections metadata field in the batch edit feature still doesn't seem to work and I wanted to follow up with Hillary's initial inquiry. If the Collections field is not intended to work in batch edit, can we enable that functionality? It would be helpful to the ongoing mass dig projects. Thanks!

**Comment by jrochkind** [comment]
@MDiMeo just a ping to remind you that we rely on our Monday meetings to prioritize work, and don't generally work on things in "Inbox" unless you triage it to tell us to (or in some cases we realize it's an emergency on our own!)
